# Generated by scripts/sync_spec.py from spec/openapi/cell.json. Do not edit.
"""Every route of the turn record, typed state, subject signals and coordination, one method each, named as
the server names the operation: `niadra.api` (sync) and `AsyncNiadra.api` (async).

Unlike the rest of the SDK, these methods raise: an `APIError` subclass on an error answer, and
`NotAvailableError` (501) while the server has not built the route. The calls built on them decide what
fails open and what fails closed, per purpose. A route of a feature the space did not turn on answers
`NotFoundError`, as a route that does not exist.
"""

from __future__ import annotations

from datetime import date

from niadra._ids import new_key
from niadra._routes import AsyncRoutes, SyncRoutes, segment
from niadra.models.coordination import (
    CheckBatchRequest,
    CheckBatchResponse,
    CheckRequest,
    CheckResult,
    ClaimRelease,
    ClaimRequest,
    ContactKeys,
    CoordinationReportPage,
    DeclareRequest,
    DeclareResult,
    Effect,
    EffectReserve,
    EffectSettle,
    Handoff,
    HandoffCreate,
    HandoffOutcome,
    OwnershipClaim,
    ShadowRequest,
    ShadowRun,
    SuppressionPage,
    SuppressionSalt,
)
from niadra.models.signals import (
    AttributionReport,
    ConstraintsBlock,
    ConstraintsRequest,
    CounterfactualRun,
    CounterfactualRunCreate,
    Inference,
    InferenceCorrection,
    InferencePage,
    InterleavingReport,
    LegalHold,
    LegalHoldCreate,
    LegalHoldRelease,
    OutcomePage,
    PowerRequest,
    PowerResult,
    ReconcileRequest,
    ReconcileResult,
    ReviewRequest,
    ReviewRequestCreate,
    ReviewRequestPage,
    ReviewResolution,
    UnmetDemandPage,
)
from niadra.models.state import (
    AgentState,
    AgentStateReadRequest,
    AgentStateWrite,
    AgentStateWriteResult,
    ContentRelease,
    ContentReleaseResult,
    ObjectCoverage,
    ObjectPushRequest,
    ObjectPushResponse,
    ObjectSnapshotRequest,
    ObjectSnapshotResponse,
    RefreshRequestPage,
    SdkProfile,
    StateReadRequest,
    StateReadResponse,
    StateVerifyRequest,
    StateVerifyResponse,
    StateView,
    StateViewRequest,
    TypeFingerprintRequest,
    TypeFingerprintResponse,
)
from niadra.models.turns import (
    ChangePage,
    DataIssue,
    DataIssuePage,
    NotificationPage,
    PromoteRequest,
    PromoteResponse,
    ReplayCase,
    ReplayCaseRequest,
    Scenario,
    ScenarioCreate,
    ScenarioFromReport,
    ScenarioPage,
    ScenarioRun,
    ScenarioRunCreate,
    ScenarioUpdate,
    TurnSearchRequest,
    TurnSearchResponse,
    TurnsRequest,
    TurnsResponse,
    TurnView,
)


class Api(SyncRoutes):
    """The routes of `niadra.api`. See the module."""

    def changes(self, *, cursor: str | None = None, limit: int = 50) -> ChangePage:
        """`GET /v1/changes`."""
        return self._call(ChangePage, "GET", "/v1/changes", params={"cursor": cursor, "limit": limit})

    def data_issues(self, *, cursor: str | None = None, limit: int = 50) -> DataIssuePage:
        """`GET /v1/data-issues`."""
        return self._call(DataIssuePage, "GET", "/v1/data-issues", params={"cursor": cursor, "limit": limit})

    def acknowledge_data_issue(self, issue_id: str) -> DataIssue:
        """`POST /v1/data-issues/{issue_id}/ack`."""
        return self._call(DataIssue, "POST", f"/v1/data-issues/{segment(issue_id)}/ack")

    def replay_case(self, body: ReplayCaseRequest) -> ReplayCase:
        """`POST /v1/replay/cases`."""
        return self._call(ReplayCase, "POST", "/v1/replay/cases", body=body)

    def create_scenario_run(
        self, body: ScenarioRunCreate, *, idempotency_key: str | None = None
    ) -> ScenarioRun:
        """`POST /v1/scenario-runs`."""
        return self._call(
            ScenarioRun, "POST", "/v1/scenario-runs", body=body, key=idempotency_key or new_key()
        )

    def read_scenario_run(self, run_id: str) -> ScenarioRun:
        """`GET /v1/scenario-runs/{run_id}`."""
        return self._call(ScenarioRun, "GET", f"/v1/scenario-runs/{segment(run_id)}")

    def list_scenarios(self, *, cursor: str | None = None, limit: int = 50) -> ScenarioPage:
        """`GET /v1/scenarios`."""
        return self._call(ScenarioPage, "GET", "/v1/scenarios", params={"cursor": cursor, "limit": limit})

    def create_scenario(self, body: ScenarioCreate, *, idempotency_key: str | None = None) -> Scenario:
        """`POST /v1/scenarios`."""
        return self._call(Scenario, "POST", "/v1/scenarios", body=body, key=idempotency_key or new_key())

    def scenario_from_report(
        self, body: ScenarioFromReport, *, idempotency_key: str | None = None
    ) -> Scenario:
        """`POST /v1/scenarios/from-report`."""
        return self._call(
            Scenario, "POST", "/v1/scenarios/from-report", body=body, key=idempotency_key or new_key()
        )

    def update_scenario(self, scenario_id: str, body: ScenarioUpdate) -> Scenario:
        """`PATCH /v1/scenarios/{scenario_id}`."""
        return self._call(Scenario, "PATCH", f"/v1/scenarios/{segment(scenario_id)}", body=body)

    def record_turns(self, body: TurnsRequest) -> TurnsResponse:
        """`POST /v1/turns`. Up to 50 turn records, the body in zstd, gzip or plain JSON. The same turn sent
        twice is one turn.
        """
        return self._call(TurnsResponse, "POST", "/v1/turns", body=body)

    def promote_turns(self, body: PromoteRequest, *, idempotency_key: str | None = None) -> PromoteResponse:
        """`POST /v1/turns/promote`. Promoting is idempotent by itself: a turn promoted again counts as
        `already_kept`.
        """
        return self._call(
            PromoteResponse, "POST", "/v1/turns/promote", body=body, key=idempotency_key or new_key()
        )

    def search_turns(self, body: TurnSearchRequest) -> TurnSearchResponse:
        """`POST /v1/turns/search`. The kept tier, newest first, by conversation, agent, time and flags."""
        return self._call(TurnSearchResponse, "POST", "/v1/turns/search", body=body)

    def read_turn(self, turn_id: str) -> TurnView:
        """`GET /v1/turns/{turn_id}`. One turn from either tier, by its id: 404 once its tier let it go."""
        return self._call(TurnView, "GET", f"/v1/turns/{segment(turn_id)}")

    def notifications(self, *, cursor: str | None = None, limit: int = 100) -> NotificationPage:
        """`GET /v1/notifications`."""
        return self._call(
            NotificationPage, "GET", "/v1/notifications", params={"cursor": cursor, "limit": limit}
        )

    def write_agent_state(self, body: AgentStateWrite) -> AgentStateWriteResult:
        """`PUT /v1/agent-state`. A write by the agent's code: over the cap it answers `stored: false`, never
        an error.
        """
        return self._call(AgentStateWriteResult, "PUT", "/v1/agent-state", body=body)

    def read_agent_state(self, body: AgentStateReadRequest) -> AgentState:
        """`POST /v1/agent-state/read`. The working state of one scope and agent: version 0 and an empty body
        when it was never written.
        """
        return self._call(AgentState, "POST", "/v1/agent-state/read", body=body)

    def release_content(
        self, ref: str, body: ContentRelease, *, idempotency_key: str | None = None
    ) -> ContentReleaseResult:
        """`POST /v1/content/{ref}/release`."""
        return self._call(
            ContentReleaseResult,
            "POST",
            f"/v1/content/{segment(ref)}/release",
            body=body,
            key=idempotency_key or new_key(),
        )

    def object_coverage(self) -> ObjectCoverage:
        """`GET /v1/objects/coverage`."""
        return self._call(ObjectCoverage, "GET", "/v1/objects/coverage")

    def push_objects(self, body: ObjectPushRequest) -> ObjectPushResponse:
        """`POST /v1/objects/push`."""
        return self._call(ObjectPushResponse, "POST", "/v1/objects/push", body=body)

    def snapshot_objects(self, body: ObjectSnapshotRequest) -> ObjectSnapshotResponse:
        """`POST /v1/objects/snapshot`."""
        return self._call(ObjectSnapshotResponse, "POST", "/v1/objects/snapshot", body=body)

    def sdk_profile(self) -> SdkProfile:
        """`GET /v1/sdk/profile`. What the SDK keeps in its local cache, from the configuration alone: no
        database, no receipt.
        """
        return self._call(SdkProfile, "GET", "/v1/sdk/profile")

    def state_read(self, body: StateReadRequest) -> StateReadResponse:
        """`POST /v1/state/read`. Objects by reference, each for the read's purpose: values with their logical
        value, stamps, source and freshness computed now, what may not be claimed, and the refusal a
        `decide` read of a type asks for.
        """
        return self._call(StateReadResponse, "POST", "/v1/state/read", body=body)

    def refresh_requests(self, *, limit: int = 50) -> RefreshRequestPage:
        """`GET /v1/state/refresh-requests`."""
        return self._call(RefreshRequestPage, "GET", "/v1/state/refresh-requests", params={"limit": limit})

    def state_verify(self, body: StateVerifyRequest) -> StateVerifyResponse:
        """`POST /v1/state/verify`."""
        return self._call(StateVerifyResponse, "POST", "/v1/state/verify", body=body)

    def state_view(self, body: StateViewRequest) -> StateView:
        """`POST /v1/state/view`."""
        return self._call(StateView, "POST", "/v1/state/view", body=body)

    def type_fingerprint(self, body: TypeFingerprintRequest) -> TypeFingerprintResponse:
        """`POST /v1/types/fingerprint`."""
        return self._call(TypeFingerprintResponse, "POST", "/v1/types/fingerprint", body=body)

    def constraints(self, body: ConstraintsRequest) -> ConstraintsBlock:
        """`POST /v1/constraints`. The constraints block of one subject, the one `include: ["constraints"]`
        adds to a context read; `for` asks for a beneficiary's.
        """
        return self._call(ConstraintsBlock, "POST", "/v1/constraints", body=body)

    def create_legal_hold(self, body: LegalHoldCreate, *, idempotency_key: str | None = None) -> LegalHold:
        """`POST /v1/legal-holds`."""
        return self._call(LegalHold, "POST", "/v1/legal-holds", body=body, key=idempotency_key or new_key())

    def release_legal_hold(self, hold_id: str, body: LegalHoldRelease) -> LegalHold:
        """`POST /v1/legal-holds/{hold_id}/release`."""
        return self._call(LegalHold, "POST", f"/v1/legal-holds/{segment(hold_id)}/release", body=body)

    def attribution(self, *, since: date, until: date) -> AttributionReport:
        """`GET /v1/measure/attribution`."""
        return self._call(
            AttributionReport, "GET", "/v1/measure/attribution", params={"since": since, "until": until}
        )

    def counterfactual_run(self, body: CounterfactualRunCreate) -> CounterfactualRun:
        """`POST /v1/measure/counterfactual-runs`."""
        return self._call(CounterfactualRun, "POST", "/v1/measure/counterfactual-runs", body=body)

    def interleaving(self) -> InterleavingReport:
        """`GET /v1/measure/interleaving`."""
        return self._call(InterleavingReport, "GET", "/v1/measure/interleaving")

    def outcomes(self, *, cursor: str | None = None, limit: int = 50) -> OutcomePage:
        """`GET /v1/measure/outcomes`."""
        return self._call(
            OutcomePage, "GET", "/v1/measure/outcomes", params={"cursor": cursor, "limit": limit}
        )

    def power(self, body: PowerRequest) -> PowerResult:
        """`POST /v1/measure/power`."""
        return self._call(PowerResult, "POST", "/v1/measure/power", body=body)

    def reconcile(self, body: ReconcileRequest) -> ReconcileResult:
        """`POST /v1/measure/reconcile`."""
        return self._call(ReconcileResult, "POST", "/v1/measure/reconcile", body=body)

    def unmet_demand(self, *, cursor: str | None = None, limit: int = 50) -> UnmetDemandPage:
        """`GET /v1/measure/unmet-demand`."""
        return self._call(
            UnmetDemandPage, "GET", "/v1/measure/unmet-demand", params={"cursor": cursor, "limit": limit}
        )

    def list_inferences(
        self, profile_id: str, *, cursor: str | None = None, limit: int = 50
    ) -> InferencePage:
        """`GET /v1/profiles/{profile_id}/inferences`."""
        return self._call(
            InferencePage,
            "GET",
            f"/v1/profiles/{segment(profile_id)}/inferences",
            params={"cursor": cursor, "limit": limit},
        )

    def delete_inference(self, profile_id: str, key: str) -> None:
        """`DELETE /v1/profiles/{profile_id}/inferences/{key}`."""
        return self._send("DELETE", f"/v1/profiles/{segment(profile_id)}/inferences/{segment(key)}")

    def correct_inference(self, profile_id: str, key: str, body: InferenceCorrection) -> Inference:
        """`POST /v1/profiles/{profile_id}/inferences/{key}/correct`."""
        return self._call(
            Inference,
            "POST",
            f"/v1/profiles/{segment(profile_id)}/inferences/{segment(key)}/correct",
            body=body,
        )

    def create_review_request(
        self, profile_id: str, body: ReviewRequestCreate, *, idempotency_key: str | None = None
    ) -> ReviewRequest:
        """`POST /v1/profiles/{profile_id}/review-requests`."""
        return self._call(
            ReviewRequest,
            "POST",
            f"/v1/profiles/{segment(profile_id)}/review-requests",
            body=body,
            key=idempotency_key or new_key(),
        )

    def list_review_requests(self, *, cursor: str | None = None, limit: int = 50) -> ReviewRequestPage:
        """`GET /v1/review-requests`."""
        return self._call(
            ReviewRequestPage, "GET", "/v1/review-requests", params={"cursor": cursor, "limit": limit}
        )

    def resolve_review_request(self, request_id: str, body: ReviewResolution) -> ReviewRequest:
        """`POST /v1/review-requests/{request_id}/resolve`."""
        return self._call(
            ReviewRequest, "POST", f"/v1/review-requests/{segment(request_id)}/resolve", body=body
        )

    def contact_keys(self, *, space: str) -> ContactKeys:
        """`GET /.well-known/niadra-contact-keys.json`."""
        return self._call(
            ContactKeys, "GET", "/.well-known/niadra-contact-keys.json", params={"space": space}
        )

    def check(self, body: CheckRequest) -> CheckResult:
        """`POST /v1/coordination/check`."""
        return self._call(CheckResult, "POST", "/v1/coordination/check", body=body)

    def check_batch(self, body: CheckBatchRequest) -> CheckBatchResponse:
        """`POST /v1/coordination/check/batch`."""
        return self._call(CheckBatchResponse, "POST", "/v1/coordination/check/batch", body=body)

    def claim(self, body: ClaimRequest, *, idempotency_key: str | None = None) -> OwnershipClaim:
        """`POST /v1/coordination/claims`."""
        return self._call(
            OwnershipClaim, "POST", "/v1/coordination/claims", body=body, key=idempotency_key or new_key()
        )

    def release_claim(
        self, claim_id: str, body: ClaimRelease, *, idempotency_key: str | None = None
    ) -> OwnershipClaim:
        """`POST /v1/coordination/claims/{claim_id}/release`."""
        return self._call(
            OwnershipClaim,
            "POST",
            f"/v1/coordination/claims/{segment(claim_id)}/release",
            body=body,
            key=idempotency_key or new_key(),
        )

    def declare(self, body: DeclareRequest, *, idempotency_key: str | None = None) -> DeclareResult:
        """`POST /v1/coordination/declare`."""
        return self._call(
            DeclareResult, "POST", "/v1/coordination/declare", body=body, key=idempotency_key or new_key()
        )

    def reserve_effect(self, body: EffectReserve, *, idempotency_key: str | None = None) -> Effect | None:
        """`POST /v1/coordination/effects`."""
        return self._call_optional(
            Effect, "POST", "/v1/coordination/effects", body=body, key=idempotency_key or new_key()
        )

    def settle_effect(
        self, effect_id: str, body: EffectSettle, *, idempotency_key: str | None = None
    ) -> Effect:
        """`POST /v1/coordination/effects/{effect_id}/settle`."""
        return self._call(
            Effect,
            "POST",
            f"/v1/coordination/effects/{segment(effect_id)}/settle",
            body=body,
            key=idempotency_key or new_key(),
        )

    def reports(self, *, cursor: str | None = None, limit: int = 50) -> CoordinationReportPage:
        """`GET /v1/coordination/reports`."""
        return self._call(
            CoordinationReportPage,
            "GET",
            "/v1/coordination/reports",
            params={"cursor": cursor, "limit": limit},
        )

    def shadow(self, body: ShadowRequest) -> ShadowRun:
        """`POST /v1/coordination/shadow`."""
        return self._call(ShadowRun, "POST", "/v1/coordination/shadow", body=body)

    def create_handoff(self, body: HandoffCreate, *, idempotency_key: str | None = None) -> Handoff:
        """`POST /v1/handoffs`."""
        return self._call(Handoff, "POST", "/v1/handoffs", body=body, key=idempotency_key or new_key())

    def read_handoff(self, handoff_id: str) -> Handoff:
        """`GET /v1/handoffs/{handoff_id}`."""
        return self._call(Handoff, "GET", f"/v1/handoffs/{segment(handoff_id)}")

    def accept_handoff(self, handoff_id: str, *, idempotency_key: str | None = None) -> Handoff:
        """`POST /v1/handoffs/{handoff_id}/accept`."""
        return self._call(
            Handoff, "POST", f"/v1/handoffs/{segment(handoff_id)}/accept", key=idempotency_key or new_key()
        )

    def handoff_outcome(
        self, handoff_id: str, body: HandoffOutcome, *, idempotency_key: str | None = None
    ) -> Handoff:
        """`POST /v1/handoffs/{handoff_id}/outcome`."""
        return self._call(
            Handoff,
            "POST",
            f"/v1/handoffs/{segment(handoff_id)}/outcome",
            body=body,
            key=idempotency_key or new_key(),
        )

    def suppressions(self, *, cursor: str | None = None, limit: int = 200) -> SuppressionPage:
        """`GET /v1/suppressions`."""
        return self._call(
            SuppressionPage, "GET", "/v1/suppressions", params={"cursor": cursor, "limit": limit}
        )

    def suppression_salt(self) -> SuppressionSalt:
        """`GET /v1/suppressions/salt`."""
        return self._call(SuppressionSalt, "GET", "/v1/suppressions/salt")


class AsyncApi(AsyncRoutes):
    """The routes of `AsyncNiadra.api`. See the module."""

    async def changes(self, *, cursor: str | None = None, limit: int = 50) -> ChangePage:
        """`GET /v1/changes`."""
        return await self._call(ChangePage, "GET", "/v1/changes", params={"cursor": cursor, "limit": limit})

    async def data_issues(self, *, cursor: str | None = None, limit: int = 50) -> DataIssuePage:
        """`GET /v1/data-issues`."""
        return await self._call(
            DataIssuePage, "GET", "/v1/data-issues", params={"cursor": cursor, "limit": limit}
        )

    async def acknowledge_data_issue(self, issue_id: str) -> DataIssue:
        """`POST /v1/data-issues/{issue_id}/ack`."""
        return await self._call(DataIssue, "POST", f"/v1/data-issues/{segment(issue_id)}/ack")

    async def replay_case(self, body: ReplayCaseRequest) -> ReplayCase:
        """`POST /v1/replay/cases`."""
        return await self._call(ReplayCase, "POST", "/v1/replay/cases", body=body)

    async def create_scenario_run(
        self, body: ScenarioRunCreate, *, idempotency_key: str | None = None
    ) -> ScenarioRun:
        """`POST /v1/scenario-runs`."""
        return await self._call(
            ScenarioRun, "POST", "/v1/scenario-runs", body=body, key=idempotency_key or new_key()
        )

    async def read_scenario_run(self, run_id: str) -> ScenarioRun:
        """`GET /v1/scenario-runs/{run_id}`."""
        return await self._call(ScenarioRun, "GET", f"/v1/scenario-runs/{segment(run_id)}")

    async def list_scenarios(self, *, cursor: str | None = None, limit: int = 50) -> ScenarioPage:
        """`GET /v1/scenarios`."""
        return await self._call(
            ScenarioPage, "GET", "/v1/scenarios", params={"cursor": cursor, "limit": limit}
        )

    async def create_scenario(self, body: ScenarioCreate, *, idempotency_key: str | None = None) -> Scenario:
        """`POST /v1/scenarios`."""
        return await self._call(
            Scenario, "POST", "/v1/scenarios", body=body, key=idempotency_key or new_key()
        )

    async def scenario_from_report(
        self, body: ScenarioFromReport, *, idempotency_key: str | None = None
    ) -> Scenario:
        """`POST /v1/scenarios/from-report`."""
        return await self._call(
            Scenario, "POST", "/v1/scenarios/from-report", body=body, key=idempotency_key or new_key()
        )

    async def update_scenario(self, scenario_id: str, body: ScenarioUpdate) -> Scenario:
        """`PATCH /v1/scenarios/{scenario_id}`."""
        return await self._call(Scenario, "PATCH", f"/v1/scenarios/{segment(scenario_id)}", body=body)

    async def record_turns(self, body: TurnsRequest) -> TurnsResponse:
        """`POST /v1/turns`. Up to 50 turn records, the body in zstd, gzip or plain JSON. The same turn sent
        twice is one turn.
        """
        return await self._call(TurnsResponse, "POST", "/v1/turns", body=body)

    async def promote_turns(
        self, body: PromoteRequest, *, idempotency_key: str | None = None
    ) -> PromoteResponse:
        """`POST /v1/turns/promote`. Promoting is idempotent by itself: a turn promoted again counts as
        `already_kept`.
        """
        return await self._call(
            PromoteResponse, "POST", "/v1/turns/promote", body=body, key=idempotency_key or new_key()
        )

    async def search_turns(self, body: TurnSearchRequest) -> TurnSearchResponse:
        """`POST /v1/turns/search`. The kept tier, newest first, by conversation, agent, time and flags."""
        return await self._call(TurnSearchResponse, "POST", "/v1/turns/search", body=body)

    async def read_turn(self, turn_id: str) -> TurnView:
        """`GET /v1/turns/{turn_id}`. One turn from either tier, by its id: 404 once its tier let it go."""
        return await self._call(TurnView, "GET", f"/v1/turns/{segment(turn_id)}")

    async def notifications(self, *, cursor: str | None = None, limit: int = 100) -> NotificationPage:
        """`GET /v1/notifications`."""
        return await self._call(
            NotificationPage, "GET", "/v1/notifications", params={"cursor": cursor, "limit": limit}
        )

    async def write_agent_state(self, body: AgentStateWrite) -> AgentStateWriteResult:
        """`PUT /v1/agent-state`. A write by the agent's code: over the cap it answers `stored: false`, never
        an error.
        """
        return await self._call(AgentStateWriteResult, "PUT", "/v1/agent-state", body=body)

    async def read_agent_state(self, body: AgentStateReadRequest) -> AgentState:
        """`POST /v1/agent-state/read`. The working state of one scope and agent: version 0 and an empty body
        when it was never written.
        """
        return await self._call(AgentState, "POST", "/v1/agent-state/read", body=body)

    async def release_content(
        self, ref: str, body: ContentRelease, *, idempotency_key: str | None = None
    ) -> ContentReleaseResult:
        """`POST /v1/content/{ref}/release`."""
        return await self._call(
            ContentReleaseResult,
            "POST",
            f"/v1/content/{segment(ref)}/release",
            body=body,
            key=idempotency_key or new_key(),
        )

    async def object_coverage(self) -> ObjectCoverage:
        """`GET /v1/objects/coverage`."""
        return await self._call(ObjectCoverage, "GET", "/v1/objects/coverage")

    async def push_objects(self, body: ObjectPushRequest) -> ObjectPushResponse:
        """`POST /v1/objects/push`."""
        return await self._call(ObjectPushResponse, "POST", "/v1/objects/push", body=body)

    async def snapshot_objects(self, body: ObjectSnapshotRequest) -> ObjectSnapshotResponse:
        """`POST /v1/objects/snapshot`."""
        return await self._call(ObjectSnapshotResponse, "POST", "/v1/objects/snapshot", body=body)

    async def sdk_profile(self) -> SdkProfile:
        """`GET /v1/sdk/profile`. What the SDK keeps in its local cache, from the configuration alone: no
        database, no receipt.
        """
        return await self._call(SdkProfile, "GET", "/v1/sdk/profile")

    async def state_read(self, body: StateReadRequest) -> StateReadResponse:
        """`POST /v1/state/read`. Objects by reference, each for the read's purpose: values with their logical
        value, stamps, source and freshness computed now, what may not be claimed, and the refusal a
        `decide` read of a type asks for.
        """
        return await self._call(StateReadResponse, "POST", "/v1/state/read", body=body)

    async def refresh_requests(self, *, limit: int = 50) -> RefreshRequestPage:
        """`GET /v1/state/refresh-requests`."""
        return await self._call(
            RefreshRequestPage, "GET", "/v1/state/refresh-requests", params={"limit": limit}
        )

    async def state_verify(self, body: StateVerifyRequest) -> StateVerifyResponse:
        """`POST /v1/state/verify`."""
        return await self._call(StateVerifyResponse, "POST", "/v1/state/verify", body=body)

    async def state_view(self, body: StateViewRequest) -> StateView:
        """`POST /v1/state/view`."""
        return await self._call(StateView, "POST", "/v1/state/view", body=body)

    async def type_fingerprint(self, body: TypeFingerprintRequest) -> TypeFingerprintResponse:
        """`POST /v1/types/fingerprint`."""
        return await self._call(TypeFingerprintResponse, "POST", "/v1/types/fingerprint", body=body)

    async def constraints(self, body: ConstraintsRequest) -> ConstraintsBlock:
        """`POST /v1/constraints`. The constraints block of one subject, the one `include: ["constraints"]`
        adds to a context read; `for` asks for a beneficiary's.
        """
        return await self._call(ConstraintsBlock, "POST", "/v1/constraints", body=body)

    async def create_legal_hold(
        self, body: LegalHoldCreate, *, idempotency_key: str | None = None
    ) -> LegalHold:
        """`POST /v1/legal-holds`."""
        return await self._call(
            LegalHold, "POST", "/v1/legal-holds", body=body, key=idempotency_key or new_key()
        )

    async def release_legal_hold(self, hold_id: str, body: LegalHoldRelease) -> LegalHold:
        """`POST /v1/legal-holds/{hold_id}/release`."""
        return await self._call(LegalHold, "POST", f"/v1/legal-holds/{segment(hold_id)}/release", body=body)

    async def attribution(self, *, since: date, until: date) -> AttributionReport:
        """`GET /v1/measure/attribution`."""
        return await self._call(
            AttributionReport, "GET", "/v1/measure/attribution", params={"since": since, "until": until}
        )

    async def counterfactual_run(self, body: CounterfactualRunCreate) -> CounterfactualRun:
        """`POST /v1/measure/counterfactual-runs`."""
        return await self._call(CounterfactualRun, "POST", "/v1/measure/counterfactual-runs", body=body)

    async def interleaving(self) -> InterleavingReport:
        """`GET /v1/measure/interleaving`."""
        return await self._call(InterleavingReport, "GET", "/v1/measure/interleaving")

    async def outcomes(self, *, cursor: str | None = None, limit: int = 50) -> OutcomePage:
        """`GET /v1/measure/outcomes`."""
        return await self._call(
            OutcomePage, "GET", "/v1/measure/outcomes", params={"cursor": cursor, "limit": limit}
        )

    async def power(self, body: PowerRequest) -> PowerResult:
        """`POST /v1/measure/power`."""
        return await self._call(PowerResult, "POST", "/v1/measure/power", body=body)

    async def reconcile(self, body: ReconcileRequest) -> ReconcileResult:
        """`POST /v1/measure/reconcile`."""
        return await self._call(ReconcileResult, "POST", "/v1/measure/reconcile", body=body)

    async def unmet_demand(self, *, cursor: str | None = None, limit: int = 50) -> UnmetDemandPage:
        """`GET /v1/measure/unmet-demand`."""
        return await self._call(
            UnmetDemandPage, "GET", "/v1/measure/unmet-demand", params={"cursor": cursor, "limit": limit}
        )

    async def list_inferences(
        self, profile_id: str, *, cursor: str | None = None, limit: int = 50
    ) -> InferencePage:
        """`GET /v1/profiles/{profile_id}/inferences`."""
        return await self._call(
            InferencePage,
            "GET",
            f"/v1/profiles/{segment(profile_id)}/inferences",
            params={"cursor": cursor, "limit": limit},
        )

    async def delete_inference(self, profile_id: str, key: str) -> None:
        """`DELETE /v1/profiles/{profile_id}/inferences/{key}`."""
        return await self._send("DELETE", f"/v1/profiles/{segment(profile_id)}/inferences/{segment(key)}")

    async def correct_inference(self, profile_id: str, key: str, body: InferenceCorrection) -> Inference:
        """`POST /v1/profiles/{profile_id}/inferences/{key}/correct`."""
        return await self._call(
            Inference,
            "POST",
            f"/v1/profiles/{segment(profile_id)}/inferences/{segment(key)}/correct",
            body=body,
        )

    async def create_review_request(
        self, profile_id: str, body: ReviewRequestCreate, *, idempotency_key: str | None = None
    ) -> ReviewRequest:
        """`POST /v1/profiles/{profile_id}/review-requests`."""
        return await self._call(
            ReviewRequest,
            "POST",
            f"/v1/profiles/{segment(profile_id)}/review-requests",
            body=body,
            key=idempotency_key or new_key(),
        )

    async def list_review_requests(self, *, cursor: str | None = None, limit: int = 50) -> ReviewRequestPage:
        """`GET /v1/review-requests`."""
        return await self._call(
            ReviewRequestPage, "GET", "/v1/review-requests", params={"cursor": cursor, "limit": limit}
        )

    async def resolve_review_request(self, request_id: str, body: ReviewResolution) -> ReviewRequest:
        """`POST /v1/review-requests/{request_id}/resolve`."""
        return await self._call(
            ReviewRequest, "POST", f"/v1/review-requests/{segment(request_id)}/resolve", body=body
        )

    async def contact_keys(self, *, space: str) -> ContactKeys:
        """`GET /.well-known/niadra-contact-keys.json`."""
        return await self._call(
            ContactKeys, "GET", "/.well-known/niadra-contact-keys.json", params={"space": space}
        )

    async def check(self, body: CheckRequest) -> CheckResult:
        """`POST /v1/coordination/check`."""
        return await self._call(CheckResult, "POST", "/v1/coordination/check", body=body)

    async def check_batch(self, body: CheckBatchRequest) -> CheckBatchResponse:
        """`POST /v1/coordination/check/batch`."""
        return await self._call(CheckBatchResponse, "POST", "/v1/coordination/check/batch", body=body)

    async def claim(self, body: ClaimRequest, *, idempotency_key: str | None = None) -> OwnershipClaim:
        """`POST /v1/coordination/claims`."""
        return await self._call(
            OwnershipClaim, "POST", "/v1/coordination/claims", body=body, key=idempotency_key or new_key()
        )

    async def release_claim(
        self, claim_id: str, body: ClaimRelease, *, idempotency_key: str | None = None
    ) -> OwnershipClaim:
        """`POST /v1/coordination/claims/{claim_id}/release`."""
        return await self._call(
            OwnershipClaim,
            "POST",
            f"/v1/coordination/claims/{segment(claim_id)}/release",
            body=body,
            key=idempotency_key or new_key(),
        )

    async def declare(self, body: DeclareRequest, *, idempotency_key: str | None = None) -> DeclareResult:
        """`POST /v1/coordination/declare`."""
        return await self._call(
            DeclareResult, "POST", "/v1/coordination/declare", body=body, key=idempotency_key or new_key()
        )

    async def reserve_effect(
        self, body: EffectReserve, *, idempotency_key: str | None = None
    ) -> Effect | None:
        """`POST /v1/coordination/effects`."""
        return await self._call_optional(
            Effect, "POST", "/v1/coordination/effects", body=body, key=idempotency_key or new_key()
        )

    async def settle_effect(
        self, effect_id: str, body: EffectSettle, *, idempotency_key: str | None = None
    ) -> Effect:
        """`POST /v1/coordination/effects/{effect_id}/settle`."""
        return await self._call(
            Effect,
            "POST",
            f"/v1/coordination/effects/{segment(effect_id)}/settle",
            body=body,
            key=idempotency_key or new_key(),
        )

    async def reports(self, *, cursor: str | None = None, limit: int = 50) -> CoordinationReportPage:
        """`GET /v1/coordination/reports`."""
        return await self._call(
            CoordinationReportPage,
            "GET",
            "/v1/coordination/reports",
            params={"cursor": cursor, "limit": limit},
        )

    async def shadow(self, body: ShadowRequest) -> ShadowRun:
        """`POST /v1/coordination/shadow`."""
        return await self._call(ShadowRun, "POST", "/v1/coordination/shadow", body=body)

    async def create_handoff(self, body: HandoffCreate, *, idempotency_key: str | None = None) -> Handoff:
        """`POST /v1/handoffs`."""
        return await self._call(Handoff, "POST", "/v1/handoffs", body=body, key=idempotency_key or new_key())

    async def read_handoff(self, handoff_id: str) -> Handoff:
        """`GET /v1/handoffs/{handoff_id}`."""
        return await self._call(Handoff, "GET", f"/v1/handoffs/{segment(handoff_id)}")

    async def accept_handoff(self, handoff_id: str, *, idempotency_key: str | None = None) -> Handoff:
        """`POST /v1/handoffs/{handoff_id}/accept`."""
        return await self._call(
            Handoff, "POST", f"/v1/handoffs/{segment(handoff_id)}/accept", key=idempotency_key or new_key()
        )

    async def handoff_outcome(
        self, handoff_id: str, body: HandoffOutcome, *, idempotency_key: str | None = None
    ) -> Handoff:
        """`POST /v1/handoffs/{handoff_id}/outcome`."""
        return await self._call(
            Handoff,
            "POST",
            f"/v1/handoffs/{segment(handoff_id)}/outcome",
            body=body,
            key=idempotency_key or new_key(),
        )

    async def suppressions(self, *, cursor: str | None = None, limit: int = 200) -> SuppressionPage:
        """`GET /v1/suppressions`."""
        return await self._call(
            SuppressionPage, "GET", "/v1/suppressions", params={"cursor": cursor, "limit": limit}
        )

    async def suppression_salt(self) -> SuppressionSalt:
        """`GET /v1/suppressions/salt`."""
        return await self._call(SuppressionSalt, "GET", "/v1/suppressions/salt")
