"""Keeps the SDK's copies of the Niadra specifications current, and writes the code generated from them.

    uv run python scripts/sync_spec.py
    uv run python scripts/sync_spec.py --server ../niadra-back --spec ../niadra-spec

`--server` cuts the routes tagged in `TAGS` out of the server's OpenAPI document (`openapi/cell.json`) into
`spec/openapi/cell.json`, with every schema they reach and its text as a public SDK may carry it. `--spec`
copies the conformance vectors (`vectors/*.json`) and the claim contract and turn record examples. Every run
then writes the models of those routes (`src/niadra/models/<module>.py`) and their methods
(`src/niadra/api.py`) from `spec/openapi/cell.json`, formatted by ruff. `tests/test_generated.py` fails when
a generated file differs from what this script writes, so regenerating is this one command.
"""

from __future__ import annotations

import argparse
import copy
import json
import keyword
import re
import shutil
import subprocess
import sys
import textwrap
from collections.abc import Iterator
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
CUT = ROOT / "spec" / "openapi" / "cell.json"
HEADER = "# Generated by scripts/sync_spec.py from spec/openapi/cell.json. Do not edit.\n"

# The server's route tags this SDK generates, and the module their models go to. A schema lands in the
# module of the first tag, in this order, whose routes reach it, so a module imports only from those above.
TAGS = {
    "turns": "turns",
    "notifications": "turns",
    "state": "state",
    "signals": "signals",
    "coordination": "coordination",
}
MODULE_DOCS = {
    "turns": "Turn records, replay, scenarios, the change log, data issues and the notification feed.",
    "state": "Typed state: objects a system of record pushes, reads with a purpose, the agent's working "
    "state and the SDK profile.",
    "signals": "Subject signals, the constraints block, the reviewable profile, review requests, legal "
    "holds and measurement.",
    "coordination": "Ownership and effects: the coordination decision, declarations, claims and locks, "
    "effects exactly once, handoffs, suppressions and the contact token's public keys.",
}
API_DOC = """Every route of the turn record, typed state, subject signals and coordination, one method each,
named as the server names the operation: `niadra.api` (sync) and `AsyncNiadra.api` (async).

Unlike the rest of the SDK, these methods raise: an `APIError` subclass on an error answer, and
`NotAvailableError` (501) while the server has not built the route. The calls built on them decide what
fails open and what fails closed, per purpose. A route of a feature the space did not turn on answers
`NotFoundError`, as a route that does not exist."""
# Schemas the SDK already mirrors by hand, and where they live.
EXISTING = {
    "Handle": "niadra.models.common",
    "ObjectRef": "niadra.models.common",
    "Problem": "niadra.models.common",
    "ItemError": "niadra.models.events",
    "HandleType": "niadra.vocabulary",
    "SubjectKind": "niadra.vocabulary",
    "Verification": "niadra.vocabulary",
}
# Constrained strings the server names, by (minLength, maxLength, pattern). A module declares the ones it
# uses; a name followed by module names applies only in those.
STRING_ALIASES = {
    (1, 256, None): "ShortStr",
    (1, 512, None): "IdStr",
    (1, 128, None): "Version turns",
    (None, None, r"^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$"): "TurnId",
    (None, None, r"^[a-z]{1,8}:[A-Za-z0-9_-]{1,32}$"): "BlobKey",
    (None, None, r"^sha256:[0-9a-f]{64}$"): "Sha256",
    (None, None, r"^[a-z][a-z0-9_]{0,39}:[^:\s]{1,256}:\S{1,512}$"): "ObjectKey",
    (None, None, r"^[a-z][a-z0-9_]{0,39}$"): "TypeName",
}
SHARED_ALIASES = {"ShortStr", "IdStr"}
# Wire names that are not Python names, named as the server's models name them.
FIELD_NAMES = {"in": "input", "out": "output"}
# Words that name how the server was planned and built, never what it does: a public SDK carries none.
INTERNAL = re.compile(
    r"\bfronts? A\d\b|\(A\d\)|\b(?:core|the) wave\b|\bphase \d\b|\bintegrator\b|\bstudy \d+\b|\bestudo\b",
    re.IGNORECASE,
)
SUCCESS = ("200", "201", "202", "204", "207")
WIDTH = 110


def main() -> None:
    parser = argparse.ArgumentParser(prog="sync_spec", description=(__doc__ or "").split("\n\n")[0])
    parser.add_argument("--server", type=Path, help="a server checkout, to cut its OpenAPI document")
    parser.add_argument("--spec", type=Path, help="a checkout of the open specifications, for the vectors")
    args = parser.parse_args()
    if args.server:
        document = json.loads((args.server / "openapi" / "cell.json").read_text())
        CUT.parent.mkdir(parents=True, exist_ok=True)
        CUT.write_text(json.dumps(cut(document), indent=2, sort_keys=True, ensure_ascii=False) + "\n")
    if args.spec:
        copy_vectors(args.spec)
    for path, text in generate(json.loads(CUT.read_text())).items():
        (ROOT / path).write_text(text)
        print(f"wrote {path}")


def copy_vectors(spec: Path) -> None:
    for pattern in ("vectors/*.json", "examples/claim-contract/*.json", "examples/turn-record/*.json"):
        for source in sorted(spec.glob(pattern)):
            relative = source.relative_to(spec)
            destination = ROOT / "spec" / relative
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(source, destination)
            print(f"copied {relative}")


def cut(document: dict[str, Any]) -> dict[str, Any]:
    """The operations tagged in `TAGS` and the schemas they reach, as an OpenAPI document of its own."""
    paths: dict[str, Any] = {}
    for path, methods in document["paths"].items():
        kept = {m: copy.deepcopy(op) for m, op in methods.items() if set(op.get("tags") or ()) & set(TAGS)}
        if kept:
            paths[path] = kept
    schemas = dict(document["components"]["schemas"])
    for methods in paths.values():
        for op in methods.values():
            _hoist_body(op, schemas)
    reached = {name: schemas[name] for name in _reach(paths, schemas)}
    renamed = _split_names(reached)
    return _published(
        _renamed(
            {
                "openapi": document["openapi"],
                "info": document["info"],
                "paths": paths,
                "components": {"schemas": {renamed.get(n, n): reached[n] for n in sorted(reached)}},
            },
            renamed,
        ),
        "",
    )


def _split_names(schemas: dict[str, Any]) -> dict[str, str]:
    """Names for the halves of a model the server documents twice, as it validates it and as it serializes
    it (`Name-Input`, `Name-Output`): the model's own name for one of them, and `NameOutput` when both are
    reached."""
    renamed: dict[str, str] = {}
    for name in schemas:
        base, _, half = name.rpartition("-")
        if half not in ("Input", "Output") or not base:
            continue
        both = f"{base}-Input" in schemas and f"{base}-Output" in schemas
        target = f"{base}Output" if both and half == "Output" else base
        if target in schemas:
            raise ValueError(f"{name}: the name {target} is taken")
        renamed[name] = target
    return renamed


def _renamed(node: Any, renamed: dict[str, str]) -> Any:
    """`node` with every reference to a renamed schema following it."""
    if isinstance(node, list):
        return [_renamed(v, renamed) for v in node]
    if not isinstance(node, dict):
        return node
    out = {k: _renamed(v, renamed) for k, v in node.items()}
    ref = out.get("$ref")
    if isinstance(ref, str) and _name(ref) in renamed:
        out["$ref"] = f"#/components/schemas/{renamed[_name(ref)]}"
    return out


def _hoist_body(op: dict[str, Any], schemas: dict[str, Any]) -> None:
    """A body the server declares inline (a route that parses its own body) as the named schema it is."""
    content = op.get("requestBody", {}).get("content", {}).get("application/json")
    if not content or "$ref" in content["schema"]:
        return
    schema = {k: v for k, v in content["schema"].items() if k != "$id"}
    name = schema.get("title")
    if not name or schemas.get(name, schema) != schema:
        raise ValueError(f"{op['operationId']}: an inline body with no title of its own")
    schemas[name] = schema
    content["schema"] = {"$ref": f"#/components/schemas/{name}"}


def _published(node: Any, where: str) -> Any:
    """`node` with every description as a public SDK may carry it (`public`)."""
    if isinstance(node, list):
        return [_published(v, where) for v in node]
    if not isinstance(node, dict):
        return node
    out = {}
    for key, value in node.items():
        if key == "description" and isinstance(value, str):
            text = public(value, where)
            if text:
                out[key] = text
        else:
            out[key] = _published(value, f"{where}/{key}")
    return out


def _name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def _refs(node: Any) -> Iterator[str]:
    if isinstance(node, dict):
        if isinstance(node.get("$ref"), str):
            yield _name(node["$ref"])
        for value in node.values():
            yield from _refs(value)
    elif isinstance(node, list):
        for value in node:
            yield from _refs(value)


def _reach(roots: Any, schemas: dict[str, Any]) -> set[str]:
    seen: set[str] = set()
    pending = list(_refs(roots))
    while pending:
        name = pending.pop()
        if name not in seen:
            seen.add(name)
            pending.extend(_refs(schemas[name]))
    return seen


def public(text: str | None, where: str) -> str | None:
    """The server's text, which a public SDK carries as it is: one naming internal planning stops the run."""
    if not text:
        return None
    found = INTERNAL.search(text)
    if found:
        raise ValueError(
            f"the description of {where} names internal planning ({found.group()!r}); fix it on the server"
        )
    return text.strip()


@dataclass
class Operation:
    name: str
    tag: str
    method: str
    path: str
    body: str | None
    response: str | None
    optional: bool
    """A success answer may come without a body (`response | None`)."""
    path_params: list[str]
    query: list[tuple[str, dict[str, Any], bool]]
    idempotent: bool
    description: str | None


def operations(document: dict[str, Any]) -> list[Operation]:
    found = []
    for path, methods in document["paths"].items():
        for method, op in methods.items():
            suffix = re.sub(r"\W", "_", path) + "_" + method
            if not op["operationId"].endswith(suffix):
                raise ValueError(f"{op['operationId']}: not named the way FastAPI names operations")
            params = op.get("parameters", [])
            body = op.get("requestBody", {}).get("content", {}).get("application/json", {}).get("schema")
            answers = [op["responses"][s] for s in SUCCESS if s in op["responses"]]
            schemas = [a.get("content", {}).get("application/json", {}).get("schema") for a in answers]
            schema = next((x for x in schemas if x), None)
            if len({json.dumps(x, sort_keys=True) for x in schemas if x}) > 1:
                raise ValueError(f"{op['operationId']}: success answers of different shapes")
            found.append(
                Operation(
                    name=op["operationId"].removesuffix(suffix),
                    tag=next(t for t in op["tags"] if t in TAGS),
                    method=method.upper(),
                    path=path,
                    body=_name(body["$ref"]) if body else None,
                    response=_name(schema["$ref"]) if schema else None,
                    optional=schema is not None and None in schemas,
                    path_params=[p["name"] for p in params if p["in"] == "path"],
                    query=[
                        (p["name"], p["schema"], p.get("required", False))
                        for p in params
                        if p["in"] == "query"
                    ],
                    idempotent=any(p["in"] == "header" and p["name"] == "Idempotency-Key" for p in params),
                    description=public(op.get("description"), op["operationId"]),
                )
            )
    return sorted(found, key=lambda o: (list(TAGS).index(o.tag), o.path, o.method))


def generate(document: dict[str, Any]) -> dict[str, str]:
    """Every generated file, by its path in the repository."""
    schemas: dict[str, Any] = document["components"]["schemas"]
    # Two server models named alike are published under their module path; a public SDK never carries one.
    unnamed = sorted(name for name in schemas if "__" in name)
    if unnamed:
        raise ValueError(f"schemas named by the server's module path: {unnamed}")
    ops = operations(document)
    sent = _reach([{"$ref": o.body} for o in ops if o.body], schemas)
    module_of: dict[str, str] = {}
    for tag, module in TAGS.items():
        roots = [{"$ref": n} for o in ops if o.tag == tag for n in (o.body, o.response) if n]
        for name in sorted(_reach(roots, schemas)):
            module_of.setdefault(name, EXISTING.get(name, f"niadra.models.{module}"))
    files = {}
    for module in dict.fromkeys(TAGS.values()):
        qualified = f"niadra.models.{module}"
        names = [n for n in _ordered(schemas) if module_of.get(n) == qualified]
        writer = ModelWriter(schemas, module_of, sent, qualified)
        files[f"src/niadra/models/{module}.py"] = writer.module(module, names)
    files["src/niadra/api.py"] = ApiWriter(module_of).module(ops)
    return {path: ruff(path, text) for path, text in files.items()}


def _ordered(schemas: dict[str, Any]) -> list[str]:
    """Every schema after the ones it refers to, so no class names one defined below it."""
    done: list[str] = []

    def visit(name: str, path: tuple[str, ...]) -> None:
        if name in done or name in path:
            return
        for ref in sorted(set(_refs(schemas[name]))):
            visit(ref, (*path, name))
        done.append(name)

    for name in sorted(schemas):
        visit(name, ())
    return done


def ruff(path: str, text: str) -> str:
    """The source as the repository's checks want it: imports sorted, then formatted."""
    for command in (["check", "--select", "I", "--fix-only"], ["format"]):
        result = subprocess.run(  # noqa: S603 - a fixed command line on the generated text
            [sys.executable, "-m", "ruff", *command, "--stdin-filename", path, "-"],
            input=text,
            capture_output=True,
            text=True,
            cwd=ROOT,
            check=False,
        )
        if result.returncode != 0:
            raise RuntimeError(f"ruff could not take the generated {path}:\n{result.stderr}")
        text = result.stdout
    return text


def _literal(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False) if isinstance(value, str) else repr(value)


def _pattern(pattern: str) -> str:
    if '"' in pattern or pattern.endswith("\\"):
        raise ValueError(f"no raw literal for the pattern {pattern}")
    return f'r"{pattern}"'


def _string(text: str) -> str:
    """A string literal in implicitly joined parts, so no generated line runs past the limit."""
    flat = " ".join(text.split())
    parts = textwrap.wrap(flat, 90, drop_whitespace=False)
    return _literal(flat) if len(parts) <= 1 else "(" + " ".join(_literal(p) for p in parts) + ")"


def _docstring(text: str, indent: str) -> str:
    if '"""' in text or "\\" in text:
        raise ValueError(f"no docstring for {text[:60]}")
    width = WIDTH - len(indent) - 3
    paragraphs = [textwrap.wrap(" ".join(p.split()), width) for p in text.split("\n\n") if p.strip()]
    lines = [line for i, p in enumerate(paragraphs) for line in ([""] if i else []) + p]
    if len(lines) == 1 and len(indent) + len(lines[0]) + 6 <= WIDTH:
        return f'{indent}"""{lines[0]}"""\n'
    if len(lines) == 1:  # the closing quotes would cross the line: two lines
        lines = textwrap.wrap(lines[0], width - 3)
    body = "\n".join(f"{indent}{line}" if line else "" for line in lines[1:])
    return f'{indent}"""{lines[0]}\n{body}\n{indent}"""\n'


def _unwrap(schema: dict[str, Any]) -> tuple[dict[str, Any], bool]:
    """`X | None` as (X, True), anything else as (itself, False)."""
    options = schema.get("anyOf")
    if options and len(options) == 2 and {"type": "null"} in options:
        (inner,) = [o for o in options if o != {"type": "null"}]
        return inner, True
    return schema, False


def _kwargs(values: dict[str, str]) -> str:
    return ", ".join(f"{k}={v}" for k, v in values.items())


@dataclass
class Imports:
    modules: dict[str, set[str]] = field(default_factory=dict)

    def add(self, module: str, name: str) -> str:
        self.modules.setdefault(module, set()).add(name)
        return name

    def render(self) -> str:
        # Ruff sorts them into place afterwards.
        return "".join(f"from {m} import {', '.join(sorted(n))}\n" for m, n in sorted(self.modules.items()))


class ModelWriter:
    """Pydantic models in the SDK's style: `Model` for what it sends, `ResponseModel` for what it only
    receives, with the server's constraints, so a request the server would refuse fails before it leaves."""

    def __init__(self, schemas: dict[str, Any], module_of: dict[str, str], sent: set[str], here: str) -> None:
        self.schemas = schemas
        self.module_of = module_of
        self.sent = sent
        self.here = here
        self.imports = Imports()
        self.aliases: dict[str, str] = {}

    def module(self, module: str, names: list[str]) -> str:
        doc = MODULE_DOCS[module]
        classes = "\n\n".join(self.definition(name) for name in names)
        aliases = "".join(f"{name} = {self.aliases[name]}\n" for name in sorted(self.aliases))
        return (
            f"{HEADER}{_docstring(doc, '')}\nfrom __future__ import annotations\n\n"
            f"{self.imports.render()}\n{aliases}\n\n{classes}"
        )

    def definition(self, name: str) -> str:
        schema = self.schemas[name]
        doc = public(schema.get("description"), name)
        if schema.get("type") != "object":
            return f"{name} = {self.type(schema)}\n" + (_docstring(doc, "") if doc else "")
        base = self.imports.add("niadra.models._base", "Model" if name in self.sent else "ResponseModel")
        out = f"class {name}({base}):\n" + (_docstring(doc, "    ") + "\n" if doc else "")
        if schema.get("additionalProperties") is True:
            config = self.imports.add("pydantic", "ConfigDict")
            out += f'    model_config = {config}(extra="allow", frozen=True, populate_by_name=True)\n\n'
        required = set(schema.get("required", ()))
        lines = [
            self.field(name, wire, prop, wire in required)
            for wire, prop in schema.get("properties", {}).items()
        ]
        # A field hides a type of the same name from every annotation of its class.
        attrs = {line.split(":", 1)[0] for line in lines}
        for line in lines:
            annotation = re.sub(r'"(?:[^"\\]|\\.)*"', "", line.split(":", 1)[1].split(" = ", 1)[0])
            hidden = attrs & set(re.findall(r"\w+", annotation))
            if hidden:
                raise ValueError(f"{name}: the field {sorted(hidden)[0]} hides a type its class uses")
        return out + "".join(f"    {line}\n" for line in lines)

    def field(self, owner: str, wire: str, prop: dict[str, Any], required: bool) -> str:
        attr = FIELD_NAMES.get(wire, wire + "_" if keyword.iskeyword(wire) else wire)
        if not attr.isidentifier():
            raise ValueError(f"{owner}.{wire}: not a field name the models can use")
        inner, nullable = _unwrap(prop)
        kwargs: dict[str, str] = {}
        if nullable:
            annotation = self.type(inner) + " | None"
        else:
            annotation = self.type(inner, constraints=False)
            kwargs.update(self.constraints(inner))
        if attr != wire:
            kwargs["alias"] = _literal(wire)
        description = public(prop.get("description"), f"{owner}.{wire}")
        if description:
            kwargs["description"] = _string(description)
        if not required:
            key, value = self.default(f"{owner}.{wire}", prop, inner, nullable)
            if not kwargs and key == "default":
                return f"{attr}: {annotation} = {value}"
            kwargs = {key: value, **kwargs}
        if not kwargs:
            return f"{attr}: {annotation}"
        return f"{attr}: {annotation} = {self.imports.add('pydantic', 'Field')}({_kwargs(kwargs)})"

    def default(
        self, where: str, prop: dict[str, Any], inner: dict[str, Any], nullable: bool
    ) -> tuple[str, str]:
        if "default" in prop and prop["default"] not in ([], {}):
            if isinstance(prop["default"], dict):
                return self._factory(where, inner, prop["default"])
            ref = _name(inner.get("$ref", ""))
            if EXISTING.get(ref) == "niadra.vocabulary":
                # A member of an enumeration the SDK writes by hand, not its bare value.
                return ("default", f"{self.ref(ref)}({_literal(prop['default'])})")
            return ("default", _literal(prop["default"]))
        # Pydantic writes no default for a `default_factory`: an empty container, or a model's defaults.
        if nullable and "default" not in prop:
            return ("default", "None")
        if inner.get("type") == "array":
            return ("default_factory", "list")
        if inner.get("type") == "object":
            return ("default_factory", "dict")
        if "$ref" in inner:
            return self._factory(where, inner, {})
        return ("default", "None")

    def _factory(self, where: str, inner: dict[str, Any], value: dict[str, Any]) -> tuple[str, str]:
        ref = _name(inner.get("$ref", ""))
        target = self.schemas.get(ref, {})
        props = target.get("properties", {})
        if target.get("required") or any(
            props.get(k, {}).get("default", object()) != v for k, v in value.items()
        ):
            raise ValueError(f"{where}: the default is not the model {ref or '?'} with its own defaults")
        return ("default_factory", self.ref(ref))

    def ref(self, name: str) -> str:
        module = self.module_of[name]
        if module != self.here:
            self.imports.add(module, name)
        return name

    def constraints(self, schema: dict[str, Any]) -> dict[str, str]:
        found = {}
        for key, arg in (
            ("minimum", "ge"),
            ("maximum", "le"),
            ("exclusiveMinimum", "gt"),
            ("exclusiveMaximum", "lt"),
        ):
            if key in schema:
                value = schema[key]
                found[arg] = repr(int(value)) if schema.get("type") == "integer" else repr(float(value))
        if "prefixItems" not in schema:
            for key, arg in (
                ("minItems", "min_length"),
                ("maxItems", "max_length"),
                ("maxProperties", "max_length"),
            ):
                if key in schema:
                    found[arg] = repr(schema[key])
        return found

    def type(self, schema: dict[str, Any], *, constraints: bool = True) -> str:
        """The annotation of `schema`, its numeric and size constraints included unless the field's own
        `Field(...)` carries them (`constraints=False`)."""
        base = self._base(schema)
        found = self.constraints(schema) if constraints else {}
        if not found:
            return base
        annotated = self.imports.add("typing", "Annotated")
        return f"{annotated}[{base}, {self.imports.add('pydantic', 'Field')}({_kwargs(found)})]"

    def _base(self, schema: dict[str, Any]) -> str:
        if "$ref" in schema:
            return self.ref(_name(schema["$ref"]))
        if "anyOf" in schema:
            inner, nullable = _unwrap(schema)
            if nullable:
                return self.type(inner) + " | None"
            return " | ".join(self.type(s) for s in schema["anyOf"])
        if "oneOf" in schema and "propertyName" in schema.get("discriminator", {}):
            union = " | ".join(self.type(s) for s in schema["oneOf"])
            on = _literal(schema["discriminator"]["propertyName"])
            annotated = self.imports.add("typing", "Annotated")
            return f"{annotated}[{union}, {self.imports.add('pydantic', 'Field')}(discriminator={on})]"
        if "const" in schema:
            return f"{self.imports.add('typing', 'Literal')}[{_literal(schema['const'])}]"
        if "enum" in schema:
            return (
                f"{self.imports.add('typing', 'Literal')}[{', '.join(_literal(v) for v in schema['enum'])}]"
            )
        kind = schema.get("type")
        if kind == "string":
            return self._string_type(schema)
        if kind in ("integer", "number", "boolean", "null"):
            return {"integer": "int", "number": "float", "boolean": "bool", "null": "None"}[kind]
        if kind == "array":
            if "prefixItems" in schema:
                return f"tuple[{', '.join(self.type(s) for s in schema['prefixItems'])}]"
            return f"list[{self.type(schema.get('items', {}))}]"
        if kind == "object" and not schema.get("properties"):
            return self._mapping(schema)
        if not {k for k in schema if k not in ("title", "description")}:
            return self.imports.add("typing", "Any")
        raise ValueError(f"no Python type for {json.dumps(schema)[:200]}")

    def _mapping(self, schema: dict[str, Any]) -> str:
        key = "str"
        value: Any = schema.get("additionalProperties", True)
        if "patternProperties" in schema:
            ((pattern, value),) = schema["patternProperties"].items()
            key = self._string_type({"type": "string", "pattern": pattern})
        elif isinstance(schema.get("propertyNames"), dict):
            key = self._string_type({"type": "string", **schema["propertyNames"]})
        rendered = self.imports.add("typing", "Any") if value in (True, {}) else self.type(value)
        return f"dict[{key}, {rendered}]"

    def _string_type(self, schema: dict[str, Any]) -> str:
        fmt = schema.get("format")
        if fmt in ("date-time", "date"):
            return self.imports.add("datetime", "datetime" if fmt == "date-time" else "date")
        if fmt == "uuid":
            return self.imports.add("uuid", "UUID")
        name, *modules = STRING_ALIASES.get(
            (schema.get("minLength"), schema.get("maxLength"), schema.get("pattern")), "-"
        ).split()
        if name == "-" or (modules and self.here.rsplit(".", 1)[-1] not in modules):
            return self._constrained(schema)
        if name in SHARED_ALIASES:
            return self.imports.add("niadra.models._base", name)
        self.aliases[name] = self._constrained(schema)
        return name

    def _constrained(self, schema: dict[str, Any]) -> str:
        found = {}
        for key, arg in (("minLength", "min_length"), ("maxLength", "max_length"), ("pattern", "pattern")):
            if key in schema:
                found[arg] = _pattern(schema[key]) if key == "pattern" else repr(schema[key])
        if not found:
            return "str"
        annotated = self.imports.add("typing", "Annotated")
        return f"{annotated}[str, {self.imports.add('pydantic', 'StringConstraints')}({_kwargs(found)})]"


def _param_type(schema: dict[str, Any]) -> str:
    """A query parameter's type in a method's signature; the server checks its bounds."""
    if schema.get("format") == "date":
        return "date"
    types = {"string": "str", "integer": "int", "number": "float", "boolean": "bool"}
    if schema.get("type") not in types:
        raise ValueError(f"no parameter type for {schema}")
    return types[schema["type"]]


def _sender(op: Operation) -> str:
    if op.response is None:
        return "_send"
    return "_call_optional" if op.optional else "_call"


class ApiWriter:
    """`Api` and `AsyncApi`: one method per operation, named as the server names the operation."""

    def __init__(self, module_of: dict[str, str]) -> None:
        self.module_of = module_of
        self.imports = Imports()

    def module(self, ops: list[Operation]) -> str:
        self.imports.add("niadra._routes", "AsyncRoutes")
        self.imports.add("niadra._routes", "SyncRoutes")
        sync = "\n".join(self.method(op, is_async=False) for op in ops)
        asynchronous = "\n".join(self.method(op, is_async=True) for op in ops)
        return (
            f"{HEADER}{_docstring(API_DOC, '')}\nfrom __future__ import annotations\n\n"
            f"{self.imports.render()}\n\n"
            f'class Api(SyncRoutes):\n    """The routes of `niadra.api`. See the module."""\n\n{sync}\n\n'
            f'class AsyncApi(AsyncRoutes):\n    """The routes of `AsyncNiadra.api`. See the module."""\n\n'
            f"{asynchronous}"
        )

    def ref(self, name: str) -> str:
        return self.imports.add(self.module_of[name], name)

    def method(self, op: Operation, *, is_async: bool) -> str:
        args = ["self"]
        path = op.path
        for name in op.path_params:
            args.append(f"{name}: str")
            path = path.replace(
                "{" + name + "}", "{" + self.imports.add("niadra._routes", "segment") + f"({name})}}"
            )
        if op.body:
            args.append(f"body: {self.ref(op.body)}")
        keywords = []
        for name, schema, required in op.query:
            inner, _ = _unwrap(schema)
            annotation = _param_type(inner)
            if annotation == "date":
                self.imports.add("datetime", "date")
            if required:
                keywords.append(f"{name}: {annotation}")
            elif schema.get("default") is not None:
                keywords.append(f"{name}: {annotation} = {_literal(schema['default'])}")
            else:
                keywords.append(f"{name}: {annotation} | None = None")
        if op.idempotent:
            keywords.append("idempotency_key: str | None = None")
        if keywords:
            args += ["*", *keywords]
        call = [self.ref(op.response)] if op.response else []
        call += [_literal(op.method), f'f"{path}"' if "{" in path else _literal(path)]
        if op.body:
            call.append("body=body")
        if op.query:
            call.append("params={" + ", ".join(f"{_literal(n)}: {n}" for n, _, _ in op.query) + "}")
        if op.idempotent:
            call.append(f"key=idempotency_key or {self.imports.add('niadra._ids', 'new_key')}()")
        doc = f"`{op.method} {op.path}`." + (f" {op.description}" if op.description else "")
        returns = f"{op.response} | None" if op.optional else op.response or "None"
        return (
            f"    {'async def' if is_async else 'def'} {op.name}({', '.join(args)}) -> {returns}:\n"
            + _docstring(doc, "        ")
            + f"        return {'await ' if is_async else ''}self.{_sender(op)}"
            + f"({', '.join(call)})\n"
        )


if __name__ == "__main__":
    main()
