# Generated by scripts/sync_spec.py from spec/openapi/cell.json. Do not edit.
"""Ownership and effects: the coordination decision, declarations, claims and locks, effects exactly once,
handoffs, suppressions and the contact token's public keys.
"""

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Any, Literal
from uuid import UUID

from pydantic import Field, StringConstraints

from niadra.models._base import IdStr, Model, ResponseModel, ShortStr
from niadra.models.common import Handle, ObjectRef
from niadra.vocabulary import Verification

TypeName = Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9_]{0,39}$")]


class ReleaseDetail(Model):
    """The claim a case closes, with the epoch it got when it was accepted."""

    claim_id: UUID
    epoch: int = Field(ge=0)


class CaseClosed(Model):
    agent: ShortStr
    detail: ReleaseDetail
    kind: Literal["case.closed"]
    object: ObjectRef | None = None
    subject: Handle | None = None


class LeaseDetail(Model):
    """An owner lease or a case, held by the declaring agent. `level` defaults to the space's least
    restrictive level.
    """

    intents: list[TypeName] = Field(default_factory=list, max_length=20)
    lease_s: int = Field(ge=1, le=86400)
    level: TypeName | None = None


class CaseOpened(Model):
    agent: ShortStr
    detail: LeaseDetail
    kind: Literal["case.opened"]
    object: ObjectRef | None = None
    subject: Handle | None = None


class ChannelState(ResponseModel):
    free_form_until: datetime | None = None
    quiet_until: datetime | None = None
    template_required: bool = False


EffectKind = Literal["delivery", "document", "notice", "filing", "paid_call", "external_action"]


class CheckRequest(Model):
    """What an agent is about to do. Without a subject there is no budget, suppression or owner to consult:
    such a check only asks about the effect key.
    """

    agent: ShortStr
    channel: TypeName | None = None
    destination_hash: Annotated[str, StringConstraints(pattern=r"^[A-Za-z0-9_-]{43}$")] | None = Field(
        default=None,
        description=(
            "The token's `rcpt`, computed by a caller that holds the gateway's key, when the "
            "destination is not the subject's handle."
        ),
    )
    direction: Literal["inbound", "outbound"]
    effect_key: IdStr | None = Field(
        default=None, description="The business fact's key; reserved atomically when nothing holds it."
    )
    effect_kind: EffectKind = "delivery"
    gateway_id: TypeName | None = None
    intent: TypeName
    object: ObjectRef | None = None
    purpose: TypeName
    subject: Handle | None = None
    task: TypeName | None = None


class CheckBatchRequest(Model):
    checks: list[CheckRequest] = Field(min_length=1, max_length=500)


class CommitmentRef(ResponseModel):
    id: IdStr
    type: TypeName
    valid_until: datetime | None = None


class ContactBudget(ResponseModel):
    next_allowed_at: datetime | None = None
    remaining: int


class EffectStatus(ResponseModel):
    """`none` means nothing held the key and this check reserved it: the caller acts and then declares."""

    attempt: int | None = None
    state: Literal["none", "in_flight", "done", "unknown_outcome"]


class Lock(ResponseModel):
    holder: ShortStr
    kind: ShortStr
    task: ShortStr | None = None
    until: datetime


ClaimKind = Literal["owner", "case", "task_lock"]


ClaimVia = Literal["declaration", "mapping", "worker"]
"""The three ways in: a declaration through the API, an observation mapped from a webhook, an observation the
company's worker read and sent.
"""


class Owner(ResponseModel):
    """Who holds the subject or the object now: the most restrictive valid claim, where it came from and until
    when. `epoch` fences a release.
    """

    epoch: int
    holder: ShortStr
    kind: ClaimKind
    level: TypeName
    since: datetime
    source: ShortStr
    valid_until: datetime
    via: ClaimVia


class PromiseRef(ResponseModel):
    due: datetime | None = None
    id: IdStr
    owner: ShortStr


class CheckResult(ResponseModel):
    """The coordination decision. `reasons` are codes (the coordination spec, 4); `holder` is who to hand off
    to with `handoff_to`. `contact_token` comes only with an allowed outbound contact of a purpose that
    needs one.
    """

    channel: ChannelState | None = None
    commitments_active: list[CommitmentRef] = Field(default_factory=list)
    contact_budget: dict[str, ContactBudget] = Field(default_factory=dict)
    contact_token: (
        Annotated[
            str, StringConstraints(max_length=1024, pattern=r"^nct1\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]{86}$")
        ]
        | None
    ) = None
    decision: Literal["allow", "defer", "deny", "handoff_to"]
    decision_id: UUID
    effect: EffectStatus | None = None
    holder: ShortStr | None = None
    locks: list[Lock] = Field(default_factory=list)
    owner: Owner | None = None
    promises_open: list[PromiseRef] = Field(default_factory=list)
    reasons: list[ShortStr] = Field(default_factory=list)
    suppressions: list[TypeName] = Field(default_factory=list)
    valid_for_s: int = Field(ge=0)


class CheckBatchResponse(ResponseModel):
    results: list[CheckResult]


class ClaimRelease(Model):
    epoch: int


class ClaimRequest(Model):
    """A declared claim, held by `holder`. `level` defaults to the space's least restrictive level; a
    declaration is refused (409 `lease_held`) while another holder's claim is at least as restrictive, and
    the same holder renews its own. `lease_s` is capped by the space's longest declared lease. A task lock
    names an object and its `task`, and is refused (409 `task_locked`) while another holder has that task.
    """

    holder: ShortStr
    intents: list[TypeName] = Field(default_factory=list, max_length=20)
    kind: ClaimKind
    lease_s: int = Field(ge=1, le=86400)
    level: TypeName | None = None
    object: ObjectRef | None = None
    observed_at: datetime | None = Field(
        default=None,
        description="When the source saw it; an observation older than the source's last is ignored.",
    )
    source: TypeName | None = Field(
        default=None,
        description=(
            "An observation of this ownership source, read and sent by the company's worker: never "
            "refused, replacing what the source said before, and capped by the source's validity."
        ),
    )
    subject: Handle | None = None
    task: TypeName | None = None


class CommitmentDecidedDetail(Model):
    """The person accepted or declined a commitment, maybe in a later conversation."""

    commitment_id: IdStr
    outcome: Literal["accepted", "declined"]


class CommitmentDecided(Model):
    agent: ShortStr
    detail: CommitmentDecidedDetail
    kind: Literal["commitment.decided"]
    object: ObjectRef | None = None
    subject: Handle | None = None


class CommitmentMadeDetail(Model):
    """`score` ranks commitments of a `best_wins` type: the higher holds."""

    commitment_id: IdStr
    score: float | None = None
    terms: dict[str, Any] = Field(default_factory=dict)
    type: TypeName
    valid_until: datetime | None = None


class CommitmentMade(Model):
    agent: ShortStr
    detail: CommitmentMadeDetail
    kind: Literal["commitment.made"]
    object: ObjectRef | None = None
    subject: Handle | None = None


class CommitmentWithdrawnDetail(Model):
    commitment_id: IdStr


class CommitmentWithdrawn(Model):
    agent: ShortStr
    detail: CommitmentWithdrawnDetail
    kind: Literal["commitment.withdrawn"]
    object: ObjectRef | None = None
    subject: Handle | None = None


class ContactKey(ResponseModel):
    """An Ed25519 public key as a JWK (RFC 8037). A `retiring` key still verifies and signs nothing new."""

    crv: Literal["Ed25519"] = "Ed25519"
    kid: Annotated[str, StringConstraints(pattern=r"^[A-Za-z0-9_-]{8,64}$")]
    kty: Literal["OKP"] = "OKP"
    not_after: datetime | None = None
    space: UUID
    status: Literal["active", "retiring"] = "active"
    x: Annotated[str, StringConstraints(pattern=r"^[A-Za-z0-9_-]{43}$")]


class ContactKeys(ResponseModel):
    """A space's public keys a gateway checks a contact token with, offline."""

    keys: list[ContactKey]


class ContactMadeDetail(Model):
    """`jti` is the contact token's; `unchecked` says the contact left without a decision, because the purpose
    fails open and none came in time.
    """

    channel: TypeName
    decision_id: UUID | None = None
    gateway_id: TypeName | None = None
    jti: UUID | None = None
    purpose: TypeName
    unchecked: bool = False


class ContactMade(Model):
    agent: ShortStr
    detail: ContactMadeDetail
    kind: Literal["contact.made"]
    object: ObjectRef | None = None
    subject: Handle | None = None


class CoordinationReport(ResponseModel):
    """A shadow run: the space's policy applied to its outbound messages already ingested, with nothing
    enforced. `summary` holds the conflicts found and per 1,000 customers a month, without anyone in them.
    """

    days: int
    finished_at: datetime | None = None
    report_id: IdStr
    requested_at: datetime
    status: Literal["pending", "done", "failed"]
    summary: dict[str, Any] = Field(default_factory=dict)


class CoordinationReportPage(ResponseModel):
    items: list[CoordinationReport]
    next_cursor: str | None = None


class EffectDetail(Model):
    """How the attempt the caller holds ended."""

    attempt: int = Field(ge=1)
    effect_key: IdStr
    state: Literal["done", "failed", "unknown_outcome"]


class EffectDeclared(Model):
    agent: ShortStr
    detail: EffectDetail
    kind: Literal["effect"]
    object: ObjectRef | None = None
    subject: Handle | None = None


class HandoffDetail(Model):
    handoff_id: IdStr
    outcome: TypeName | None = None
    status: Literal["created", "accepted", "closed"]


class HandoffDeclared(Model):
    agent: ShortStr
    detail: HandoffDetail
    kind: Literal["handoff"]
    object: ObjectRef | None = None
    subject: Handle | None = None


class LeaseDeclared(Model):
    agent: ShortStr
    detail: LeaseDetail
    kind: Literal["lease"]
    object: ObjectRef | None = None
    subject: Handle | None = None


class SuppressionAddedDetail(Model):
    """The subject may not be contacted for `purpose`, on `channel` or on every channel. `until` defaults to
    the reason's own interval, or to no end.
    """

    channel: TypeName | None = None
    purpose: TypeName
    reason: TypeName
    until: datetime | None = None


class SuppressionAdded(Model):
    agent: ShortStr
    detail: SuppressionAddedDetail
    kind: Literal["suppression.added"]
    object: ObjectRef | None = None
    subject: Handle | None = None


class SuppressionLiftedDetail(Model):
    """Lifts what the same source suppressed for `purpose` and `channel`."""

    channel: TypeName | None = None
    purpose: TypeName


class SuppressionLifted(Model):
    agent: ShortStr
    detail: SuppressionLiftedDetail
    kind: Literal["suppression.lifted"]
    object: ObjectRef | None = None
    subject: Handle | None = None


class TaskLockDetail(Model):
    lease_s: int = Field(ge=1, le=86400)
    task: TypeName


class TaskLockDeclared(Model):
    agent: ShortStr
    detail: TaskLockDetail
    kind: Literal["task_lock"]
    object: ObjectRef | None = None
    subject: Handle | None = None


DeclareRequest = Annotated[
    CaseOpened
    | CaseClosed
    | LeaseDeclared
    | TaskLockDeclared
    | ContactMade
    | EffectDeclared
    | CommitmentMade
    | CommitmentWithdrawn
    | CommitmentDecided
    | HandoffDeclared
    | SuppressionAdded
    | SuppressionLifted,
    Field(discriminator="kind"),
]
"""What happened, after the fact: one kind of declaration, with the fields of its kind in `detail` (the
coordination spec, 5).
"""


class DeclareResult(ResponseModel):
    accepted: bool
    decision_id: UUID | None = None


class Effect(ResponseModel):
    """`effect_id` is the key's keyed hash: it names the effect in paths, where the key itself, which may
    carry a conversation id, never goes.
    """

    attempt: int
    done_at: datetime | None = None
    effect_id: Annotated[str, StringConstraints(pattern=r"^[A-Za-z0-9_-]{43}$")]
    reserved_at: datetime
    state: Literal["reserved", "done", "failed", "unknown_outcome"]


class EffectReserve(Model):
    cost_units: int = Field(default=0, ge=0)
    effect_key: IdStr
    fact: ObjectRef | None = None
    kind: EffectKind


class EffectSeen(ResponseModel):
    effect_id: Annotated[str, StringConstraints(pattern=r"^[A-Za-z0-9_-]{43}$")]
    kind: EffectKind
    state: Literal["reserved", "done", "failed", "unknown_outcome"]


class EffectSettle(Model):
    attempt: int = Field(ge=1)
    state: Literal["done", "failed", "unknown_outcome"]


class HandoffContext(ResponseModel):
    """The compiled `handoff` view, at the receiving side's policy and verification level. `etag` is the
    pack's it was compiled from, absent for a subject the memory knows nothing of yet.
    """

    etag: ShortStr | None = None
    policy_version: ShortStr | None = None
    text: str


class OpenObject(ResponseModel):
    ref: ObjectRef
    since: datetime | None = None
    state: ShortStr | None = None


class OutcomeRequest(ResponseModel):
    """How the receiving side reports back: one of `vocabulary`, by `expected_by`."""

    expected_by: datetime | None = None
    vocabulary: list[TypeName] = Field(default_factory=list, max_length=50)


class HandoffPackage(ResponseModel):
    """What a handoff carries to whoever receives it (the coordination spec, 7)."""

    commitments_active: list[CommitmentRef] = Field(default_factory=list)
    context: HandoffContext
    created_at: datetime
    effects: list[EffectSeen] = Field(default_factory=list)
    from_agent: ShortStr
    handoff_id: IdStr
    level: Verification
    open_objects: list[OpenObject] = Field(default_factory=list, max_length=50)
    outcome: OutcomeRequest = Field(default_factory=OutcomeRequest)
    owner: Owner | None = None
    promises_open: list[PromiseRef] = Field(default_factory=list)
    reason: Annotated[str, StringConstraints(min_length=1, max_length=500)] | None = None
    spec: Literal["handoff-package.v0"] = "handoff-package.v0"
    subject: Handle | None = Field(default=None, description="Whom the handoff is about.")
    suppressions: list[TypeName] = Field(default_factory=list)
    target: ShortStr


class Handoff(ResponseModel):
    created_at: datetime
    expected_by: datetime | None = None
    handoff_id: IdStr
    outcome: ShortStr | None = None
    package: HandoffPackage | None = None
    status: Literal["created", "accepted", "closed", "expired"]


class HandoffCreate(Model):
    """Hands the subject to `target`. The package is compiled at `level`, the verification the receiving side
    has of the subject, so it never carries what that side could not read.
    """

    agent: ShortStr | None = Field(
        default=None, description="The agent handing off; the calling key's name when absent."
    )
    conversation_id: IdStr | None = None
    expected_by: datetime | None = Field(
        default=None, description="When the outcome is due; the space's default wait when absent."
    )
    level: Verification = Verification("V0")
    reason: Annotated[str, StringConstraints(min_length=1, max_length=500)] | None = None
    subject: Handle
    target: ShortStr


class HandoffOutcome(Model):
    detail: dict[str, Any] = Field(default_factory=dict)
    outcome: TypeName


class OwnershipClaim(ResponseModel):
    claim_id: IdStr
    epoch: int
    holder: str
    kind: ClaimKind
    level: TypeName
    valid_until: datetime


class ShadowRequest(Model):
    days: int = Field(default=30, ge=1, le=90)


class ShadowRun(ResponseModel):
    report_id: IdStr
    status: Literal["pending", "done"]


class Suppression(ResponseModel):
    """One entry of the suppression list: `key` is the subject's handle keyed with the reading source's salt
    (the suppression-list spec); `removed` takes the entry `id` out of the reader's copy. The reason stays
    with the producer: a vendor learns that it may not contact, never why.
    """

    channel: TypeName | None = None
    id: IdStr
    key: Annotated[str, StringConstraints(pattern=r"^[A-Za-z0-9_-]{43}$")]
    purpose: TypeName
    removed: bool = False
    since: datetime
    until: datetime | None = None


class SuppressionPage(ResponseModel):
    """A page of changes, oldest first. With `reset`, the reader drops its copy before applying `items`: the
    salt changed, or the cursor is older than what the list keeps.
    """

    items: list[Suppression]
    next_cursor: str | None = None
    reset: bool = False
    salt_id: IdStr


class SuppressionSalt(ResponseModel):
    salt: Annotated[str, StringConstraints(pattern=r"^[A-Za-z0-9_-]{43}$")]
    salt_id: IdStr
    valid_from: datetime
