# Generated by scripts/sync_spec.py from spec/openapi/cell.json. Do not edit.
"""Ownership and effects: the coordination decision, declarations, claims and locks, effects exactly once,
handoffs, suppressions and the contact token's public keys.

Draft: the server has not fixed these models yet, and their fields may still change.
"""

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Any, Literal
from uuid import UUID

from pydantic import Field, StringConstraints

from niadra.models._base import IdStr, Model, ResponseModel, ShortStr
from niadra.models.common import Handle, ObjectRef


class ChannelState(ResponseModel):
    free_form_until: datetime | None = None
    quiet_until: datetime | None = None
    template_required: bool = False


class CheckRequest(Model):
    agent: ShortStr
    channel: ShortStr | None = None
    destination_hash: ShortStr | None = None
    direction: Literal["inbound", "outbound"]
    effect_key: IdStr | None = None
    gateway_id: ShortStr | None = None
    intent: ShortStr
    object: ObjectRef | None = None
    purpose: ShortStr
    subject: Handle | None = None
    task: ShortStr | None = None


class CheckBatchRequest(Model):
    checks: list[CheckRequest] = Field(min_length=1, max_length=500)


class ContactBudget(ResponseModel):
    next_allowed_at: datetime | None = None
    remaining: int


class EffectStatus(ResponseModel):
    state: Literal["none", "in_flight", "done", "unknown_outcome"]


class Lock(ResponseModel):
    holder: ShortStr
    kind: ShortStr
    task: ShortStr | None = None
    until: datetime


class Owner(ResponseModel):
    epoch: int
    holder: ShortStr
    kind: ShortStr
    since: datetime
    source: ShortStr
    valid_until: datetime | None = None


class CheckResult(ResponseModel):
    channel: ChannelState | None = None
    commitments_active: list[dict[str, Any]] = Field(default_factory=list)
    contact_budget: dict[str, ContactBudget] = Field(default_factory=dict)
    contact_token: str | None = None
    decision: Literal["allow", "defer", "deny", "handoff_to"]
    decision_id: UUID
    effect: EffectStatus | None = None
    holder: str | None = None
    locks: list[Lock] = Field(default_factory=list)
    owner: Owner | None = None
    promises_open: list[dict[str, Any]] = Field(default_factory=list)
    reasons: list[str] = Field(default_factory=list)
    suppressions: list[str] = Field(default_factory=list)
    valid_for_s: int


class CheckBatchResponse(ResponseModel):
    results: list[CheckResult]


class ClaimRelease(Model):
    epoch: int


class ClaimRequest(Model):
    holder: ShortStr
    intents: list[ShortStr] = Field(default_factory=list)
    kind: Literal["owner", "case", "task_lock"]
    lease_s: int = Field(ge=1, le=86400)
    object: ObjectRef | None = None
    subject: Handle | None = None
    task: ShortStr | None = None


class ContactKeys(ResponseModel):
    """The spaces' Ed25519 public keys a gateway checks a contact token with, offline."""

    keys: list[dict[str, str]]


class CoordinationReportPage(ResponseModel):
    items: list[dict[str, Any]]
    next_cursor: str | None = None


class DeclareRequest(Model):
    agent: ShortStr
    detail: dict[str, Any] = Field(default_factory=dict)
    kind: Literal[
        "case.opened",
        "case.closed",
        "lease",
        "task_lock",
        "contact.made",
        "effect",
        "commitment.made",
        "commitment.withdrawn",
        "handoff",
    ]
    object: ObjectRef | None = None
    subject: Handle | None = None


class DeclareResult(ResponseModel):
    accepted: bool
    decision_id: UUID | None = None


class Effect(ResponseModel):
    attempt: int
    done_at: datetime | None = None
    effect_key: IdStr
    reserved_at: datetime
    state: Literal["reserved", "done", "failed", "unknown_outcome"]


class EffectReserve(Model):
    cost_units: int = Field(default=0, ge=0)
    effect_key: IdStr
    fact: ObjectRef | None = None
    kind: Literal["delivery", "document", "notice", "filing", "paid_call", "external_action"]


class EffectSettle(Model):
    state: Literal["done", "failed", "unknown_outcome"]


class Handoff(ResponseModel):
    created_at: datetime
    handoff_id: IdStr
    outcome: ShortStr | None = None
    package: dict[str, Any] = Field(default_factory=dict)
    status: Literal["created", "accepted", "closed"]


class HandoffCreate(Model):
    conversation_id: IdStr | None = None
    reason: Annotated[str, StringConstraints(min_length=1, max_length=500)] | None = None
    subject: Handle
    target: ShortStr


class HandoffOutcome(Model):
    detail: dict[str, Any] = Field(default_factory=dict)
    outcome: ShortStr


class OwnershipClaim(ResponseModel):
    claim_id: IdStr
    epoch: int
    holder: str
    kind: Literal["owner", "case", "task_lock"]
    valid_until: datetime


class ShadowRequest(Model):
    days: int = Field(default=30, ge=1, le=90)


class ShadowRun(ResponseModel):
    report_id: IdStr
    status: Literal["pending", "done"]


class Suppression(ResponseModel):
    channel: ShortStr | None = None
    key: ShortStr
    purpose: ShortStr
    reason: ShortStr
    removed: bool = False
    since: datetime
    until: datetime | None = None


class SuppressionPage(ResponseModel):
    items: list[Suppression]
    next_cursor: str | None = None


class SuppressionSalt(ResponseModel):
    salt: str
    valid_from: datetime
