# Generated by scripts/sync_spec.py from spec/openapi/cell.json. Do not edit.
"""Subject signals, the constraints block, the reviewable profile, review requests, legal holds and
measurement.
"""

from __future__ import annotations

from datetime import date, datetime
from typing import Annotated, Any, Literal
from uuid import UUID

from pydantic import Field, StringConstraints

from niadra.models._base import IdStr, Model, ResponseModel, ShortStr
from niadra.models.common import Handle, ObjectRef

ObjectKey = Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9_]{0,39}:[^:\s]{1,256}:\S{1,512}$")]


class AttributeEntry(ResponseModel):
    apply: Literal["always", "when_asked"]
    category: ShortStr | None = None
    confidence: float = Field(ge=0.0, le=1.0)
    id: Annotated[str, StringConstraints(pattern=r"^z[0-9]{1,4}$")]
    name: Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9_]{0,63}(?:\.[a-z0-9_]{1,64}){0,3}$")]
    source: Literal["stated", "correction", "acquired", "kept", "returned_for_size", "inferred"]
    system: ShortStr | None = None
    value: bool | int | float | Annotated[str, StringConstraints(max_length=256)]


class AttributionRow(ResponseModel):
    agent: str
    band: Literal["deterministic", "probable"]
    currency: str
    day: date
    finality: Literal["provisional", "final", "expired_without_outcome"]
    lines: int
    method: Literal["line", "order", "identity", "assisted_handoff"]
    outcome: ShortStr
    outcomes: int
    value_minor: int


class AttributionTotal(ResponseModel):
    """One method, band and finality over the period: deterministic and probable are never added together."""

    band: Literal["deterministic", "probable"]
    currency: str
    finality: Literal["provisional", "final", "expired_without_outcome"]
    lines: int
    method: Literal["line", "order", "identity", "assisted_handoff"]
    outcome: ShortStr
    outcomes: int
    value_minor: int


class IdentityCalibration(ResponseModel):
    """How often the identity method names the exposure the line's own token names, on the lines where both
    exist: the confidence of that method in this space.
    """

    agreeing: int
    compared: int
    rate: float | None = None


class AttributionReport(ResponseModel):
    """Value by day, agent, method and band, deterministic and probable apart; a value is never multiplied by
    a confidence, and no total adds a probable value to a deterministic one.
    """

    identity: IdentityCalibration
    rows: list[AttributionRow]
    since: date
    totals: list[AttributionTotal]
    until: date


class BiFile(Model):
    """The company's BI export for the period, as CSV with a header: `order` (the id the company knows the
    object by), `line` (optional), `value` (in major units, as the signed definition nets it) and
    `currency`.
    """

    content: Annotated[str, StringConstraints(min_length=1, max_length=5000000)]
    format: Literal["csv"] = "csv"


class BlockSubject(ResponseModel):
    for_: Annotated[str, StringConstraints(pattern=r"^(?:self|gift|beneficiary:[A-Za-z0-9_-]{1,64})$")] = (
        Field(default="self", alias="for")
    )


class CompanyRule(ResponseModel):
    """A rule of the company delivered in the block, with where it lives and its rank in the order the company
    declared: the block never ranks two origins by itself.
    """

    attr: (
        Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9_]{0,39}\.[a-z][a-z0-9_]{0,63}$")] | None
    ) = None
    id: Annotated[str, StringConstraints(pattern=r"^r[0-9]{1,4}$")]
    op: Literal["in", "not_in", "eq", "ne", "lt", "lte", "gt", "gte", "between"] | None = None
    origin: ShortStr = Field(description="`code`, `db:<table>`, `prompt:<version>`, `policy:<version>`...")
    rank: int = Field(ge=1, le=100)
    values: list[bool | int | float | Annotated[str, StringConstraints(max_length=256)]] = Field(
        default_factory=list, max_length=50
    )


class Conflict(ResponseModel):
    """Two entries that cannot both hold, and the one that won: the current utterance over what was stated
    before, and a stated entry over an inferred one. Between two company rules, it is also a data issue.
    """

    by: Literal["current_utterance", "precedence", "rule_rank"]
    ids: list[str] = Field(min_length=2, max_length=10)
    kept: str


class ConstraintOrigin(ResponseModel):
    event_key: IdStr | None = None
    kind: Literal["stated", "tool_args", "correction"]
    turn_id: IdStr | None = None


class HardConstraint(ResponseModel):
    """Only what the person said: an inference is never hard."""

    attr: Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9_]{0,39}\.[a-z][a-z0-9_]{0,63}$")]
    category: ShortStr | None = None
    expires_at: datetime | None = None
    id: Annotated[str, StringConstraints(pattern=r"^h[0-9]{1,4}$")]
    op: Literal["in", "not_in", "eq", "ne", "lt", "lte", "gt", "gte", "between"]
    origin: ConstraintOrigin
    relax: Literal["never", "ask"] = "never"
    scope: Literal["turn", "session", "persistent"]
    source: Literal["stated", "tool_args", "correction"]
    values: list[bool | int | float | Annotated[str, StringConstraints(max_length=256)]] = Field(
        min_length=1, max_length=50
    )


class Rendered(ResponseModel):
    """The block for one tool, through its bindings (`constraints.v0`, rendering)."""

    args: dict[str, Any] = Field(description="Argument values that carry hard constraints and attributes.")
    mode: Literal["advisory", "apply"]
    post_filter: list[str] = Field(
        default_factory=list, description="Residual ids the SDK filters from the results of an overfetch."
    )
    residual: list[str] = Field(default_factory=list, description="Ids no argument of the tool can express.")
    tool: ShortStr


class Shown(ResponseModel):
    last_at: datetime | None = None
    ref: ObjectKey
    times: int = Field(ge=1)


class SoftConstraint(ResponseModel):
    attr: Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9_]{0,39}\.[a-z][a-z0-9_]{0,63}$")]
    category: ShortStr | None = None
    confidence: float = Field(ge=0.0, le=1.0)
    id: Annotated[str, StringConstraints(pattern=r"^s[0-9]{1,4}$")]
    polarity: Literal["prefer", "avoid"] = "prefer"
    source: Literal["inferred", "stated"]
    value: bool | int | float | Annotated[str, StringConstraints(max_length=256)]
    weight: float = Field(ge=0.0, le=1.0)


class ConstraintsBlock(ResponseModel):
    """What one subject wants, refuses and is, for the tools of this turn (`constraints.v0`)."""

    already_presented: list[Shown] = Field(default_factory=list, max_length=200)
    ask: list[ShortStr] = Field(
        default_factory=list, description="Questions the agent should ask, as `for_whom`, before assuming."
    )
    attributes: list[AttributeEntry] = Field(default_factory=list, max_length=50)
    conflicts: list[Conflict] = Field(default_factory=list, max_length=50)
    exclude: list[ObjectKey] = Field(default_factory=list, max_length=200)
    hard: list[HardConstraint] = Field(default_factory=list, max_length=100)
    precedence: list[Literal["current_utterance", "stated_persistent", "inferred"]] = Field(
        default_factory=list
    )
    relaxation_order: list[str] = Field(
        default_factory=list, description="What gives way first when a search finds nothing: `soft`, ids."
    )
    rendered: Rendered | None = None
    rules: list[CompanyRule] = Field(default_factory=list, max_length=50)
    soft: list[SoftConstraint] = Field(default_factory=list, max_length=100)
    subject: BlockSubject = Field(default_factory=BlockSubject)
    version: Annotated[str, StringConstraints(pattern=r"^cv_[0-9a-f]{8,64}$")] = Field(
        description="A digest of the block, which the turn record cites."
    )


class ConstraintsRequest(Model):
    conversation_id: IdStr | None = None
    for_: Annotated[str, StringConstraints(pattern=r"^(?:self|gift|beneficiary:[A-Za-z0-9_-]{1,64})$")] = (
        Field(default="self", alias="for")
    )
    subject: Handle
    tool: ShortStr | None = Field(default=None, description="Rendered for this tool's bindings.")


class CounterfactualRun(ResponseModel):
    limits: list[str] = Field(default_factory=list)
    noise_floor: float | None = None
    overlap_at_k: float | None = None
    run_id: IdStr


class CounterfactualRunCreate(Model):
    element: ShortStr
    results: list[dict[str, Any]] = Field(min_length=1, max_length=5000)
    tool: ShortStr


class Inference(ResponseModel):
    """One thing the signals infer about the subject, with what it rests on: the subject can see it, correct
    it and delete it. What the subject said is not an inference, and is not listed.
    """

    at: datetime = Field(description="When its latest evidence happened.")
    attr: (
        Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9_]{0,39}\.[a-z][a-z0-9_]{0,63}$")] | None
    ) = Field(default=None, description="The field whose value is inferred.")
    confidence: float | None = None
    evidence: dict[str, Any] = Field(
        default_factory=dict,
        description=(
            "What it rests on, as counts: effective exposure, weighted signal, events, sessions and "
            "lift for a value; times for an interest."
        ),
    )
    for_: Annotated[str, StringConstraints(pattern=r"^(?:self|gift|beneficiary:[A-Za-z0-9_-]{1,64})$")] = (
        Field(default="self", alias="for")
    )
    key: IdStr = Field(description="A keyed hash that names the inference; it never carries its value.")
    kind: Literal["affinity", "soft_constraint", "attribute", "interest"] = Field(
        description=(
            "`soft_constraint` when the constraints block carries it as a soft entry, `attribute` for "
            "the inferred size, `affinity` for a value with evidence and no entry yet, `interest` for "
            "an object."
        )
    )
    origin: ShortStr = Field(
        description=(
            "`interactions`, `implicit_negative` (shown often and never engaged with), or why an "
            "interest was kept: `engaged`, `feedback`, `watch`."
        )
    )
    polarity: Literal["prefer", "avoid"] | None = None
    ref: ObjectKey | None = Field(default=None, description="The object of an interest.")
    used_for: list[ShortStr] = Field(default_factory=list, description="The purposes it is used for.")
    value: bool | int | float | Annotated[str, StringConstraints(max_length=256)] | None = None


class InferenceCorrection(Model):
    """The value the subject says instead: a stated preference, or a stated attribute for an inferred size
    (`source: correction`). The inference it corrects is deleted. An interest is deleted, not corrected.
    """

    reason: Annotated[str, StringConstraints(min_length=1, max_length=500)] | None = None
    value: bool | int | float | Annotated[str, StringConstraints(max_length=256)]


class InferencePage(ResponseModel):
    items: list[Inference]
    next_cursor: str | None = None


class InterleavingReport(ResponseModel):
    rows: list[dict[str, Any]]


class LegalHold(ResponseModel):
    created_at: datetime
    hold_id: IdStr
    released_at: datetime | None = None
    scope: Literal["handle", "object", "conversation"]
    status: Literal["active", "released"]


class LegalHoldCreate(Model):
    """Exactly one of `handle`, `object` or `conversation_id`: what is kept from purging while the hold is
    active.
    """

    conversation_id: IdStr | None = None
    handle: Handle | None = None
    object: ObjectRef | None = None
    reason: Annotated[str, StringConstraints(min_length=1, max_length=500)]


class LegalHoldRelease(Model):
    reason: Annotated[str, StringConstraints(min_length=1, max_length=500)]


class OutcomeLink(ResponseModel):
    """One outcome attributed to what an agent did, by one method. `line` and `order` are deterministic: the
    exposure token the order line or the order carried, or the agent's own action on the object. `identity`
    and `assisted_handoff` are probable: the same item engaged with or shown within a window, or a handoff
    that assisted the sale. A link carries its line's value whole or none at all: a value is never
    weighted.
    """

    action_id: IdStr | None = None
    agent: ShortStr | None = None
    band: Literal["deterministic", "probable"]
    currency: ShortStr | None = None
    exposure_id: IdStr | None = None
    final_at: datetime | None = Field(default=None, description="When a provisional link becomes final.")
    finality: Literal["provisional", "final", "expired_without_outcome"] = Field(
        description=(
            "`provisional` until the exchange window ends or the object reaches a final state; "
            "`expired_without_outcome` when its deadline passed first."
        )
    )
    handoff_id: IdStr | None = None
    known_at: datetime
    line: ShortStr | None = None
    link_id: IdStr
    method: Literal["line", "order", "identity", "assisted_handoff"]
    object: ObjectKey
    outcome: ShortStr = Field(description="The outcome definition of the `measurement` document.")
    position: int | None = None
    state: ShortStr = Field(description="The state the object or its line is in.")
    turn_id: IdStr | None = None
    valid_at: datetime = Field(description="When the outcome first counted.")
    value_minor: int | None = Field(default=None, description="In the currency's minor units; absent: none.")


class OutcomePage(ResponseModel):
    items: list[OutcomeLink]
    next_cursor: str | None = None


class PowerRequest(Model):
    alpha: float = Field(default=0.05, gt=0.0, lt=1.0)
    effect: float = Field(gt=0.0, lt=1.0)
    metric: ShortStr
    power: float = Field(default=0.8, gt=0.0, lt=1.0)


class PowerResult(ResponseModel):
    days: int | None
    sample_size: int | None


class ReconcileRequest(Model):
    file: BiFile
    since: date
    until: date


class ReconciledLine(ResponseModel):
    bi_minor: int
    line: str
    order: IdStr
    ours_minor: int


class ReconcileResult(ResponseModel):
    """Our value of each line against the BI's, on the lines both know; lines only one side knows are counted
    apart and never enter the deviation.
    """

    bi_minor: int
    currency: str | None = None
    deviation: float | None = Field(description="|ours - BI| / BI on the lines both know.")
    matched: int
    only_bi: int
    only_ours: int
    ours_minor: int
    report_id: IdStr
    tolerance: float
    within_tolerance: bool
    worst: list[ReconciledLine] = Field(default_factory=list, description="The lines that differ most.")


class ReviewRequest(ResponseModel):
    created_at: datetime
    decision_receipt_id: UUID | None = None
    explanation: dict[str, Any] = Field(
        default_factory=dict,
        description=(
            "Built from receipts: their ids, kinds, surfaces, rules, versions and inputs by reference, "
            "never personal content."
        ),
    )
    outcome: Literal["upheld", "reversed", "corrected"] | None = None
    profile_id: IdStr
    reason: str | None = None
    request_id: IdStr
    resolution: str | None = Field(default=None, description="The reviewer's note.")
    resolved_at: datetime | None = None
    status: Literal["open", "resolved"]


class ReviewRequestCreate(Model):
    """A request to review an automated decision, sent to the controller's data protection officer."""

    decision_receipt_id: UUID | None = Field(
        default=None, description="The receipt of the decision; absent, the subject's recent decisions."
    )
    reason: Annotated[str, StringConstraints(min_length=1, max_length=500)]


class ReviewRequestPage(ResponseModel):
    items: list[ReviewRequest]
    next_cursor: str | None = None


class ReviewResolution(Model):
    note: Annotated[str, StringConstraints(min_length=1, max_length=500)] | None = None
    outcome: Literal["upheld", "reversed", "corrected"]


class UnmetDemandPage(ResponseModel):
    items: list[dict[str, Any]]
    next_cursor: str | None = None
