# Generated by scripts/sync_spec.py from spec/openapi/cell.json. Do not edit.
"""Subject signals, the constraints block, the reviewable profile, review requests, legal holds and
measurement.
"""

from __future__ import annotations

from datetime import date, datetime
from typing import Annotated, Any, Literal
from uuid import UUID

from pydantic import Field, StringConstraints

from niadra.models._base import IdStr, Model, ResponseModel, ShortStr
from niadra.models.common import Handle, ObjectRef

ObjectKey = Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9_]{0,39}:[^:\s]{1,256}:\S{1,512}$")]
TurnId = Annotated[str, StringConstraints(pattern=r"^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$")]


class ArmComparison(ResponseModel):
    """One arm against `control` on one metric, adjusted by CUPED when the history varies, with the mixture
    sequential test: its p-value and interval hold at any look, so the report may be read every day.
    """

    arm: str
    arm_mean: float
    ci_high: float
    ci_low: float = Field(description="The always-valid interval of `difference` at the test's `alpha`.")
    control_mean: float = Field(description="Per person, before the adjustment.")
    decided: bool = Field(description="`p_value` at or below `alpha`: the difference is real.")
    difference: float = Field(description="The arm minus the control, per person, adjusted.")
    looks: int = Field(description="The daily looks kept before this one.")
    metric: Literal["conversion", "value"]
    p_value: float = Field(description="The running minimum over the daily looks and this one.")
    relative: float | None = Field(description="`difference` over the control's mean.")
    variance_reduction: float | None = Field(
        description="The share of the variance CUPED removed; absent when it did not apply."
    )


class ArmOutcomes(ResponseModel):
    """The people one arm holds and what they did after they were assigned, from the outcome links."""

    arm: str
    converted: int = Field(description="People with an outcome in a success state.")
    outcomes: int
    people: int
    value_minor: int = Field(description="Their lines' money, each line once whatever the method.")


class AskedAttribute(ResponseModel):
    attr: Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9_]{0,39}\.[a-z][a-z0-9_]{0,63}$")]
    op: Literal["in", "not_in", "eq", "ne", "lt", "lte", "gt", "gte", "between"]
    values: list[bool | int | float | Annotated[str, StringConstraints(max_length=256)]]


class AttributeEntry(ResponseModel):
    apply: Literal["always", "when_asked"]
    category: ShortStr | None = None
    confidence: float = Field(ge=0.0, le=1.0)
    id: Annotated[str, StringConstraints(pattern=r"^z[0-9]{1,4}$")]
    name: Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9_]{0,63}(?:\.[a-z0-9_]{1,64}){0,3}$")]
    source: Literal["stated", "correction", "acquired", "kept", "returned_for_size", "inferred"]
    system: ShortStr | None = None
    value: bool | int | float | Annotated[str, StringConstraints(max_length=256)]


class AttributionRow(ResponseModel):
    agent: str
    band: Literal["deterministic", "probable"]
    currency: str
    day: date
    finality: Literal["provisional", "final", "expired_without_outcome"]
    lines: int
    method: Literal["line", "order", "identity", "assisted_handoff"]
    outcome: ShortStr
    outcomes: int
    value_minor: int


class AttributionTotal(ResponseModel):
    """One method, band and finality over the period: deterministic and probable are never added together."""

    band: Literal["deterministic", "probable"]
    currency: str
    finality: Literal["provisional", "final", "expired_without_outcome"]
    lines: int
    method: Literal["line", "order", "identity", "assisted_handoff"]
    outcome: ShortStr
    outcomes: int
    value_minor: int


class IdentityCalibration(ResponseModel):
    """How often the identity method names the exposure the line's own token names, on the lines where both
    exist: the confidence of that method in this space.
    """

    agreeing: int
    compared: int
    rate: float | None = None


class AttributionReport(ResponseModel):
    """Value by day, agent, method and band, deterministic and probable apart; a value is never multiplied by
    a confidence, and no total adds a probable value to a deterministic one.
    """

    identity: IdentityCalibration
    rows: list[AttributionRow]
    since: date
    totals: list[AttributionTotal]
    until: date


class BiFile(Model):
    """The company's BI export for the period, uploaded first (`POST /v1/measure/reconcile/uploads`), as CSV
    with a header: `order` (the id the company knows the object by), `line` (optional), `value` (in major
    units, as the signed definition nets it) and `currency`. It is read once and deleted.
    """

    format: Literal["csv"] = "csv"
    upload_id: UUID


class BiUpload(ResponseModel):
    expires_at: datetime
    upload_headers: dict[str, str] = Field(
        default_factory=dict, description="Send exactly these headers; the storage refuses other bytes."
    )
    upload_id: UUID
    upload_url: str


class BiUploadRequest(Model):
    """Reserves the upload of the company's BI file: its size and SHA-256, which the storage checks."""

    sha256: Annotated[str, StringConstraints(pattern=r"^[0-9a-f]{64}$")]
    size_bytes: int = Field(ge=1, le=52428800)


class BlockSubject(ResponseModel):
    for_: Annotated[str, StringConstraints(pattern=r"^(?:self|gift|beneficiary:[A-Za-z0-9_-]{1,64})$")] = (
        Field(default="self", alias="for")
    )


class CompanyRule(ResponseModel):
    """A rule of the company delivered in the block, with where it lives and its rank in the order the company
    declared: the block never ranks two origins by itself.
    """

    attr: (
        Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9_]{0,39}\.[a-z][a-z0-9_]{0,63}$")] | None
    ) = None
    id: Annotated[str, StringConstraints(pattern=r"^r[0-9]{1,4}$")]
    op: Literal["in", "not_in", "eq", "ne", "lt", "lte", "gt", "gte", "between"] | None = None
    origin: ShortStr = Field(description="`code`, `db:<table>`, `prompt:<version>`, `policy:<version>`...")
    rank: int = Field(ge=1, le=100)
    values: list[bool | int | float | Annotated[str, StringConstraints(max_length=256)]] = Field(
        default_factory=list, max_length=50
    )


class Conflict(ResponseModel):
    """Two entries that cannot both hold, and the one that won: the current utterance over what was stated
    before, and a stated entry over an inferred one. Between two company rules, it is also a data issue.
    """

    by: Literal["current_utterance", "precedence", "rule_rank"]
    ids: list[str] = Field(min_length=2, max_length=10)
    kept: str


class ConstraintOrigin(ResponseModel):
    event_key: IdStr | None = None
    kind: Literal["stated", "tool_args", "correction"]
    turn_id: IdStr | None = None


class HardConstraint(ResponseModel):
    """Only what the person said: an inference is never hard."""

    attr: Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9_]{0,39}\.[a-z][a-z0-9_]{0,63}$")]
    category: ShortStr | None = None
    expires_at: datetime | None = None
    id: Annotated[str, StringConstraints(pattern=r"^h[0-9]{1,4}$")]
    object: ObjectKey | None = Field(
        default=None, description="With `scope: object`, the object the instruction is about."
    )
    op: Literal["in", "not_in", "eq", "ne", "lt", "lte", "gt", "gte", "between"]
    origin: ConstraintOrigin
    relax: Literal["never", "ask"] = "never"
    scope: Literal["turn", "session", "persistent", "object"]
    source: Literal["stated", "tool_args", "correction"]
    values: list[bool | int | float | Annotated[str, StringConstraints(max_length=256)]] = Field(
        min_length=1, max_length=50
    )


class ObjectInstruction(ResponseModel):
    """What someone said must or must not be done about an object the read is about: a task on the object, a
    read by the object, or a task view of its type. Hard, never relaxed, never inferred; one about a field
    of the object's type is also in `hard`, where a tool binding applies it.
    """

    about: UUID | None = Field(
        default=None,
        description=(
            "Naming no object: the organization (its profile) it is about, a client the read is about, "
            "its own reads or a contact's read with `about`."
        ),
    )
    attr: (
        Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9_]{0,39}\.[a-z][a-z0-9_]{0,63}$")] | None
    ) = Field(default=None, description="The field of the object's type it is about.")
    contact: bool = Field(
        default=False,
        description=(
            "A contact preference (a channel, hours): how the company reaches `only_with`, never a "
            "limit on what may be said to them."
        ),
    )
    expires_at: datetime | None = None
    hard: Annotated[str, StringConstraints(pattern=r"^h[0-9]{1,4}$")] | None = Field(
        default=None, description="The entry of `hard` that carries it for a tool, when `attr` is set."
    )
    id: Annotated[str, StringConstraints(pattern=r"^i[0-9]{1,4}$")]
    object: ObjectKey | None = Field(default=None, description="The object it is about.")
    only_with: ShortStr | None = Field(
        default=None,
        description=(
            "The one person it holds with, as the conversation named them: it binds the readers dealing"
            " with that person, not whoever is speaking. With `contact`, the person it is the "
            "preference of."
        ),
    )
    role: ShortStr | None = Field(
        default=None, description="The role on the object of who said it (`owner`, `participant`, `lawyer`)."
    )
    said_at: datetime
    strength: Literal["must", "must_not"]
    text: Annotated[str, StringConstraints(max_length=256)] = Field(
        description="As it was said, short: what a reader honors without a tool binding."
    )


class Rendered(ResponseModel):
    """The block for one tool, through its bindings (`constraints.v0`, rendering)."""

    args: dict[str, Any] = Field(description="Argument values that carry hard constraints and attributes.")
    mode: Literal["advisory", "apply"]
    post_filter: list[str] = Field(
        default_factory=list, description="Residual ids the SDK filters from the results of an overfetch."
    )
    residual: list[str] = Field(default_factory=list, description="Ids no argument of the tool can express.")
    tool: ShortStr


class ShownValue(ResponseModel):
    """A number an object showed the subject, as they were shown it."""

    claim_safe: bool = Field(
        description=(
            "Whether it may be claimed now: its type allows claims of the field, and no more than the "
            "field's age for claims has passed since it was shown."
        )
    )
    role: ShortStr | None = Field(default=None, description="The field's role, for claims.")
    v: float


class Shown(ResponseModel):
    last_at: datetime | None = None
    ref: ObjectKey
    times: int = Field(ge=1)
    values: dict[str, ShownValue] = Field(
        default_factory=dict,
        description=(
            "The numbers the object was last shown with (a price, a total, a discount, an installment),"
            " by field: each field its type declares as `money`, `percent` or `number`. A claim check "
            "takes them as evidence for the offer an agent quotes back."
        ),
    )


class SoftConstraint(ResponseModel):
    attr: Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9_]{0,39}\.[a-z][a-z0-9_]{0,63}$")]
    category: ShortStr | None = None
    confidence: float = Field(ge=0.0, le=1.0)
    id: Annotated[str, StringConstraints(pattern=r"^s[0-9]{1,4}$")]
    polarity: Literal["prefer", "avoid"] = "prefer"
    source: Literal["inferred", "stated"]
    value: bool | int | float | Annotated[str, StringConstraints(max_length=256)]
    weight: float = Field(ge=0.0, le=1.0)


class ConstraintsBlock(ResponseModel):
    """What one subject wants, refuses and is, for the tools of this turn (`constraints.v0`)."""

    already_presented: list[Shown] = Field(default_factory=list, max_length=200)
    ask: list[ShortStr] = Field(
        default_factory=list, description="Questions the agent should ask, as `for_whom`, before assuming."
    )
    attributes: list[AttributeEntry] = Field(default_factory=list, max_length=50)
    conflicts: list[Conflict] = Field(default_factory=list, max_length=50)
    exclude: list[ObjectKey] = Field(default_factory=list, max_length=200)
    hard: list[HardConstraint] = Field(default_factory=list, max_length=100)
    instructions: list[ObjectInstruction] = Field(
        default_factory=list,
        max_length=500,
        description="What people said must or must not be done about the objects the read is about.",
    )
    omitted: dict[str, int] = Field(
        default_factory=dict,
        description=(
            "How many entries of each kind (`hard`, `soft`, `exclude`, `already_presented`, "
            "`instructions`) the block's sizes left out; the restrictions keep their room first. Absent"
            " when nothing was left out; `text` says it too."
        ),
    )
    precedence: list[Literal["current_utterance", "stated_persistent", "inferred"]] = Field(
        default_factory=list
    )
    relaxation_order: list[str] = Field(
        default_factory=list, description="What gives way first when a search finds nothing: `soft`, ids."
    )
    rendered: Rendered | None = None
    rules: list[CompanyRule] = Field(default_factory=list, max_length=50)
    soft: list[SoftConstraint] = Field(default_factory=list, max_length=100)
    subject: BlockSubject = Field(default_factory=BlockSubject)
    text: str = Field(
        description=(
            "The block as lines for a model, in the space's language, each field by its label and each "
            "operator in words; an empty string when the block has nothing to say. Not part of "
            "`version`."
        )
    )
    version: Annotated[str, StringConstraints(pattern=r"^cv_[0-9a-f]{8,64}$")] = Field(
        description="A digest of the block, which the turn record cites."
    )


class ConstraintsRequest(Model):
    conversation_id: IdStr | None = None
    for_: Annotated[str, StringConstraints(pattern=r"^(?:self|gift|beneficiary:[A-Za-z0-9_-]{1,64})$")] = (
        Field(default="self", alias="for")
    )
    subject: Handle
    tool: ShortStr | None = Field(default=None, description="Rendered for this tool's bindings.")


class CounterfactualEngaged(Model):
    """An item the person engaged with in the recorded turn, by its 1-based position in each live list; absent
    where the list does not hold it.
    """

    base: Annotated[int, Field(ge=1, le=10000)] | None = None
    variant: Annotated[int, Field(ge=1, le=10000)] | None = None


class CounterfactualCase(Model):
    """One recorded tool call run live three times at the same moment: twice with the element (the base, whose
    two lists measure the tool's own noise) and once without it (the variant). Positions and overlaps only:
    never an item, an argument or a result.
    """

    base_count: Annotated[int, Field(ge=0)] | None = Field(
        default=None, description="Items in the base's first list."
    )
    call_id: ShortStr
    dry_run: bool = Field(default=False, description="The calls ran as the tool's dry run.")
    engaged: list[CounterfactualEngaged] = Field(default_factory=list, max_length=50)
    k: Annotated[int, Field(ge=1, le=100)] | None = Field(
        default=None,
        description="The positions compared: the recorded list's `visible_k`, else the run's `k`.",
    )
    noise: Annotated[float, Field(ge=0.0, le=1.0)] | None = Field(
        default=None, description="overlap@k of the base's two lists: the tool's own noise."
    )
    overlap: Annotated[float, Field(ge=0.0, le=1.0)] | None = Field(
        default=None, description="overlap@k of the base's first list and the variant's."
    )
    status: Literal["completed", "no_dry_run", "tool_error", "infrastructure_error"] = Field(
        description=(
            "`no_dry_run` for a tool that writes state and has no dry run: it is never called. "
            "`tool_error` when a call failed, `infrastructure_error` when the runner could not run the "
            "case."
        )
    )
    turn_id: TurnId
    variant_count: Annotated[int, Field(ge=0)] | None = Field(
        default=None, description="Items in the variant's list."
    )


class CounterfactualEngagement(ResponseModel):
    """Where the items the person engaged with went without the element, over the completed cases."""

    gained: int = Field(description="Within the variant's first `k` and not the base's.")
    items: int
    kept: int = Field(description="Within the first `k` of both lists.")
    lost: int = Field(description="Within the base's first `k` and not the variant's.")
    mean_shift: float | None = Field(
        default=None,
        description=(
            "The variant's position minus the base's, averaged over the items both lists hold; positive"
            " when they fell."
        ),
    )
    shown: int = Field(description="Within the first `k` of the base's list.")


class CounterfactualRun(ResponseModel):
    """Whether the element changes what the tool returns, beyond the tool's own noise. It never says whether
    the result got better, nor how the model reacts: `limits` says so, and what else holds the answer back.
    """

    above_noise: int
    below_noise: int = Field(description="Completed cases whose overlap is below their own noise.")
    cases: int
    completed: int
    created_at: datetime
    effect: float | None = Field(
        description=(
            "`noise_floor - overlap`: how much of the first positions the element moves beyond noise."
        )
    )
    element: Literal["constraints", "hard", "size", "exclude"]
    engaged: CounterfactualEngagement
    label: str | None = None
    limits: list[
        Literal[
            "not_quality",
            "model_reaction_not_measured",
            "trivial_for_hard",
            "few_cases",
            "noisy_tool",
            "cases_skipped",
            "dry_run",
        ]
    ]
    noise_floor: float | None = Field(description="Mean overlap@k of the base with itself.")
    overlap: float | None = Field(description="Mean overlap@k of the base and the variant.")
    p_value: float | None = Field(
        description=(
            "The two-sided sign test of `below_noise` against `above_noise`: how likely a split this "
            "uneven is when the element changes nothing."
        )
    )
    run_id: IdStr
    skipped: dict[str, int] = Field(default_factory=dict, description="The cases not completed.")
    ties: int
    tool: str


class CounterfactualRunCreate(Model):
    """What a runner measured in the company's CI for one tool and one element (the tool counterfactual
    spec).
    """

    cases: list[CounterfactualCase] = Field(min_length=1, max_length=5000)
    element: Literal["constraints", "hard", "size", "exclude"]
    k: int = Field(
        default=10,
        ge=1,
        le=100,
        description="The positions compared when a recorded list has no `visible_k`.",
    )
    label: ShortStr | None = Field(
        default=None, description="A name for the run, such as the commit or the build it ran on."
    )
    tool: Annotated[str, StringConstraints(pattern=r"^[A-Za-z][A-Za-z0-9_.:-]{0,63}$")]


class CounterfactualRunPage(ResponseModel):
    items: list[CounterfactualRun]
    next_cursor: str | None = None


class ExperimentResult(ResponseModel):
    agent: str | None = None
    alpha: float
    arms: list[ArmOutcomes]
    comparisons: list[ArmComparison] = Field(
        description="Empty until each arm holds enough people for the normal approximation."
    )
    cuped_days: int = Field(description="The days before each person's assignment taken as the covariate.")
    element: str | None = None
    ends_at: datetime | None = None
    experiment: ShortStr
    kind: Literal["element", "agent"]
    starts_at: datetime


class ExperimentReport(ResponseModel):
    """Every experiment on an element or an agent, arm by arm, from what people did after they were assigned:
    incremental, as only a holdout says.
    """

    as_of: datetime
    experiments: list[ExperimentResult]


class Inference(ResponseModel):
    """One thing the signals infer about the subject, with what it rests on: the subject can see it, correct
    it and delete it. What the subject said is not an inference, and is not listed.
    """

    at: datetime = Field(description="When its latest evidence happened.")
    attr: (
        Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9_]{0,39}\.[a-z][a-z0-9_]{0,63}$")] | None
    ) = Field(default=None, description="The field whose value is inferred.")
    confidence: float | None = None
    evidence: dict[str, Any] = Field(
        default_factory=dict,
        description=(
            "What it rests on, as counts: effective exposure, weighted signal, events, sessions and "
            "lift for a value; times for an interest."
        ),
    )
    for_: Annotated[str, StringConstraints(pattern=r"^(?:self|gift|beneficiary:[A-Za-z0-9_-]{1,64})$")] = (
        Field(default="self", alias="for")
    )
    key: IdStr = Field(description="A keyed hash that names the inference; it never carries its value.")
    kind: Literal["affinity", "soft_constraint", "attribute", "interest", "instruction"] = Field(
        description=(
            "`soft_constraint` when the constraints block carries it as a soft entry, `attribute` for "
            "the inferred size, `affinity` for a value with evidence and no entry yet, `interest` for "
            "an object, `instruction` for what the subject said must or must not be done about an "
            "object (`ref`, the words in `value`): said, not inferred, and listed so a correction can "
            "withdraw it."
        )
    )
    origin: ShortStr = Field(
        description=(
            "`interactions`, `implicit_negative` (shown often and never engaged with), or why an "
            "interest was kept: `engaged`, `feedback`, `watch`."
        )
    )
    polarity: Literal["prefer", "avoid"] | None = None
    ref: ObjectKey | None = Field(default=None, description="The object of an interest.")
    used_for: list[ShortStr] = Field(default_factory=list, description="The purposes it is used for.")
    value: bool | int | float | Annotated[str, StringConstraints(max_length=256)] | None = None


class InferenceCorrection(Model):
    """The value the subject says instead: a stated preference, or a stated attribute for an inferred size
    (`source: correction`). The inference it corrects is deleted. An interest is deleted, not corrected.
    """

    reason: Annotated[str, StringConstraints(min_length=1, max_length=500)] | None = None
    value: bool | int | float | Annotated[str, StringConstraints(max_length=256)]


class InferencePage(ResponseModel):
    items: list[Inference]
    next_cursor: str | None = None


class InterleavingRow(ResponseModel):
    day: date
    experiment: ShortStr
    impressions: int
    ties: int = Field(description="Impressions engaged with equally, or not at all.")
    tool: ShortStr
    wins_a: int = Field(description="Impressions whose engagement went to the items ranking `a` contributed.")
    wins_b: int


class InterleavingTotal(ResponseModel):
    experiment: ShortStr
    impressions: int
    p_value: float | None = Field(
        description="The two-sided sign test on the decided impressions; absent before any was decided."
    )
    ties: int
    tool: ShortStr
    wins_a: int
    wins_b: int


class InterleavingReport(ResponseModel):
    """Interleaved lists of a tool's two rankings (team draft, seeded by the turn): which ranking the person's
    engagement credited, impression by impression, by day and over the period.
    """

    rows: list[InterleavingRow]
    since: date
    totals: list[InterleavingTotal]
    until: date


class LegalHold(ResponseModel):
    created_at: datetime
    hold_id: IdStr
    released_at: datetime | None = None
    scope: Literal["handle", "object", "conversation"]
    status: Literal["active", "released"]


class LegalHoldCreate(Model):
    """Exactly one of `handle`, `object` or `conversation_id`: what is kept from purging while the hold is
    active.
    """

    conversation_id: IdStr | None = None
    handle: Handle | None = None
    object: ObjectRef | None = None
    reason: Annotated[str, StringConstraints(min_length=1, max_length=500)]


class LegalHoldRelease(Model):
    reason: Annotated[str, StringConstraints(min_length=1, max_length=500)]


class OutcomeLink(ResponseModel):
    """One outcome attributed to what an agent did, by one method. `line` and `order` are deterministic: the
    exposure token the order line or the order carried, or the agent's own action on the object. `identity`
    and `assisted_handoff` are probable: the same item engaged with or shown within a window, or a handoff
    that assisted the sale. A link carries its line's value whole or none at all: a value is never
    weighted.
    """

    action_id: IdStr | None = None
    agent: ShortStr | None = None
    band: Literal["deterministic", "probable"]
    confidence: float | None = Field(
        default=None,
        description=(
            "Of an `identity` link: how often that method names the exposure a line's own token names "
            "in this space, where both exist. Beside the value, never multiplied by it."
        ),
    )
    currency: ShortStr | None = None
    exposure_id: IdStr | None = None
    final_at: datetime | None = Field(default=None, description="When a provisional link becomes final.")
    finality: Literal["provisional", "final", "expired_without_outcome"] = Field(
        description=(
            "`provisional` until the exchange window ends or the object reaches a final state; "
            "`expired_without_outcome` when its deadline passed first."
        )
    )
    handoff_id: IdStr | None = None
    known_at: datetime
    line: ShortStr | None = None
    link_id: IdStr
    method: Literal["line", "order", "identity", "assisted_handoff"]
    object: ObjectKey
    outcome: ShortStr = Field(description="The outcome definition of the `measurement` document.")
    position: int | None = None
    purchase: ObjectKey | None = Field(
        default=None,
        description=(
            "The purchase it counts in, when the revenue definition counts a split purchase's parts as "
            "one order."
        ),
    )
    state: ShortStr = Field(description="The state the object or its line is in.")
    turn_id: IdStr | None = None
    valid_at: datetime = Field(description="When the outcome first counted.")
    value_minor: int | None = Field(
        default=None,
        description=(
            "In the currency's minor units, as the signed revenue definition counts it; absent: none."
        ),
    )


class OutcomePage(ResponseModel):
    items: list[OutcomeLink]
    next_cursor: str | None = None


class PowerRequest(Model):
    """How long the space's traffic takes to detect a difference of `effect` (relative: 0.1 is 10%) on
    `metric`. The traffic and the baseline come from the space's history, the named experiment's or the
    busiest one's of the last 28 days, unless given.
    """

    alpha: float = Field(default=0.05, le=0.2, gt=0.0)
    baseline_mean: Annotated[float, Field(ge=0.0)] | None = Field(
        default=None, description="Per person: a rate for `conversion`, minor units for `value`."
    )
    baseline_sd: Annotated[float, Field(gt=0.0)] | None = Field(
        default=None, description="Per person, for `value`; a rate's follows from its mean."
    )
    control_fraction: float = Field(default=0.5, gt=0.0, lt=1.0)
    daily_people: Annotated[int, Field(ge=1)] | None = Field(
        default=None, description="New people a day entering the test."
    )
    effect: float = Field(le=10.0, gt=0.0, description="The relative difference to detect: 0.1 is 10%.")
    experiment: ShortStr | None = Field(default=None, description="The experiment whose history to use.")
    metric: Literal["conversion", "value"] = "conversion"
    power: float = Field(default=0.8, ge=0.5, lt=1.0)


class PowerResult(ResponseModel):
    baseline_from: Literal["given", "history"]
    baseline_mean: float
    baseline_sd: float
    daily_people: float
    days: int | None = Field(description="At a fixed horizon, looked at once, at the end.")
    days_sequential: int | None
    effect: float
    experiment: str | None = Field(default=None, description="The experiment whose history was used.")
    metric: Literal["conversion", "value"]
    people: int | None = Field(description="Both arms together, at a fixed horizon.")
    people_sequential: int | None = Field(
        description="Both arms together, for the daily-looked sequential test to have decided with `power`."
    )
    traffic_from: Literal["given", "history"]


class ReconcileRequest(Model):
    file: BiFile
    since: date
    until: date


class ReconciledLine(ResponseModel):
    bi_minor: int
    line: str
    order: IdStr
    ours_minor: int


class ReconcileResult(ResponseModel):
    """Our value of each line against the BI's, on the lines both know; lines only one side knows are counted
    apart and never enter the deviation.
    """

    bi_minor: int
    currency: str | None = None
    deviation: float | None = Field(description="|ours - BI| / BI on the lines both know.")
    matched: int
    only_bi: int
    only_ours: int
    ours_minor: int
    report_id: IdStr
    tolerance: float
    within_tolerance: bool
    worst: list[ReconciledLine] = Field(default_factory=list, description="The lines that differ most.")


class ReviewRequest(ResponseModel):
    created_at: datetime
    decision_receipt_id: UUID | None = None
    explanation: dict[str, Any] = Field(
        default_factory=dict,
        description=(
            "Built from receipts: their ids, kinds, surfaces, rules, versions and inputs by reference, "
            "never personal content."
        ),
    )
    outcome: Literal["upheld", "reversed", "corrected"] | None = None
    profile_id: IdStr
    reason: str | None = None
    request_id: IdStr
    resolution: str | None = Field(default=None, description="The reviewer's note.")
    resolved_at: datetime | None = None
    status: Literal["open", "resolved"]


class ReviewRequestCreate(Model):
    """A request to review an automated decision, sent to the controller's data protection officer."""

    decision_receipt_id: UUID | None = Field(
        default=None, description="The receipt of the decision; absent, the subject's recent decisions."
    )
    reason: Annotated[str, StringConstraints(min_length=1, max_length=500)]


class ReviewRequestPage(ResponseModel):
    items: list[ReviewRequest]
    next_cursor: str | None = None


class ReviewResolution(Model):
    note: Annotated[str, StringConstraints(min_length=1, max_length=500)] | None = None
    outcome: Literal["upheld", "reversed", "corrected"]


class UnmetDemand(ResponseModel):
    """One combination people asked a tool for, in one week, that came back with nothing or with fewer than
    three results. Never a person: a combination fewer than the space's minimum of people asked is left
    out.
    """

    asked: list[AskedAttribute] = Field(
        description=(
            "What the tool's arguments asked, on the type registry's fields, values normalized; empty "
            "when the arguments named none."
        )
    )
    calls: int
    empty: int = Field(description="Calls that returned nothing; the rest returned one or two results.")
    people: int = Field(description="Distinct people who asked it that week.")
    tool: str
    week: date = Field(description="The Monday the week starts on.")


class UnmetDemandPage(ResponseModel):
    items: list[UnmetDemand]
    min_people: int
    next_cursor: str | None = None
    since: date
    until: date
