# Generated by scripts/sync_spec.py from spec/openapi/cell.json. Do not edit.
"""Subject signals, the constraints block, the reviewable profile, review requests, legal holds and
measurement.

Draft: the server has not fixed these models yet, and their fields may still change.
"""

from __future__ import annotations

from datetime import date, datetime
from typing import Annotated, Any, Literal

from pydantic import Field, StringConstraints

from niadra.models._base import IdStr, Model, ResponseModel, ShortStr
from niadra.models.common import Handle, ObjectRef


class AttributionReport(ResponseModel):
    """Value by method and band, deterministic and probable apart; weights are never summed as money."""

    rows: list[dict[str, Any]]
    since: date
    until: date


class ConstraintsBlock(ResponseModel):
    """The `constraints.v0` block."""

    already_presented: list[dict[str, Any]] = Field(default_factory=list)
    ask: list[str] = Field(default_factory=list)
    attributes: list[dict[str, Any]] = Field(default_factory=list)
    exclude: list[str] = Field(default_factory=list)
    hard: list[dict[str, Any]] = Field(default_factory=list)
    precedence: str | None = None
    relaxation_order: list[str] = Field(default_factory=list)
    rendered: dict[str, Any] | None = None
    rules: list[dict[str, Any]] = Field(default_factory=list)
    soft: list[dict[str, Any]] = Field(default_factory=list)
    subject: dict[str, Any]
    version: ShortStr


class ConstraintsRequest(Model):
    conversation_id: IdStr | None = None
    for_: ShortStr = Field(default="self", alias="for")
    subject: Handle
    tool: ShortStr | None = Field(default=None, description="Rendered for this tool's bindings.")


class CounterfactualRun(ResponseModel):
    limits: list[str] = Field(default_factory=list)
    noise_floor: float | None = None
    overlap_at_k: float | None = None
    run_id: IdStr


class CounterfactualRunCreate(Model):
    element: ShortStr
    results: list[dict[str, Any]] = Field(min_length=1, max_length=5000)
    tool: ShortStr


class Inference(ResponseModel):
    at: datetime
    confidence: float | None = None
    evidence: dict[str, Any] = Field(default_factory=dict)
    key: IdStr
    kind: Literal["affinity", "soft_constraint", "attribute", "interest"]
    origin: ShortStr
    used_for: list[ShortStr] = Field(default_factory=list)


class InferenceCorrection(Model):
    """Becomes a stated preference (`source: correction`)."""

    reason: Annotated[str, StringConstraints(min_length=1, max_length=500)] | None = None
    value: Any


class InferencePage(ResponseModel):
    items: list[Inference]
    next_cursor: str | None = None


class InterleavingReport(ResponseModel):
    rows: list[dict[str, Any]]


class LegalHold(ResponseModel):
    created_at: datetime
    hold_id: IdStr
    released_at: datetime | None = None
    status: Literal["active", "released"]


class LegalHoldCreate(Model):
    conversation_id: IdStr | None = None
    handle: Handle | None = None
    object: ObjectRef | None = None
    reason: Annotated[str, StringConstraints(min_length=1, max_length=500)]


class LegalHoldRelease(Model):
    reason: Annotated[str, StringConstraints(min_length=1, max_length=500)]


class OutcomePage(ResponseModel):
    items: list[dict[str, Any]]
    next_cursor: str | None = None


class PowerRequest(Model):
    alpha: float = Field(default=0.05, gt=0.0, lt=1.0)
    effect: float = Field(gt=0.0, lt=1.0)
    metric: ShortStr
    power: float = Field(default=0.8, gt=0.0, lt=1.0)


class PowerResult(ResponseModel):
    days: int | None
    sample_size: int | None


class ReconcileRequest(Model):
    since: date
    until: date
    upload_ref: IdStr


class ReconcileResult(ResponseModel):
    detail: dict[str, Any] = Field(default_factory=dict)
    deviation: float


class ReviewRequest(ResponseModel):
    created_at: datetime
    profile_id: IdStr
    request_id: IdStr
    resolution: str | None = None
    status: Literal["open", "resolved"]


class ReviewRequestCreate(Model):
    """A request to review an automated decision (LGPD, art. 20), sent to the controller's DPO."""

    decision_receipt_id: IdStr | None = None
    reason: Annotated[str, StringConstraints(min_length=1, max_length=500)]


class ReviewRequestPage(ResponseModel):
    items: list[ReviewRequest]
    next_cursor: str | None = None


class ReviewResolution(Model):
    note: Annotated[str, StringConstraints(min_length=1, max_length=500)] | None = None
    outcome: Literal["upheld", "reversed", "corrected"]


class UnmetDemandPage(ResponseModel):
    items: list[dict[str, Any]]
    next_cursor: str | None = None
