# Generated by scripts/sync_spec.py from spec/openapi/cell.json. Do not edit.
"""Typed state: objects a system of record pushes, reads with a purpose, the agent's working state and the SDK
profile.
"""

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Any, Literal

from pydantic import Field, StringConstraints

from niadra.models._base import IdStr, Model, ResponseModel, ShortStr
from niadra.models.common import Handle

TypeName = Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9_]{0,39}$")]


class AgentState(ResponseModel):
    body: dict[str, Any] = Field(default_factory=dict)
    updated_at: datetime | None = None
    version: int


class AgentStateScope(Model):
    """What one working state belongs to. The id travels in the body, never in a URL: a conversation id may
    look like a phone number.
    """

    id: IdStr
    kind: Literal["conversation", "task", "object", "subject"]


class AgentStateReadRequest(Model):
    agent: ShortStr
    scope: AgentStateScope


class AgentStateWrite(Model):
    """A write of an agent's working state, by its code and never by a model: `cas` replaces the whole state
    at `if_version` (0 when it must not exist yet); `merge_by_key` replaces each top-level field it names
    and removes a field written as exactly `{"$delete": true}`.
    """

    agent: ShortStr
    body: dict[str, Any]
    if_version: Annotated[int, Field(ge=0)] | None = None
    mode: Literal["cas", "merge_by_key"]
    scope: AgentStateScope


class AgentStateWriteResult(ResponseModel):
    reason: Literal["over_cap", "not_declared_field"] | None = None
    stored: bool
    version: int


class ClaimContractSummary(ResponseModel):
    categories: list[dict[str, Any]] = Field(default_factory=list)
    negative_corpus_version: ShortStr | None = None
    outputs: dict[str, list[str]] = Field(default_factory=dict)
    version: ShortStr


class ContentMarker(ResponseModel):
    """A content field whose text Niadra does not hold (`pointer`, `hash_only`), or holds under scan."""

    mode: Literal["full", "pointer", "hash_only"]
    pointer: IdStr | None = Field(
        default=None, description="Where the SDK reads the text inside the company's boundary."
    )
    scan: Literal["pending", "clean", "flagged"]
    sha256: Annotated[str, StringConstraints(pattern=r"^[0-9a-f]{64}$")] | None = None


class ContentRelease(Model):
    reason: Annotated[str, StringConstraints(min_length=1, max_length=500)]


class ContentReleaseResult(ResponseModel):
    released: bool


Feature = Literal[
    "turns",
    "state",
    "agent_state",
    "signals",
    "claims",
    "coordination",
    "measurement",
    "notifications",
    "legal_holds",
]


class FieldCoverage(ResponseModel):
    age_p50_s: int | None = None
    coverage: float
    field: ShortStr


class PreviousValue(ResponseModel):
    """A field's value before its latest change, kept for the fields that declare `track_changes`."""

    logic: Literal["yes", "no", "unobserved", "known_defect"]
    v: Any = None


class FieldState(ResponseModel):
    """One field as a read serves it: the value with its logical value, stamps, source and observer, and the
    freshness computed now against the type's current rule.
    """

    age_s: int | None = Field(default=None, description="Seconds since `observed_at`.")
    claim_safe: bool
    completeness: ShortStr | None = None
    content: ContentMarker | None = None
    known_at: datetime | None = Field(default=None, description="When Niadra first knew it; never moves.")
    logic: Literal["yes", "no", "unobserved", "known_defect"]
    masked: bool = Field(default=False, description="The reader's access masks the value: `v` is absent.")
    observed_at: datetime | None = Field(default=None, description="When the source observed the value.")
    observer: ShortStr | None = None
    role: ShortStr | None = None
    src: ShortStr | None = None
    status: Literal["fresh", "stale", "expired"]
    v: Any = None
    valid_at: datetime | None = None
    was: PreviousValue | None = None


class TypeCoverage(ResponseModel):
    fields: list[FieldCoverage]
    type: TypeName


class ObjectCoverage(ResponseModel):
    types: list[TypeCoverage]


class Provenance(Model):
    """Where pushed values come from: only a `live` source sustains a claim, and the age of every value counts
    from `source_observed_at`.
    """

    scope: Literal["global", "customer", "context"] = "global"
    source: Literal["live", "snapshot", "cache"]
    source_observed_at: datetime


class StateRef(Model):
    """An object of the type registry: a subject's or a shared one, whose key may name a variant."""

    id: IdStr
    namespace: ShortStr
    type: ShortStr
    variant: ShortStr | None = None


class ObjectPush(Model):
    fields: dict[str, Any] = Field(max_length=200)
    provenance: Provenance
    ref: StateRef
    version: int = Field(
        ge=0,
        description=(
            "The source's version of the object. A field moves only when this is greater than the "
            "version that last wrote it; a source never reuses a version for other content."
        ),
    )


class ObjectPushRequest(Model):
    objects: list[ObjectPush] = Field(min_length=1, max_length=1000)


class ObjectPushResponse(ResponseModel):
    """How many items of the request each decision took, against the hot layer, with no database statement.

    A shared object's item is `applied` when at least one of its fields moved forward: reads serve it at
    once, and the consolidator writes it within a second with the same per-field rule, so the stored object
    never disagrees with the answer. `stale_version`: every field was already written by this version or a
    greater one, as a retried request finds. `out_of_set`: the object is not in the working set, and
    nothing is kept. A subject's object is `recorded`: accepted as a system event about it, in the
    request's one statement, and its fields move by the same rule when the event is applied.
    """

    applied: int
    out_of_set: int
    recorded: int = 0
    stale_version: int


class OutcomeState(ResponseModel):
    at: datetime | None = None
    final: bool
    state: ShortStr = Field(description="A canonical state of the type, or `expired_without_outcome`.")


class ReadingResult(ResponseModel):
    """A named reading's value, as niadra-expr computes it: the logical value, and the kind and value when
    known (dates as `YYYY-MM-DD`, times in UTC, durations in milliseconds).
    """

    absent: ShortStr | None = None
    logic: Literal["yes", "no", "unobserved", "known_defect"]
    type: Literal["bool", "number", "string", "duration", "date", "datetime", "list"] | None = None
    v: Any = None


class Refetch(ResponseModel):
    admitted: bool
    priority: Literal["high", "normal", "low"]
    reason: ShortStr


class Refusal(ResponseModel):
    action: ShortStr | None = None
    reason: ShortStr


class TimerState(ResponseModel):
    due_at: datetime | None = Field(default=None, description="Computed now from the rule and the values.")
    fired_at: datetime | None = None
    name: ShortStr
    state: Literal["armed", "fired", "cancelled"]


class ValueState(ResponseModel):
    """A value the company computed, kept as a versioned fact with the rule that produced it."""

    absent_as: ShortStr | None = Field(default=None, description="The name of the absence, when absent.")
    claim_safe: bool
    computed_at: datetime
    declared_gaps: list[str] = Field(default_factory=list)
    gap_effect: Literal["errs_early", "errs_late", "unknown"] = "unknown"
    logic: Literal["yes", "no", "unobserved", "known_defect"]
    rule: ShortStr
    status: Literal["fresh", "stale", "expired"]
    supersedes_version: int | None = None
    v: Any = None
    version: int = Field(ge=1)


class ObjectRead(ResponseModel):
    """One object as a state read serves it: fields with four logical values and their stamps, computed
    values, lifecycle, timers and readings, and what may not be claimed with data this old. A read never
    refuses; a `decide` read of a type that asks for it carries `refusal` beside the values, for the
    company's tool.
    """

    as_of: datetime | None = None
    declared_gaps: list[str] = Field(default_factory=list)
    derived_status: Literal["current", "expired_by_input"] | None = None
    expired_by: list[str] = Field(default_factory=list, description="The inputs whose change expired it.")
    fields: dict[str, FieldState] = Field(default_factory=dict)
    latches: dict[str, datetime] = Field(default_factory=dict)
    outcome: OutcomeState | None = None
    prohibitions: list[str] = Field(default_factory=list)
    readings: dict[str, ReadingResult] = Field(default_factory=dict)
    ref: StateRef
    refetch: Refetch | None = None
    refusal: Refusal | None = None
    state: ShortStr | None = None
    timers: list[TimerState] = Field(default_factory=list)
    type_version: ShortStr | None = None
    values: dict[str, ValueState] = Field(default_factory=dict)
    withheld: dict[str, Literal["access", "licence", "scan"]] = Field(
        default_factory=dict, description="Fields left out for this reader, and why."
    )


class ObjectSnapshotRequest(Model):
    """Reconciliation from an NDJSON file uploaded through the file path that exists (`/v1/ingest`)."""

    type: TypeName
    upload_ref: IdStr


class ObjectSnapshotResponse(ResponseModel):
    import_id: IdStr


class RefreshRequest(ResponseModel):
    budget_units: int
    lease_until: datetime
    priority: Literal["high", "normal", "low"]
    reason: ShortStr
    ref: StateRef
    request_id: IdStr


class RefreshRequestPage(ResponseModel):
    items: list[RefreshRequest]


class SdkProfile(ResponseModel):
    """What the SDK keeps in its local cache: the features on, the source's tool bindings, the summarized type
    registry, the claim contract and turn recording.
    """

    claim_contract: ClaimContractSummary | None = None
    features: list[Feature]
    recording: dict[str, Any] | None = None
    tool_bindings: list[dict[str, Any]] = Field(default_factory=list)
    types: list[dict[str, Any]] = Field(default_factory=list)
    valid_for_s: int


class StateReadRequest(Model):
    fields: list[ShortStr] | None = None
    purpose: Literal["display", "claim", "decide"] = "display"
    readings: list[ShortStr] | None = None
    refs: list[StateRef] = Field(min_length=1, max_length=20)
    subject: Handle | None = None


class StateReadResponse(ResponseModel):
    degraded: bool = False
    objects: list[ObjectRead]


class VerifyCheck(Model):
    field: ShortStr
    ref: StateRef
    value: Any = None


class StateVerifyRequest(Model):
    checks: list[VerifyCheck] = Field(min_length=1, max_length=50)
    subject: Handle | None = None


class Verdict(ResponseModel):
    claim_safe: bool
    declared_gaps: list[str] = Field(default_factory=list)
    field: ShortStr
    matches: bool | None = None
    prohibitions: list[str] = Field(default_factory=list)
    ref: StateRef
    status: Literal["fresh", "stale", "expired"]


class StateVerifyResponse(ResponseModel):
    verdicts: list[Verdict]


class StateView(ResponseModel):
    changes_since_seen: list[dict[str, Any]] = Field(default_factory=list)
    degraded: bool = False
    interests: list[dict[str, Any]] = Field(default_factory=list)
    objects: list[dict[str, Any]] = Field(default_factory=list)


class StateViewRequest(Model):
    purpose: Literal["display", "claim", "decide"] = "display"
    subject: Handle


class TypeFingerprintRequest(Model):
    fingerprint: Annotated[str, StringConstraints(min_length=1, max_length=128)]
    type: TypeName


class TypeFingerprintResponse(ResponseModel):
    drift: bool
