# Generated by scripts/sync_spec.py from spec/openapi/cell.json. Do not edit.
"""Typed state: objects a system of record pushes, reads with a purpose, the agent's working state and the SDK
profile.
"""

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Any, Literal

from pydantic import Field, StringConstraints

from niadra.models._base import IdStr, Model, ResponseModel, ShortStr
from niadra.models.common import Handle

Sha256 = Annotated[str, StringConstraints(pattern=r"^sha256:[0-9a-f]{64}$")]
TypeName = Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9_]{0,39}$")]


class Actions(ResponseModel):
    """What happens to a claim that does not stand, by the task's context (an output kind or a document kind);
    `default` for any other. A context the contract lists as immutable is never rewritten.
    """

    contexts: dict[
        TypeName, Literal["block", "warn", "count", "rewrite_if_unequivocal", "discard_anchor_and_count"]
    ] = Field(default_factory=dict, max_length=32)
    default: Literal["block", "warn", "count", "rewrite_if_unequivocal", "discard_anchor_and_count"]
    replace_with: Annotated[str, StringConstraints(min_length=1, max_length=500)] | None = Field(
        default=None, description="The caveat a blocked passage gives way to, in a mutable output."
    )


class AgentState(ResponseModel):
    body: dict[str, Any] = Field(default_factory=dict)
    updated_at: datetime | None = None
    version: int


class AgentStateMeta(ResponseModel):
    """One working state of a customer, as the Console shows it: never its content."""

    agent: ShortStr
    bytes: int = Field(description="The size of the state's body.")
    schema_version: ShortStr | None = None
    scope_kind: Literal["conversation", "task", "object", "subject"]
    source_id: IdStr
    updated_at: datetime
    valid_until: datetime
    version: int


class AgentStateMetaPage(ResponseModel):
    items: list[AgentStateMeta]


class AgentStateScope(Model):
    """What one working state belongs to. The id travels in the body, never in a URL: a conversation id may
    look like a phone number.
    """

    id: IdStr
    kind: Literal["conversation", "task", "object", "subject"]


class AgentStateReadRequest(Model):
    agent: ShortStr
    scope: AgentStateScope


class AgentStateWrite(Model):
    """A write of an agent's working state, by its code and never by a model: `cas` replaces the whole state
    at `if_version` (0 when it must not exist yet); `merge_by_key` replaces each top-level field it names
    and removes a field written as exactly `{"$delete": true}`.
    """

    agent: ShortStr
    body: dict[str, Any]
    if_version: Annotated[int, Field(ge=0)] | None = None
    mode: Literal["cas", "merge_by_key"]
    scope: AgentStateScope
    subject: Handle | None = Field(
        default=None,
        description=(
            "The customer the state is about, when its scope does not name them: erasing the customer "
            "and their data package find the state by it."
        ),
    )


class AgentStateWriteResult(ResponseModel):
    reason: Literal["over_cap", "not_declared_field"] | None = None
    stored: bool
    version: int


class AnchorEvidence(ResponseModel):
    coverage: Literal["fact", "law"] = Field(description="Counted apart: law and fact never add up.")
    min_match: float = Field(default=0.9, ge=0.9, le=1.0)


class Negation(ResponseModel):
    param: Annotated[str, StringConstraints(pattern=r"^[A-Za-z_][A-Za-z0-9_.-]{0,63}$")] = Field(
        description="The argument that takes the values the field must not have."
    )


class BoundArg(ResponseModel):
    """One argument of the tool and the field it carries. `in` and `eq` render to `param`, `not_in` and `ne`
    to the negation's, and a comparison or `between` only when `ops` lists it.
    """

    attr: Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9_]{0,39}\.[a-z][a-z0-9_]{0,63}$")] = Field(
        description="The field, as `type.field`."
    )
    negation: Negation | None = None
    ops: list[Literal["in", "not_in", "eq", "ne", "lt", "lte", "gt", "gte", "between"]] = Field(
        default_factory=list, max_length=9
    )
    param: Annotated[str, StringConstraints(pattern=r"^[A-Za-z_][A-Za-z0-9_.-]{0,63}$")]
    transform: Literal["lower", "upper"] | None = Field(default=None, description="The case text is sent in.")


class StateRef(Model):
    """An object of the type registry: a subject's or a shared one, whose key may name a variant."""

    id: IdStr
    namespace: ShortStr
    type: ShortStr
    variant: ShortStr | None = None


class ChangeSinceSeen(ResponseModel):
    """A field of an interest whose value is not the one the subject was shown."""

    field: ShortStr
    now: Any = None
    observed_at: datetime | None = Field(
        default=None, description="When the source observed the value now held."
    )
    ref: StateRef
    seen: Any = None


class ValueEvidence(ResponseModel):
    """A value in the turn record, from a tool's result or from state, that the number is checked against."""

    fresh_for: Literal["claim"] | None = Field(
        default=None, description="The value is within its type's `claim_max_age`, or the claim is `stale`."
    )
    gap_terms: dict[TypeName, list[Annotated[str, StringConstraints(min_length=1, max_length=80)]]] = Field(
        default_factory=dict,
        max_length=32,
        description="The words that state each declared gap; a gap without them is stated by its name.",
    )
    must_state_gaps: bool = Field(
        default=False, description="The value's declared gaps must be said with it, or `gap_not_stated`."
    )
    same_role: bool = Field(default=False, description="The value's role is the number's role.")
    type: TypeName | None = None
    value: TypeName | None = Field(default=None, description="A field or a computed value of `type`.")


class ClaimEvidence(ResponseModel):
    """What the turn record must hold for a claim of the category to stand: exactly one kind."""

    anchor: AnchorEvidence | None = None
    tool: Annotated[str, StringConstraints(pattern=r"^[A-Za-z][A-Za-z0-9_.:-]{0,63}$")] | None = Field(
        default=None, description="A call of this tool in the turn."
    )
    tool_any: list[Annotated[str, StringConstraints(pattern=r"^[A-Za-z][A-Za-z0-9_.:-]{0,63}$")]] = Field(
        default_factory=list, max_length=20
    )
    value: ValueEvidence | None = None


class Detect(ResponseModel):
    """How a category finds its claims in the text, without a model: numbers of these classes, the words
    around them that give their role, terms of the trade, named patterns, or sections of a document.
    """

    classes: list[Literal["money", "percent", "date", "duration", "quantity", "count", "dosage"]] = Field(
        default_factory=list, max_length=7
    )
    document_sections: list[TypeName] = Field(default_factory=list, max_length=20)
    patterns: list[Literal["article_citation", "precedent_citation"]] = Field(default_factory=list)
    roles: dict[TypeName, list[Annotated[str, StringConstraints(min_length=1, max_length=80)]]] = Field(
        default_factory=dict,
        max_length=32,
        description="The words that give a number its role, synonyms and every language in one list.",
    )
    terms: list[Annotated[str, StringConstraints(min_length=1, max_length=80)]] = Field(
        default_factory=list,
        max_length=100,
        description=(
            "With `classes`, a number counts only in a sentence that holds one of them; alone, the term"
            " is the claim."
        ),
    )


class Natures(ResponseModel):
    """How a number is handled by where it came from: computed (a value with provenance in the turn, by rule
    or observed) is checked against it; quoted (inside quotation marks) is checked only for being in a
    source, as written, even when it is false; said by the model (no origin) takes this action, or the
    category's.
    """

    computed: Literal["check", "count"] = "check"
    model: Literal["block", "warn", "count"] | None = None
    quoted: Literal["verbatim", "count"] = "verbatim"


class ClaimCategory(ResponseModel):
    actions: Actions
    agents: list[ShortStr] = Field(default_factory=list, max_length=50, description="Empty: every agent.")
    detect: Detect
    evidence: ClaimEvidence
    id: TypeName
    natures: Natures = Field(default_factory=Natures)


class ClaimOutputs(ResponseModel):
    immutable: list[TypeName] = Field(default_factory=list, max_length=32)
    mutable: list[TypeName] = Field(default_factory=list, max_length=32)


class InternalText(ResponseModel):
    """Fingerprints of the company's own prompt: hashes of every `n` words, computed by the SDK, never the
    prompt itself. An output that repeats one gives way to `redact`, recorded as a claim of the category
    `internal_text` with the verdict `internal_text_found`, the action taken and, as evidence, the
    `shingle_hashes_ref` in `document`.
    """

    n: int = Field(default=8, ge=4, le=32)
    redact: Annotated[str, StringConstraints(min_length=1, max_length=200)]
    shingle_hashes_ref: ShortStr = Field(description="The prompt version the hashes were computed from.")


class ClaimContractSummary(ResponseModel):
    """The contract as the SDK keeps it: everything but the negative corpus's phrases, which only the CI's
    `niadra contract test` reads, from the company's own copy.
    """

    categories: list[ClaimCategory] = Field(default_factory=list)
    internal_text: InternalText | None = None
    languages: list[Literal["pt", "en", "es"]]
    negative_corpus_version: ShortStr | None = None
    outputs: ClaimOutputs = Field(default_factory=ClaimOutputs)
    version: ShortStr


class ContentMarker(ResponseModel):
    """A content field whose text Niadra does not hold (`pointer`, `hash_only`), or holds under scan."""

    mode: Literal["full", "pointer", "hash_only"]
    pointer: IdStr | None = Field(
        default=None, description="Where the SDK reads the text inside the company's boundary."
    )
    scan: Literal["pending", "clean", "flagged"]
    sha256: Annotated[str, StringConstraints(pattern=r"^[0-9a-f]{64}$")] | None = None


class ContentRelease(Model):
    reason: Annotated[str, StringConstraints(min_length=1, max_length=500)]


class ContentReleaseResult(ResponseModel):
    released: bool


class DerivedState(ResponseModel):
    """A field the type derives from the related objects of one relation (a look's pieces), computed at this
    read and never stored. A related object whose data is not known leaves it `unobserved`, unless the
    answer is already decided.
    """

    logic: Literal["yes", "no", "unobserved"]
    over: int = Field(ge=0, description="The related objects it was computed over.")
    unknown: int = Field(
        ge=0,
        description=(
            "How many of them were not known: out of the working set, not an exact match "
            "(`status_field`), or with the data the condition reads not observed."
        ),
    )
    v: Any = None


class DriftChanges(Model):
    """What changed between the declaration and the type the schema proposes now, as counts: never a new name,
    a value or a definition (object-type spec, 8.8.2).
    """

    fields: list[Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9_]{0,63}$")]] = Field(
        default_factory=list,
        max_length=50,
        description=(
            "The declaration's fields removed or retyped, and its state field when the states differ."
        ),
    )
    fields_added: int = Field(ge=0)
    fields_removed: int = Field(ge=0)
    fields_retyped: int = Field(ge=0)
    key_changed: bool
    relations_added: int = Field(ge=0)
    relations_removed: int = Field(ge=0)
    states_added: int = Field(ge=0)
    states_removed: int = Field(ge=0)


Feature = Literal[
    "turns",
    "state",
    "agent_state",
    "signals",
    "claims",
    "coordination",
    "measurement",
    "notifications",
    "legal_holds",
]
"""The agent features a space turns on: everything is off until the space's `features` document lists it, and
`GET /v1/sdk/profile` announces what is on.
"""


class FieldCoverage(ResponseModel):
    age_p50_s: int | None = Field(
        default=None, description="The median age, in seconds, of the field's newest observation."
    )
    coverage: float = Field(
        ge=0.0, le=1.0, description="The share of the type's objects some source observed the field of."
    )
    field: ShortStr


class PreviousValue(ResponseModel):
    """A field's value before its latest change, kept for the fields that declare `track_changes`."""

    logic: Literal["yes", "no", "unobserved", "known_defect"]
    v: Any = None


class FieldState(ResponseModel):
    """One field as a read serves it: the value with its logical value, stamps, source and observer, and the
    freshness computed now against the type's current rule.
    """

    age_s: int | None = Field(default=None, description="Seconds since `observed_at`.")
    claim_safe: bool
    completeness: ShortStr | None = None
    content: ContentMarker | None = None
    known_at: datetime | None = Field(default=None, description="When Niadra first knew it; never moves.")
    logic: Literal["yes", "no", "unobserved", "known_defect"]
    masked: bool = Field(default=False, description="The reader's access masks the value: `v` is absent.")
    observed_at: datetime | None = Field(default=None, description="When the source observed the value.")
    observer: ShortStr | None = None
    role: ShortStr | None = None
    src: ShortStr | None = None
    status: Literal["fresh", "stale", "expired"]
    v: Any = None
    valid_at: datetime | None = None
    was: PreviousValue | None = None


class OutcomeState(ResponseModel):
    at: datetime | None = None
    final: bool
    state: ShortStr = Field(description="A canonical state of the type, or `expired_without_outcome`.")


class ReadingResult(ResponseModel):
    """A named reading's value, as niadra-expr computes it: the logical value, and the kind and value when
    known (dates as `YYYY-MM-DD`, times in UTC, durations in milliseconds).
    """

    absent: ShortStr | None = None
    inputs: dict[str, str] | None = Field(
        default=None,
        description=(
            "For a reading that includes its inputs: the derived object's inputs, by the name its type "
            "gives them, as `type:namespace:id`."
        ),
    )
    logic: Literal["yes", "no", "unobserved", "known_defect"]
    type: Literal["bool", "number", "string", "duration", "date", "datetime", "list"] | None = None
    v: Any = None


class Refetch(ResponseModel):
    admitted: bool
    priority: Literal["high", "normal", "low"]
    reason: ShortStr


class Refusal(ResponseModel):
    action: ShortStr | None = None
    reason: ShortStr


class TimerState(ResponseModel):
    due_at: datetime | None = Field(default=None, description="Computed now from the rule and the values.")
    fired_at: datetime | None = None
    name: ShortStr
    state: Literal["armed", "fired", "cancelled"]
    supersedes_firing_id: IdStr | None = Field(
        default=None,
        description=(
            "The firing this one replaces: a timer that already fired fires again once the value that "
            "armed it is revised."
        ),
    )


class ValueState(ResponseModel):
    """A value the company computed, kept as a versioned fact with the rule that produced it."""

    absent_as: ShortStr | None = Field(default=None, description="The name of the absence, when absent.")
    claim_safe: bool
    computed_at: datetime
    declared_gaps: list[str] = Field(default_factory=list)
    gap_effect: Literal["errs_early", "errs_late", "unknown"] = "unknown"
    logic: Literal["yes", "no", "unobserved", "known_defect"]
    rule: ShortStr
    status: Literal["fresh", "stale", "expired"]
    supersedes_version: int | None = None
    v: Any = None
    version: int = Field(ge=1)


class ObjectRead(ResponseModel):
    """One object as a state read serves it: fields with four logical values and their stamps, computed
    values, lifecycle, timers and readings, and what may not be claimed with data this old. A read never
    refuses; a `decide` read of a type that asks for it carries `refusal` beside the values, for the
    company's tool.
    """

    as_of: datetime | None = None
    axes: dict[str, str] = Field(
        default_factory=dict,
        description=(
            "Each time axis of the type whose value is known: a date as `YYYY-MM-DD`, an instant in "
            "UTC. The platform keeps `known_at` (when the producer first knew of the object) and the "
            "time its content last changed."
        ),
    )
    blocked: dict[ShortStr, list[str]] = Field(
        default_factory=dict,
        description=(
            "What the fields whose value is not known block, as the type declares it "
            "(`unobserved_blocks`): each activity (`model_read`, `derive`, `claim`, or a task of the "
            "company such as `decide:close`) with the fields that block it. Nothing else is blocked."
        ),
    )
    declared_gaps: list[str] = Field(default_factory=list)
    derived: dict[str, DerivedState] = Field(
        default_factory=dict, description="The type's derived fields, from the related objects."
    )
    derived_status: Literal["current", "expired_by_input"] | None = None
    expired_by: list[str] = Field(default_factory=list, description="The inputs whose change expired it.")
    fields: dict[str, FieldState] = Field(default_factory=dict)
    latches: dict[str, datetime] = Field(default_factory=dict)
    outcome: OutcomeState | None = None
    prohibitions: list[str] = Field(default_factory=list)
    readings: dict[str, ReadingResult] = Field(default_factory=dict)
    ref: StateRef
    refetch: Refetch | None = None
    refusal: Refusal | None = None
    state: ShortStr | None = None
    timers: list[TimerState] = Field(default_factory=list)
    type_version: ShortStr | None = None
    values: dict[str, ValueState] = Field(default_factory=dict)
    withheld: dict[str, Literal["access", "licence", "scan"]] = Field(
        default_factory=dict, description="Fields left out for this reader, and why."
    )


class InterestState(ResponseModel):
    """A shared object the subject showed interest in, as it stands now."""

    at: datetime
    object: ObjectRead | None = Field(
        default=None,
        description="The object as a `display` read serves it; absent once it left the working set.",
    )
    reason: ShortStr = Field(description="`presented`, `engaged`, `feedback` or `watch`.")
    ref: StateRef


class TypeCoverage(ResponseModel):
    fields: list[FieldCoverage]
    objects: int = Field(description="The objects measured: the ones of the type that changed last.")
    type: TypeName


class ObjectCoverage(ResponseModel):
    """How much of each declared field the objects of each type carry, and how old it is, from the stamps
    alone: never a value.
    """

    types: list[TypeCoverage]


class Provenance(Model):
    """Where pushed values come from: only a `live` source sustains a claim, and the age of every value counts
    from `source_observed_at`.
    """

    scope: Literal["global", "customer", "context"] = "global"
    source: Literal["live", "snapshot", "cache"]
    source_observed_at: datetime


class ObjectPush(Model):
    fields: dict[str, Any] = Field(max_length=200)
    inputs: Annotated[dict[ShortStr, ShortStr], Field(max_length=20)] | None = Field(
        default=None,
        description=(
            "For a derived object (a customer's quote, a shared best offer): the objects its inputs are"
            ' fields of, by the name its type gives them, as `type:namespace:id` (`{"lead": '
            '"lead:crm:L-9"}`). When a field of one of them changes, the object expires, naming the '
            "input. A shared object's inputs are shared objects: a customer's object is never one."
        ),
    )
    provenance: Provenance
    ref: StateRef
    request_id: IdStr | None = Field(
        default=None,
        description=(
            "The refresh request this item answers, from the resolver worker's lease: the request is "
            "settled, and a `watch_revalidation` is decided on these values even when they are not "
            "newer than the ones held."
        ),
    )
    version: int = Field(
        ge=0,
        le=9007199254740991,
        description=(
            "The source's version of the object. A field moves only when this is greater than the "
            "version that last wrote it; a source never reuses a version for other content."
        ),
    )


class ObjectPushRequest(Model):
    objects: list[ObjectPush] = Field(min_length=1, max_length=1000)


class ObjectPushResponse(ResponseModel):
    """How many items of the request each decision took, against the hot layer, with no database statement.

    A shared object's item is `applied` when at least one of its fields moved forward: reads serve it at
    once, and the consolidator writes it within a second with the same per-field rule, so the stored object
    never disagrees with the answer. `stale_version`: every field was already written by this version or a
    greater one, as a retried request finds. `out_of_set`: the object is not in the working set, and
    nothing is kept. A subject's object is `recorded`: accepted as a system event about it, in the
    request's one statement, and its fields move by the same rule when the event is applied.
    """

    applied: int
    out_of_set: int
    recorded: int = 0
    stale_version: int


class ObjectSnapshotResponse(ResponseModel):
    """A snapshot taken in: its lines are applied as pushes of provenance `snapshot`, which never sustain a
    claim, by the same version rule.
    """

    import_id: IdStr
    objects: int = Field(description="The lines taken in.")


class RefreshRelease(Model):
    """A leased request the resolver worker cannot answer: the object is not at the source, or fetching it
    failed. The request leaves at once and its paid call counts; a `watch_revalidation` falls back to the
    type's `unconfirmed_watch`.
    """

    outcome: Literal["not_found", "failed"]


class RefreshReleased(ResponseModel):
    reason: ShortStr
    request_id: IdStr


class RefreshRequest(ResponseModel):
    budget_units: int
    lease_until: datetime
    priority: Literal["high", "normal", "low"]
    reason: ShortStr
    ref: StateRef
    request_id: IdStr


class RefreshRequestPage(ResponseModel):
    items: list[RefreshRequest]


class ResultObjects(ResponseModel):
    """Where a result carries objects of a type, and which key of each item holds which field."""

    fields: dict[
        Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9_]{0,63}$")],
        Annotated[str, StringConstraints(pattern=r"^[A-Za-z_][A-Za-z0-9_-]{0,63}$")],
    ] = Field(default_factory=dict, max_length=100)
    id: Annotated[str, StringConstraints(pattern=r"^[A-Za-z_][A-Za-z0-9_-]{0,63}$")] = Field(
        default="id", description="The key of the item that holds the object's id."
    )
    namespace: Annotated[str, StringConstraints(pattern=r"^[A-Za-z0-9][A-Za-z0-9_.-]{0,63}$")]
    path: Annotated[
        str, StringConstraints(max_length=256, pattern=r"^\$?(\.?[A-Za-z_][A-Za-z0-9_-]*(\[\*\])?)*$")
    ] = "$"
    type: TypeName


class ToolCapabilities(ResponseModel):
    dry_run_param: Annotated[str, StringConstraints(pattern=r"^[A-Za-z_][A-Za-z0-9_.-]{0,63}$")] | None = (
        Field(
            default=None, description="The argument that makes a call change nothing, for a counterfactual."
        )
    )
    mask_output: bool = Field(
        default=False, description="The SDK masks the fields the key may not read in the tool's output."
    )
    overfetch: bool = Field(
        default=False, description="The tool returns more than asked: the SDK filters the residual from it."
    )
    relax_flag: (
        Annotated[
            str, StringConstraints(max_length=256, pattern=r"^\$?(\.?[A-Za-z_][A-Za-z0-9_-]*(\[\*\])?)*$")
        ]
        | None
    ) = Field(default=None, description="Where the result says the tool relaxed what it was asked.")


class ToolBinding(ResponseModel):
    args: list[BoundArg] = Field(default_factory=list, max_length=50)
    capabilities: ToolCapabilities = Field(default_factory=ToolCapabilities)
    results: list[ResultObjects] = Field(default_factory=list, max_length=10)
    tool: Annotated[str, StringConstraints(pattern=r"^[A-Za-z0-9_][A-Za-z0-9_.:/-]{0,63}$")]


class TurnRecordingSummary(ResponseModel):
    """How the calling source records turns, for the SDK's capture: where the values may live, and the pins a
    turn needs to be replayable.
    """

    content_mode: Literal["stored", "pointer", "hash_only"] = Field(
        description="`stored`, `pointer` or `hash_only`; a turn may keep less, never more."
    )
    required_pins: list[Literal["prompts", "corpus_digest", "model", "assembler", "tool_schemas"]] = Field(
        description="Without one of these, a turn is kept not replayable."
    )


class SdkProfile(ResponseModel):
    """What the SDK keeps in its local cache: the features on, the source's tool bindings, the summarized type
    registry, the claim contract and turn recording.
    """

    claim_contract: ClaimContractSummary | None = None
    features: list[Feature]
    recording: TurnRecordingSummary | None = Field(
        default=None, description="How this source records turns, once the space records them."
    )
    tool_bindings: list[ToolBinding] = Field(
        default_factory=list, description="The bindings of the tools this source's agents call."
    )
    types: list[dict[str, Any]] = Field(default_factory=list)
    valid_for_s: int


class StateReadRequest(Model):
    fields: list[ShortStr] | None = None
    purpose: Literal["display", "claim", "decide"] = "display"
    readings: list[ShortStr] | None = None
    refs: list[StateRef] = Field(min_length=1, max_length=20)
    subject: Handle | None = None


class StateReadResponse(ResponseModel):
    degraded: bool = False
    objects: list[ObjectRead]


class VerifyCheck(Model):
    field: ShortStr
    ref: StateRef
    value: Any = None


class StateVerifyRequest(Model):
    checks: list[VerifyCheck] = Field(min_length=1, max_length=50)
    subject: Handle | None = None


class Verdict(ResponseModel):
    claim_safe: bool
    declared_gaps: list[str] = Field(default_factory=list)
    field: ShortStr
    matches: bool | None = None
    prohibitions: list[str] = Field(default_factory=list)
    ref: StateRef
    status: Literal["fresh", "stale", "expired"]


class StateVerifyResponse(ResponseModel):
    verdicts: list[Verdict]


class StateView(ResponseModel):
    """The state of one subject (the `now` view): their objects of the declared types, each as a `display`
    read serves it; the shared objects they showed interest in, and what changed since they saw them; and
    the same as short lines for the turn block.
    """

    changes_since_seen: list[ChangeSinceSeen] = Field(default_factory=list)
    degraded: bool = False
    interests: list[InterestState] = Field(default_factory=list)
    objects: list[ObjectRead] = Field(default_factory=list)
    text: str | None = Field(
        default=None,
        description=(
            "The view as lines for the turn block, after `slots`: never part of the pack's `text`, so "
            "the cached prefix keeps its bytes. Absent when there is nothing to say."
        ),
    )


class StateViewRequest(Model):
    purpose: Literal["display", "claim", "decide"] = "display"
    subject: Handle


class TypeFingerprintRequest(Model):
    """A deriving tool's check of a declared type: the fingerprint of the schema it read now."""

    changes: DriftChanges | None = None
    fingerprint: Sha256
    type: TypeName


class TypeFingerprintResponse(ResponseModel):
    drift: bool = Field(description="Whether the fingerprint differs from the declaration's.")
    issue_id: IdStr | None = Field(
        default=None,
        description="The data issue of kind `drift` the check opened or counted in, when the type alerts.",
    )
