# Generated by scripts/sync_spec.py from spec/openapi/cell.json. Do not edit.
"""Turn records, replay, scenarios, the change log, data issues and the notification feed."""

from __future__ import annotations

from datetime import date, datetime
from typing import Annotated, Any, Literal
from uuid import UUID

from pydantic import Field, StringConstraints

from niadra.models._base import IdStr, Model, ResponseModel, ShortStr
from niadra.models.events import ItemError

BlobKey = Annotated[str, StringConstraints(pattern=r"^[a-z]{1,8}:[A-Za-z0-9_-]{1,32}$")]
ObjectKey = Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9_]{0,39}:[^:\s]{1,256}:\S{1,512}$")]
Sha256 = Annotated[str, StringConstraints(pattern=r"^sha256:[0-9a-f]{64}$")]
TurnId = Annotated[str, StringConstraints(pattern=r"^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$")]
TypeName = Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9_]{0,39}$")]
Version = Annotated[str, StringConstraints(min_length=1, max_length=128)]


class AssertionOutcome(Model):
    detail: Annotated[str, StringConstraints(max_length=500)] | None = None
    id: Annotated[str, StringConstraints(pattern=r"^[a-z0-9][a-z0-9_.-]{0,63}$")]
    kind: Literal[
        "tool_called",
        "tool_not_called",
        "hard_respected",
        "no_denial_with_results",
        "claims_traced",
        "claims_match_state",
        "no_promise_without_action",
        "expected_in_topk",
        "handoff_when",
        "effect_once",
        "budget",
        "lexicon",
        "tools_offered_match",
    ]
    outcome: Literal["pass", "fail", "not_checked"]


class AssertionStats(ResponseModel):
    """One assertion over the run's completed executions, against its baseline. `p_value` is the one-sided
    Fisher exact test that the run passes less often than the baseline, rounded to 6 decimals.
    """

    baseline_failed: int
    baseline_passed: int
    drop: float = Field(description="The baseline's pass rate minus the run's.")
    failed: int
    flaky: bool
    id: Annotated[str, StringConstraints(pattern=r"^[a-z0-9][a-z0-9_.-]{0,63}$")]
    not_checked: int
    p_value: float
    passed: int
    regression: bool


class Attribute(Model):
    """What the person is: a size, a preferred network, a diet. Said here; the lifecycle's outcomes (bought,
    kept, returned for size) derive the rest on the server, never an agent.
    """

    category: ShortStr | None = None
    for_: Annotated[str, StringConstraints(pattern=r"^(?:self|gift|beneficiary:[A-Za-z0-9_-]{1,64})$")] = (
        Field(default="self", alias="for")
    )
    kind: Literal["attribute"]
    name: Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9_]{0,63}(?:\.[a-z0-9_]{1,64}){0,3}$")]
    source: Literal["stated", "correction"] = "stated"
    system: ShortStr | None = Field(default=None, description="The measuring system: `BR`, `EU`, `US`.")
    value: bool | int | float | Annotated[str, StringConstraints(max_length=256)]


class Change(ResponseModel):
    """One entry of the change log a bisection walks: a pin that changed between two builds of an agent, or a
    section of the space's configuration that changed between two applied snapshots (`config`, named by the
    section, with no agent: every agent reads it, and its digests stand for the values).
    """

    after: str | None = None
    agent: ShortStr | None = None
    at: datetime
    before: str | None = None
    kind: Literal["prompt", "model", "code", "data", "config", "compiler"]
    name: ShortStr | None = Field(default=None, description="The prompt or the tool, for those kinds.")


class ChangePage(ResponseModel):
    items: list[Change]
    next_cursor: str | None = None


class ClaimEvidenceRef(Model):
    """Where a claim's evidence is in the turn record: a call's field, an object's field, or a document."""

    anchor: IdStr | None = Field(default=None, description="The blob that keeps the quoted text.")
    call_id: IdStr | None = None
    document: IdStr | None = Field(default=None, description="The document an anchor cites.")
    field: TypeName | None = None
    ref: IdStr | None = Field(default=None, description="An object, `type:namespace:id`.")
    score: Annotated[float, Field(ge=0.0, le=1.0)] | None = Field(
        default=None, description="The anchor's similarity."
    )


class ClaimValue(Model):
    """A number the parser read, normalized: an amount, or a range from `min` to `max`, with its unit (the
    currency code of money, `%`, a time unit, a unit of measure or of dose), or a date, or a range of
    dates.
    """

    amount: (
        Annotated[str, StringConstraints(pattern=r"^-?(?:0|[1-9][0-9]{0,17})(?:\.[0-9]{1,6})?$")] | None
    ) = None
    date: (
        Annotated[
            str,
            StringConstraints(
                pattern=r"^(?:[0-9]{4}-[0-9]{2}(?:-[0-9]{2})?|--[0-9]{2}-[0-9]{2}|---[0-9]{2})$"
            ),
        ]
        | None
    ) = None
    date_from: (
        Annotated[
            str,
            StringConstraints(
                pattern=r"^(?:[0-9]{4}-[0-9]{2}(?:-[0-9]{2})?|--[0-9]{2}-[0-9]{2}|---[0-9]{2})$"
            ),
        ]
        | None
    ) = None
    date_to: (
        Annotated[
            str,
            StringConstraints(
                pattern=r"^(?:[0-9]{4}-[0-9]{2}(?:-[0-9]{2})?|--[0-9]{2}-[0-9]{2}|---[0-9]{2})$"
            ),
        ]
        | None
    ) = None
    max: Annotated[str, StringConstraints(pattern=r"^-?(?:0|[1-9][0-9]{0,17})(?:\.[0-9]{1,6})?$")] | None = (
        None
    )
    min: Annotated[str, StringConstraints(pattern=r"^-?(?:0|[1-9][0-9]{0,17})(?:\.[0-9]{1,6})?$")] | None = (
        None
    )
    unit: Annotated[str, StringConstraints(min_length=1, max_length=16)] | None = None


class ClaimRecord(Model):
    """One claim the SDK found in an output, as the turn record carries it: kinds, spans and verdicts."""

    action: Literal["none", "block", "warn", "count", "rewrite", "discard_anchor"] = Field(
        description=(
            "What was done, which the contract's configured action decides: `rewrite_if_unequivocal` is"
            " `rewrite` when the rewrite is unequivocal and `warn` otherwise, "
            "`discard_anchor_and_count` is `discard_anchor`, and a claim that stands (`matched`, "
            "`quoted_found`, `anchored`) is `none`."
        )
    )
    category: TypeName
    class_: Literal["money", "percent", "date", "duration", "quantity", "count", "dosage"] | None = Field(
        default=None, alias="class"
    )
    evidence: ClaimEvidenceRef | None = None
    nature: Literal["computed", "quoted", "model"] | None = None
    role: TypeName | None = None
    span: tuple[int, int] = Field(description="Code point offsets of the claim in the output, end exclusive.")
    value: ClaimValue | None = None
    verdict: Literal[
        "matched",
        "mismatch",
        "stale",
        "gap_not_stated",
        "role_ambiguous",
        "unsupported",
        "no_evidence",
        "quoted_found",
        "quoted_missing",
        "anchored",
        "below_threshold",
        "source_exists_claim_unverified",
        "source_missing",
        "not_checked",
        "internal_text_found",
    ]


class DataIssue(ResponseModel):
    """A problem in the company's data, returned to its owner with no personal data: one open issue per class,
    type, field and source, counted each time it is found again.
    """

    acknowledged_at: datetime | None = Field(
        default=None, description="Once acknowledged, the next occurrence opens a new issue."
    )
    field: ShortStr | None = None
    issue_id: IdStr
    kind: Literal[
        "null_field",
        "out_of_vocabulary",
        "stale_source",
        "coverage_drop",
        "invalid_value",
        "divergence",
        "drift",
        "rule_conflict",
        "type_undeclared",
        "field_held",
        "budget_reached",
        "row_failed",
        "inference_limit",
    ] = Field(
        description=(
            "`null_field`, `out_of_vocabulary`, `stale_source`, `invalid_value`: a value an agent's "
            "tool showed; `coverage_drop`: a field filled less often than before; `divergence`: two "
            "sources of one value disagree; `drift`: the schema a type mirrors changed, and a new field"
            " is already served to agents as it came (a note, nothing to fix); `field_held`: a new "
            "field that may be personal data or free text, held from agents until the type declares it;"
            " `row_failed`: a row that failed every attempt to be taken in is kept aside, sealed, never"
            " deleted, until an admin retries it (`POST /v1/intake/failed/retry`), `source` naming "
            "where it came from; `rule_conflict`: two rules decide one thing differently; "
            "`type_undeclared`: tools showed objects of a type the space never declared; "
            "`budget_reached`: the space spent its day's AI ceiling for a purpose (`source`), and "
            "memory waits for the next UTC day; `inference_limit`: what the space's systems send passed"
            " a limit of what Niadra infers on its own (types, fields or states of a type, operations),"
            " or a name was not safe to use; what passed it is still stored and served as it came, and "
            "`field` names the limit."
        )
    )
    last_seen_at: datetime
    object_type: ShortStr | None = None
    occurrences: int
    opened_at: datetime
    refs: list[ObjectKey] = Field(
        default_factory=list, max_length=50, description="The first objects it was seen on, up to 50."
    )
    source: ShortStr | None = Field(
        default=None, description="Where the data came from: a tool or a system of record."
    )


class DataIssuePage(ResponseModel):
    items: list[DataIssue]
    next_cursor: str | None = None


class Engaged(Model):
    exposure_id: UUID | None = Field(default=None, description="Absent for an item of no list.")
    for_: Annotated[str, StringConstraints(pattern=r"^(?:self|gift|beneficiary:[A-Za-z0-9_-]{1,64})$")] = (
        Field(default="self", alias="for")
    )
    how: Literal["click", "detail", "mention", "add_to_cart", "compare", "share", "other"]
    kind: Literal["engaged"]
    ref: ObjectKey


class FailedIntake(ResponseModel):
    """A batch of the company's data that failed every attempt to be taken in: kept aside, sealed as it came,
    never deleted, until an admin retries it. What kind of batch, from which source and when; never its
    content.
    """

    attempts: int = Field(ge=0)
    failed_at: datetime
    intake_id: UUID
    kind: Literal["events", "turns"] = Field(
        description="`events` for `POST /v1/events` and the webhooks, `turns` for `POST /v1/turns`."
    )
    received_at: datetime
    source_id: UUID


class FailedIntakePage(ResponseModel):
    items: list[FailedIntake] = Field(description="Oldest first, up to 500 of each kind.")
    kept: int = Field(
        ge=0,
        description=(
            "Every batch kept aside, listed or not; past the listing, `POST /v1/intake/failed/retry` "
            "with no ids retries all of them."
        ),
    )


class FailedIntakeRetried(ResponseModel):
    retried: int = Field(ge=0, description="Batches put back in the space's order for a worker to store.")


class FailedIntakeRetry(Model):
    intake_ids: Annotated[list[UUID], Field(max_length=500)] | None = Field(
        default=None, description="The batches to retry; none retries every kept batch."
    )


class Feedback(Model):
    for_: Annotated[str, StringConstraints(pattern=r"^(?:self|gift|beneficiary:[A-Za-z0-9_-]{1,64})$")] = (
        Field(default="self", alias="for")
    )
    kind: Literal["feedback"]
    polarity: Literal["positive", "negative"]
    reason_attrs: list[
        Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9_]{0,39}\.[a-z][a-z0-9_]{0,63}$")]
    ] = Field(default_factory=list, max_length=10)
    ref: ObjectKey


class Notification(ResponseModel):
    """A webhook's body, for the company that pulls instead of receiving it: the same fields, ids and pointers
    only. An event aimed at one endpoint, or about a memory item only some sources may read, reaches its
    webhooks only.
    """

    created_at: datetime
    data: dict[str, Any]
    id: IdStr = Field(description="The event's id; a webhook delivery of the same event has its own.")
    links: dict[str, str] = Field(default_factory=dict)
    subject: dict[str, Any] | None = None
    tenant: IdStr
    type: ShortStr


class NotificationPage(ResponseModel):
    """Oldest first. `next_cursor` is where the next poll starts: the same cursor when nothing is new."""

    items: list[Notification]
    next_cursor: str


class Preference(Model):
    """What the person wants or refuses, said or captured from a tool's arguments; only these become hard."""

    attr: Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9_]{0,39}\.[a-z][a-z0-9_]{0,63}$")]
    category: ShortStr | None = Field(default=None, description="Holds only in this category of the type.")
    expires_at: datetime | None = None
    for_: Annotated[str, StringConstraints(pattern=r"^(?:self|gift|beneficiary:[A-Za-z0-9_-]{1,64})$")] = (
        Field(default="self", alias="for")
    )
    kind: Literal["preference"]
    op: Literal["in", "not_in", "eq", "ne", "lt", "lte", "gt", "gte", "between"]
    scope: Literal["turn", "session", "persistent"] = "session"
    source: Literal["stated", "tool_args", "correction"] = "stated"
    strength: Literal["must", "must_not", "prefer", "avoid"]
    values: list[bool | int | float | Annotated[str, StringConstraints(max_length=256)]] = Field(
        min_length=1, max_length=50
    )


class PresentedItem(Model):
    pos: int = Field(ge=1, le=10000, description="1-based position in the whole list, across pages.")
    ref: ObjectKey
    shown: dict[
        Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9_]{0,63}$")],
        bool | int | float | Annotated[str, StringConstraints(max_length=256)] | None,
    ] = Field(
        default_factory=dict,
        max_length=32,
        description=(
            "The values the item showed, for the fields its type tracks or lets be claimed; what "
            "`changes_since_seen` later compares against."
        ),
    )
    team: Literal["a", "b"] | None = Field(
        default=None, description="Which of two interleaved lists contributed the item."
    )


class Presented(Model):
    """A list delivered to the person: the exposure. Its canonical moment is `delivered_at`, when the
    interface bridge handed the list to the client, never when a tool returned it or the model named it.
    """

    delivered_at: datetime
    exposure_id: UUID
    for_: Annotated[str, StringConstraints(pattern=r"^(?:self|gift|beneficiary:[A-Za-z0-9_-]{1,64})$")] = (
        Field(default="self", alias="for")
    )
    items: list[PresentedItem] = Field(min_length=1, max_length=100)
    kind: Literal["presented"]
    list_id: ShortStr
    list_kind: ShortStr = "results"
    method: Literal["bridge", "otel", "tool_result"] = Field(
        default="bridge",
        description=(
            "`bridge` from the interface bridge, `otel` from a `niadra.exposure` span, `tool_result` "
            "inferred from what a tool returned: labeled, because it counts more than was shown."
        ),
    )
    offset: int = Field(default=0, ge=0, le=10000)
    page: int = Field(default=1, ge=1, le=1000, description='"See more" is the same list with `page + 1`.')
    parent_list_id: ShortStr | None = None
    visible_k: Annotated[int, Field(ge=1, le=100)] | None = Field(
        default=None, description="How many of the first items were visible on delivery."
    )


class PromoteRequest(Model):
    """Moves turns from the short tier (every turn, 7 days) to the kept one, by conversation or by id, with
    the reason: the complaint arrives days after the turn.
    """

    conversation_id: IdStr | None = None
    reason: Literal["complaint", "bug_report", "review", "other"]
    turn_ids: list[TurnId] = Field(default_factory=list, max_length=500)


class PromoteResponse(ResponseModel):
    already_kept: int
    not_found: int = Field(description="Turns no longer in the short tier, or never recorded.")
    promoted: int


class ReplayAssertion(Model):
    """A structural check on the replayed turn's record, evaluated by the runner. The replay spec fixes each
    kind's `args` and how it is evaluated; a kind the runner cannot evaluate yields `not_checked`.
    """

    args: dict[ShortStr, Any] = Field(default_factory=dict, max_length=20)
    id: Annotated[str, StringConstraints(pattern=r"^[a-z0-9][a-z0-9_.-]{0,63}$")]
    kind: Literal[
        "tool_called",
        "tool_not_called",
        "hard_respected",
        "no_denial_with_results",
        "claims_traced",
        "claims_match_state",
        "no_promise_without_action",
        "expected_in_topk",
        "handoff_when",
        "effect_once",
        "budget",
        "lexicon",
        "tools_offered_match",
    ]
    suggested: bool = Field(default=False, description="Suggested by rule from the recorded turn.")
    turn_id: TurnId | None = Field(
        default=None, description="The one turn of the scenario it applies to; every turn when absent."
    )


class ReplayBlocker(ResponseModel):
    """Why a turn cannot be run again: `content_mode` (`hash_only` keeps no value), `fidelity` (only a gold
    record can be replayed), `completeness` (only a complete one) or `missing_pin` (the pin the recording
    requires and the record lacks).
    """

    reason: Literal["content_mode", "fidelity", "completeness", "missing_pin"]
    value: ShortStr = Field(description="E.g. `hash_only`, `bronze`, `partial` or the pin's name, `model`.")


class ReplayHistoryEntry(ResponseModel):
    at: datetime
    role: Literal["customer", "agent", "human"]
    text: str | None = None


class ReplayInput(ResponseModel):
    kind: Literal["message", "action", "event", "timer"]
    text: str | None = Field(default=None, description="The customer's message that opened the turn, masked.")


class Seen(Model):
    """A ping of the list component: how far the person saw."""

    exposure_id: UUID
    for_: Annotated[str, StringConstraints(pattern=r"^(?:self|gift|beneficiary:[A-Za-z0-9_-]{1,64})$")] = (
        Field(default="self", alias="for")
    )
    kind: Literal["seen"]
    max_index_seen: int = Field(ge=1, le=10000, description="The highest `pos` the component showed.")


class TurnAgent(Model):
    name: ShortStr = Field(description="The agent's name inside the source, e.g. `closing`.")
    parent_turn_id: TurnId | None = Field(
        default=None,
        description="The turn that opened this one as a sub-turn (a sub-agent, an agent as tool).",
    )
    role: ShortStr | None = Field(default=None, description="Free text, e.g. `specialist` or `router`.")


class TurnBlob(Model):
    """A large value of the record. `sha256` is over its normalized canonical JSON (RFC 8785): the same value
    always has the same hash.
    """

    content: Any = Field(default=None, description="The value itself, only in `stored` mode.")
    pointer: Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9+.-]*://\S{1,1024}$")] | None = Field(
        default=None, description="Where the customer keeps it, in `pointer` mode."
    )
    sha256: Sha256
    size: Annotated[int, Field(ge=0)] | None = Field(default=None, description="Bytes of the canonical form.")


class TurnCompilerPins(Model):
    compiler: Version | None = Field(
        default=None, description="The context compiler's version, from the pack."
    )
    pack_hash: Version | None = Field(default=None, description="The hash of the pack this turn read.")


class TurnPins(Model):
    """What must be the same for a replay to reproduce this turn. The recording document says which are
    required; a turn without one of them is kept, marked not replayable.
    """

    assembler: Version | None = Field(
        default=None, description="The version of the company's context assembler."
    )
    corpus_digest: Sha256 | None = Field(
        default=None,
        description="Digest of the files the agent consults, computed in the SDK; never the files.",
    )
    model: Version | None = Field(default=None, description="The exact model the agent called.")
    niadra: TurnCompilerPins | None = None
    prompts: dict[ShortStr, Version] = Field(
        default_factory=dict, max_length=50, description="Prompt name -> version, e.g. `core` -> `v16`."
    )
    tool_schemas: dict[ShortStr, Sha256] = Field(
        default_factory=dict, max_length=200, description="Tool name -> hash of its schema."
    )


class TurnBuild(Model):
    adapter: ShortStr | None = Field(
        default=None, description="The framework adapter and its version, if any."
    )
    pins: TurnPins = Field(default_factory=TurnPins)
    sdk: ShortStr | None = Field(default=None, description="E.g. `niadra-python/0.7.0`.")


class TurnConstraints(Model):
    """What the SDK measured of the constraints block on one tool call: sent, checked, violated."""

    constraints: Version = Field(description="The version of the constraints block applied.")
    hard_sent: list[ShortStr] = Field(default_factory=list, max_length=200)
    relaxed: Literal["declared", "suspected"] | None = None
    results_checked: int = Field(ge=0)
    unverifiable: int = Field(ge=0)
    violations: int = Field(ge=0)


class TurnProvenance(Model):
    scope: Literal["global", "customer", "context"] = "global"
    source: Literal["live", "snapshot", "cache"]
    source_observed_at: datetime


class TurnObservation(Model):
    """State a tool result showed, with provenance per field; without provenance it is display only."""

    fields: dict[ShortStr, Any] = Field(max_length=200)
    provenance: TurnProvenance | None = None
    ref: ObjectKey = Field(
        description="An object as `<type>:<namespace>:<id>`, e.g. `item_variant:store:991`."
    )


class TurnTokens(Model):
    cached: int = Field(default=0, ge=0)
    input: int = Field(ge=0, alias="in")
    output: int = Field(ge=0, alias="out")


class TurnCall(Model):
    """One tool or model call of the turn, copied deep at the moment it happened."""

    applied: TurnConstraints | None = None
    args: BlobKey | None = None
    args_hash: Sha256 | None = Field(default=None, description="Of the normalized arguments.")
    attempt: int = Field(default=1, ge=1)
    cache_hit: bool = False
    call_id: ShortStr
    cost_units: dict[ShortStr, int] = Field(default_factory=dict, max_length=20)
    effect_key: IdStr | None = None
    kind: Literal["tool", "model"]
    latency_ms: Annotated[int, Field(ge=0)] | None = None
    name: ShortStr | None = Field(
        default=None, description="The tool's name, or the model's for a model call."
    )
    observations: list[TurnObservation] = Field(default_factory=list, max_length=200)
    parent_call_id: ShortStr | None = None
    result_model: BlobKey | None = Field(default=None, description="The result as the model saw it.")
    result_ui: BlobKey | None = Field(default=None, description="The result as the interface got it.")
    status: Literal["ok", "error", "timeout", "cancelled"] = "ok"
    synthetic: bool = False
    tokens: TurnTokens | None = None
    truncated: bool = Field(default=False, description="Arguments or result arrived cut (OpenTelemetry).")


class TurnCoordination(Model):
    decision: Literal["allow", "defer", "deny", "handoff_to"]
    decision_id: IdStr


class TurnCost(Model):
    usd: float = Field(ge=0.0)


class TurnEffect(Model):
    key: IdStr
    state: Literal["reserved", "done", "failed", "unknown_outcome"]


class TurnOutput(Model):
    document: BlobKey | None = Field(default=None, description="A document the turn wrote, by its blob.")
    event_keys: list[IdStr] = Field(
        default_factory=list,
        max_length=50,
        description="The events `track()` sent for what the turn said: the text is never repeated here.",
    )
    handoff_id: IdStr | None = None
    ui: BlobKey | None = None


class TurnRead(Model):
    """A read the turn made from Niadra, by its version: the pack by ETag, a block by its version."""

    blob: BlobKey | None = Field(default=None, description="The content read, when the recording keeps it.")
    etag: Version | None = None
    receipt_id: IdStr | None = None
    surface: Literal[
        "pack", "state", "constraints", "coordination", "budget", "history", "agent_memory", "agent_state"
    ]
    version: Version | None = None


class Unwatch(Model):
    for_: Annotated[str, StringConstraints(pattern=r"^(?:self|gift|beneficiary:[A-Za-z0-9_-]{1,64})$")] = (
        Field(default="self", alias="for")
    )
    kind: Literal["unwatch"]
    ref: ObjectKey


class Watch(Model):
    """An explicit "let me know when": the only way an interest raises a notice."""

    condition: Annotated[str, StringConstraints(min_length=1, max_length=500)] = Field(
        description="A `niadra-expr` expression over the object's fields."
    )
    consent_event_key: IdStr
    expires_at: datetime | None = None
    for_: Annotated[str, StringConstraints(pattern=r"^(?:self|gift|beneficiary:[A-Za-z0-9_-]{1,64})$")] = (
        Field(default="self", alias="for")
    )
    kind: Literal["watch"]
    ref: ObjectKey


class TurnRecord(Model):
    """One turn, from its input (a message, an interface action, an event, a timer firing) to the last thing
    it emitted to the customer or to a document.
    """

    agent: TurnAgent
    blobs: dict[BlobKey, TurnBlob] = Field(default_factory=dict, max_length=1000)
    build: TurnBuild = Field(default_factory=TurnBuild)
    calls: list[TurnCall] = Field(default_factory=list, max_length=500)
    claims: list[ClaimRecord] = Field(default_factory=list, max_length=500)
    completeness: Literal["complete", "partial", "incomplete", "unknown"] = "complete"
    content_mode: Literal["stored", "pointer", "hash_only"]
    conversation_id: IdStr | None = None
    coordination: list[TurnCoordination] = Field(default_factory=list, max_length=50)
    cost: TurnCost | None = None
    effects: list[TurnEffect] = Field(default_factory=list, max_length=50)
    ended_at: datetime | None = None
    fidelity: Literal["bronze", "silver", "gold"] = "gold"
    flags: list[
        Literal[
            "error",
            "guard_acted",
            "guard_budget_exceeded",
            "handoff",
            "assertion_failed",
            "synthetic",
            "incomplete",
            "negative_feedback",
            "truncated",
        ]
    ] = Field(default_factory=list, max_length=20)
    interactions: list[
        Annotated[
            Presented | Seen | Engaged | Feedback | Preference | Attribute | Watch | Unwatch,
            Field(discriminator="kind"),
        ]
    ] = Field(default_factory=list, max_length=200)
    kind: Literal["message", "action", "event", "timer"] = "message"
    latency_ms: Annotated[int, Field(ge=0)] | None = None
    output: TurnOutput = Field(default_factory=TurnOutput)
    reads: list[TurnRead] = Field(default_factory=list, max_length=20)
    spec: Literal["turn-record.v0"] = "turn-record.v0"
    started_at: datetime
    task_id: IdStr | None = None
    turn_id: TurnId


class ReplayCase(ResponseModel):
    """What the replay runner needs to run a turn again inside the company's boundary: the record, with the
    kept values in `stored` mode and the pointers and digests otherwise; the pins; the conversation's
    masked history up to the turn, ending with the turn's own input; and the assertions. The pack of the
    time is the blob of the record's `pack` read.
    """

    assertions: list[ReplayAssertion] = Field(default_factory=list)
    case_id: IdStr
    expires_at: datetime = Field(description="When the turn leaves storage; after it, `replay_expired`.")
    history: list[ReplayHistoryEntry] = Field(default_factory=list)
    input: ReplayInput
    mode: Literal["hermetic_turn", "hermetic_conversation", "era_memory"]
    record: TurnRecord
    required_pins: list[Literal["prompts", "corpus_digest", "model", "assembler", "tool_schemas"]]
    scenario_id: IdStr | None = None
    turn_id: TurnId
    vary: list[Literal["prompts", "corpus_digest", "model", "assembler", "tool_schemas"]] = Field(
        default_factory=list
    )


class ReplayCaseRequest(Model):
    """A case for one turn, alone or as part of a scenario. `build` is the build the runner will run; every
    pin the recording requires must match the recorded one, except the pins in `vary`, which the run
    changes on purpose.
    """

    build: TurnBuild
    mode: Literal["hermetic_turn", "hermetic_conversation", "era_memory"] = "hermetic_turn"
    scenario_id: IdStr | None = None
    turn_id: TurnId
    vary: list[Literal["prompts", "corpus_digest", "model", "assembler", "tool_schemas"]] = Field(
        default_factory=list, max_length=5
    )


class ReplayResult(Model):
    """One execution of one case. `infrastructure_error` (the agent raised, a blob could not be fetched or did
    not match its digest, a timeout) is counted apart and never fails an assertion; `pin_mismatch` is a
    case the runner stopped at its pin check.
    """

    assertions: list[AssertionOutcome] = Field(default_factory=list, max_length=50)
    case_id: IdStr | None = None
    divergent_calls: int = Field(default=0, ge=0)
    error: Annotated[str, StringConstraints(max_length=500)] | None = None
    latency_ms: Annotated[int, Field(ge=0)] | None = None
    paraphrase: bool = Field(
        default=False, description="The run's input was a paraphrase of the recorded one."
    )
    run: int = Field(ge=1, le=100)
    scenario_id: IdStr
    status: Literal["completed", "pin_mismatch", "infrastructure_error"]
    turn_id: TurnId


class Scenario(ResponseModel):
    assertions: list[ReplayAssertion]
    created_at: datetime
    name: str
    origin: Literal["manual", "report"]
    scenario_id: IdStr
    status: Literal["active", "retired"]
    turn_ids: list[TurnId]
    updated_at: datetime
    version: int = Field(description="Grows with every change of the name, the assertions or the status.")


class ScenarioCreate(Model):
    """Turns kept as a scenario, with the assertions they must keep passing; without assertions, the ones
    suggested by rule from the turns.
    """

    assertions: list[ReplayAssertion] = Field(default_factory=list, max_length=50)
    name: ShortStr
    turn_ids: list[TurnId] = Field(min_length=1, max_length=50)


class ScenarioFromReport(Model):
    """A bug report becomes a scenario: its turns are kept and assertions suggested by rule, from the turns
    and from words of the description. The description is read, never stored.
    """

    conversation_id: IdStr | None = None
    description: Annotated[str, StringConstraints(max_length=2000)] | None = None
    name: ShortStr | None = None
    turn_ids: list[TurnId] = Field(default_factory=list, max_length=50)


class ScenarioPage(ResponseModel):
    items: list[Scenario]
    next_cursor: str | None = None


class ScenarioVerdict(ResponseModel):
    assertions: list[AssertionStats]
    baseline_run_id: IdStr | None = Field(
        default=None, description="The earlier run compared against; none when it was the recording."
    )
    completed: int
    infrastructure_errors: int
    needs_paraphrase: bool = Field(
        description="An assertion passed and failed across the runs: its next run must include paraphrases."
    )
    pin_mismatches: int
    scenario_id: IdStr
    verdict: Literal["pass", "flaky", "infrastructure_error", "pin_mismatch", "regression"]


class ScenarioRunSummary(ResponseModel):
    scenarios: list[ScenarioVerdict] = Field(default_factory=list)


class ScenarioRun(ResponseModel):
    build: TurnBuild
    created_at: datetime
    mode: Literal["hermetic_turn", "hermetic_conversation", "era_memory"]
    run_id: IdStr
    status: Literal["pending", "done"]
    summary: ScenarioRunSummary
    vary: list[Literal["prompts", "corpus_digest", "model", "assembler", "tool_schemas"]] = Field(
        default_factory=list
    )
    verdict: Literal["pass", "flaky", "infrastructure_error", "pin_mismatch", "regression"] | None = Field(
        default=None, description="The worst of the scenarios' verdicts."
    )


class ScenarioRunCreate(Model):
    """What the company's CI reports after running the scenarios N times: the statistics stay with Niadra.
    Every pin the recording requires must match each scenario's recorded build, except those in `vary`.
    """

    build: TurnBuild
    mode: Literal["hermetic_turn", "hermetic_conversation", "era_memory"] = "hermetic_turn"
    results: list[ReplayResult] = Field(min_length=1, max_length=5000)
    runs: Annotated[int, Field(ge=1, le=100)] | None = None
    scenario_ids: list[IdStr] = Field(min_length=1, max_length=200)
    vary: list[Literal["prompts", "corpus_digest", "model", "assembler", "tool_schemas"]] = Field(
        default_factory=list, max_length=5
    )


class ScenarioUpdate(Model):
    assertions: Annotated[list[ReplayAssertion], Field(max_length=50)] | None = None
    name: ShortStr | None = None
    status: Literal["active", "retired"] | None = None


class TurnIndexEntry(ResponseModel):
    """One row of the kept tier's index, as the day's anchored root counts it: ids, times, the build and the
    mode, never what the turn said. `digest` is SHA-256 over the RFC 8785 form of the other fields.
    """

    agent: ShortStr
    build_hash: str | None = None
    content_mode: Literal["stored", "pointer", "hash_only"]
    digest: Sha256
    kept_at: datetime
    kind: Literal["message", "action", "event", "timer"]
    source_id: IdStr
    started_at: datetime
    turn_id: TurnId


class TurnIndexPage(ResponseModel):
    """The rows the kept tier took on one UTC day, in turn id order. Their digests, as leaves in that order,
    make the `turns.root` of the day's `audit.root` event (RFC 6962 prefixes, an odd node carried up), for
    the company's own audit chain to anchor.
    """

    day: date
    items: list[TurnIndexEntry]
    next_cursor: str | None = None


class TurnSearchRequest(Model):
    """A search over the kept tier. The conversation id travels in the body, never in the URL."""

    agent: ShortStr | None = None
    conversation_id: IdStr | None = None
    cursor: Annotated[str, StringConstraints(max_length=200)] | None = None
    flags: list[
        Literal[
            "error",
            "guard_acted",
            "guard_budget_exceeded",
            "handoff",
            "assertion_failed",
            "synthetic",
            "incomplete",
            "negative_feedback",
            "truncated",
        ]
    ] = Field(default_factory=list, max_length=20)
    limit: int = Field(default=50, ge=1, le=200)
    since: datetime | None = None
    until: datetime | None = None


class TurnSummary(ResponseModel):
    agent: ShortStr
    completeness: Literal["complete", "partial", "incomplete", "unknown"]
    fidelity: Literal["bronze", "silver", "gold"]
    flags: list[
        Literal[
            "error",
            "guard_acted",
            "guard_budget_exceeded",
            "handoff",
            "assertion_failed",
            "synthetic",
            "incomplete",
            "negative_feedback",
            "truncated",
        ]
    ] = Field(default_factory=list)
    kind: Literal["message", "action", "event", "timer"]
    replayable: bool
    started_at: datetime
    tier: Literal["short", "kept"]
    turn_id: TurnId


class TurnSearchResponse(ResponseModel):
    items: list[TurnSummary]
    next_cursor: str | None = None


class TurnView(ResponseModel):
    """A recorded turn as the viewer shows it. In `pointer` and `hash_only` modes, blobs have no content."""

    kept_until: datetime | None = None
    record: TurnRecord
    replay_blockers: list[ReplayBlocker] = Field(
        default_factory=list, description="Why the turn cannot be run again; empty when it can."
    )
    replayable: bool = Field(description="Every pin the recording requires is there.")
    tier: Literal["short", "kept"]


class TurnsRequest(Model):
    turns: list[TurnRecord] = Field(min_length=1, max_length=50)


class TurnsResponse(ResponseModel):
    """200 when every turn was taken, 207 with one error per rejected turn (by index)."""

    accepted: int
    duplicates: int = Field(description="Turns already recorded: the same turn sent twice is one.")
    errors: list[ItemError] = Field(default_factory=list)
