# Generated by scripts/sync_spec.py from spec/openapi/cell.json. Do not edit.
"""Turn records, replay, scenarios, the change log, data issues and the notification feed."""

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Any, Literal

from pydantic import ConfigDict, Field, StringConstraints

from niadra.models._base import IdStr, Model, ResponseModel, ShortStr
from niadra.models.common import ObjectRef
from niadra.models.events import ItemError

BlobKey = Annotated[str, StringConstraints(pattern=r"^[a-z]{1,8}:[A-Za-z0-9_-]{1,32}$")]
ObjectKey = Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9_]{0,39}:[^:\s]{1,256}:\S{1,512}$")]
Sha256 = Annotated[str, StringConstraints(pattern=r"^sha256:[0-9a-f]{64}$")]
TurnId = Annotated[str, StringConstraints(pattern=r"^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$")]
Version = Annotated[str, StringConstraints(min_length=1, max_length=128)]


class Change(ResponseModel):
    """One entry of the change log the bisection walks."""

    after: str | None = None
    agent: ShortStr | None = None
    at: datetime
    before: str | None = None
    kind: Literal["prompt", "model", "code", "data", "config", "compiler"]


class ChangePage(ResponseModel):
    items: list[Change]
    next_cursor: str | None = None


class DataIssue(ResponseModel):
    acknowledged_at: datetime | None = None
    field: ShortStr | None = None
    issue_id: IdStr
    kind: Literal[
        "null_field",
        "out_of_vocabulary",
        "stale_source",
        "coverage_drop",
        "invalid_value",
        "divergence",
        "drift",
        "rule_conflict",
    ]
    object_type: ShortStr | None = None
    occurrences: int
    opened_at: datetime
    refs: list[ObjectRef] = Field(default_factory=list, max_length=50)
    source: ShortStr | None = None


class DataIssuePage(ResponseModel):
    items: list[DataIssue]
    next_cursor: str | None = None


class Notification(ResponseModel):
    """A webhook's body, for who pulls instead of receiving it: the same body, in `change_seq` order."""

    data: dict[str, Any]
    id: IdStr
    occurred_at: datetime
    type: ShortStr


class NotificationPage(ResponseModel):
    items: list[Notification]
    next_cursor: str | None = None


class PromoteRequest(Model):
    """Moves turns from the short tier (every turn, 7 days) to the kept one, by conversation or by id, with
    the reason: the complaint arrives days after the turn.
    """

    conversation_id: IdStr | None = None
    reason: Literal["complaint", "bug_report", "review", "other"]
    turn_ids: list[TurnId] = Field(default_factory=list, max_length=500)


class PromoteResponse(ResponseModel):
    already_kept: int
    not_found: int = Field(description="Turns no longer in the short tier, or never recorded.")
    promoted: int


class TurnAgent(Model):
    name: ShortStr = Field(description="The agent's name inside the source, e.g. `closing`.")
    parent_turn_id: TurnId | None = Field(
        default=None,
        description="The turn that opened this one as a sub-turn (a sub-agent, an agent as tool).",
    )
    role: ShortStr | None = Field(default=None, description="Free text, e.g. `specialist` or `router`.")


class TurnBlob(Model):
    """A large value of the record. `sha256` is over its normalized canonical JSON (RFC 8785): the same value
    always has the same hash.
    """

    content: Any = Field(default=None, description="The value itself, only in `stored` mode.")
    pointer: Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9+.-]*://\S{1,1024}$")] | None = Field(
        default=None, description="Where the customer keeps it, in `pointer` mode."
    )
    sha256: Sha256
    size: Annotated[int, Field(ge=0)] | None = Field(default=None, description="Bytes of the canonical form.")


class TurnCompilerPins(Model):
    compiler: Version | None = Field(
        default=None, description="The context compiler's version, from the pack."
    )
    pack_hash: Version | None = Field(default=None, description="The hash of the pack this turn read.")


class TurnPins(Model):
    """What must be the same for a replay to reproduce this turn. The recording document says which are
    required; a turn without one of them is kept, marked not replayable.
    """

    assembler: Version | None = Field(
        default=None, description="The version of the company's context assembler."
    )
    corpus_digest: Sha256 | None = Field(
        default=None,
        description="Digest of the files the agent consults, computed in the SDK; never the files.",
    )
    model: Version | None = Field(default=None, description="The exact model the agent called.")
    niadra: TurnCompilerPins | None = None
    prompts: dict[ShortStr, Version] = Field(
        default_factory=dict, max_length=50, description="Prompt name -> version, e.g. `core` -> `v16`."
    )
    tool_schemas: dict[ShortStr, Sha256] = Field(
        default_factory=dict, max_length=200, description="Tool name -> hash of its schema."
    )


class TurnBuild(Model):
    adapter: ShortStr | None = Field(
        default=None, description="The framework adapter and its version, if any."
    )
    pins: TurnPins = Field(default_factory=TurnPins)
    sdk: ShortStr | None = Field(default=None, description="E.g. `niadra-python/0.7.0`.")


class TurnConstraints(Model):
    """What the SDK measured of the constraints block on one tool call: sent, checked, violated."""

    constraints: Version = Field(description="The version of the constraints block applied.")
    hard_sent: list[ShortStr] = Field(default_factory=list, max_length=200)
    relaxed: Literal["declared", "suspected"] | None = None
    results_checked: int = Field(ge=0)
    unverifiable: int = Field(ge=0)
    violations: int = Field(ge=0)


class TurnProvenance(Model):
    scope: Literal["global", "customer", "context"] = "global"
    source: Literal["live", "snapshot", "cache"]
    source_observed_at: datetime


class TurnObservation(Model):
    """State a tool result showed, with provenance per field; without provenance it is display only."""

    fields: dict[ShortStr, Any] = Field(max_length=200)
    provenance: TurnProvenance | None = None
    ref: ObjectKey = Field(
        description="An object as `<type>:<namespace>:<id>`, e.g. `item_variant:store:991`."
    )


class TurnTokens(Model):
    cached: int = Field(default=0, ge=0)
    input: int = Field(ge=0, alias="in")
    output: int = Field(ge=0, alias="out")


class TurnCall(Model):
    """One tool or model call of the turn, copied deep at the moment it happened."""

    applied: TurnConstraints | None = None
    args: BlobKey | None = None
    args_hash: Sha256 | None = Field(default=None, description="Of the normalized arguments.")
    attempt: int = Field(default=1, ge=1)
    cache_hit: bool = False
    call_id: ShortStr
    cost_units: dict[ShortStr, int] = Field(default_factory=dict, max_length=20)
    effect_key: IdStr | None = None
    kind: Literal["tool", "model"]
    latency_ms: Annotated[int, Field(ge=0)] | None = None
    name: ShortStr | None = Field(
        default=None, description="The tool's name, or the model's for a model call."
    )
    observations: list[TurnObservation] = Field(default_factory=list, max_length=200)
    parent_call_id: ShortStr | None = None
    result_model: BlobKey | None = Field(default=None, description="The result as the model saw it.")
    result_ui: BlobKey | None = Field(default=None, description="The result as the interface got it.")
    status: Literal["ok", "error", "timeout", "cancelled"] = "ok"
    synthetic: bool = False
    tokens: TurnTokens | None = None
    truncated: bool = Field(default=False, description="Arguments or result arrived cut (OpenTelemetry).")


class TurnEvidence(Model):
    anchor: BlobKey | None = Field(default=None, description="The quoted text a fact is anchored to.")
    call_id: ShortStr | None = None
    field: ShortStr | None = None


class TurnClaim(Model):
    """A claim contract verdict, found by the SDK before the text reached the customer or a document. The
    fields are the claim contract's record; its spec fixes the vocabularies of `verdict` and `action`, so
    this record takes them as names until that model replaces this one.
    """

    action: ShortStr = Field(default="none", description="E.g. `none`, `warn`, `count`, `block`.")
    category: ShortStr
    class_: Literal["money", "percent", "date", "quantity", "count", "duration", "dosage", "text"] | None = (
        Field(default=None, alias="class")
    )
    evidence: TurnEvidence | None = None
    nature: Literal["computed", "quoted", "model"] | None = None
    role: ShortStr | None = None
    span: tuple[int, int] | None = Field(default=None, description="Start and end offsets in the output.")
    value: Any = None
    verdict: ShortStr = Field(description="E.g. `matched`, `role_ambiguous`, `below_threshold`.")


class TurnCoordination(Model):
    decision: Literal["allow", "defer", "deny", "handoff_to"]
    decision_id: IdStr


class TurnCost(Model):
    usd: float = Field(ge=0.0)


class TurnEffect(Model):
    key: IdStr
    state: Literal["reserved", "done", "failed", "unknown_outcome"]


class TurnInteraction(Model):
    """What the person was shown or did in the turn. Its fields are the `interaction.v0` spec's, validated
    when the turn is applied; until that spec's `Interaction` model lands, the record fixes only the kind
    and keeps the rest as it came. The swap narrows the type and changes no document.
    """

    model_config = ConfigDict(extra="allow", frozen=True, populate_by_name=True)

    kind: Literal["presented", "seen", "engaged", "feedback", "preference", "attribute", "watch", "unwatch"]


class TurnOutput(Model):
    document: BlobKey | None = Field(default=None, description="A document the turn wrote, by its blob.")
    event_keys: list[IdStr] = Field(
        default_factory=list,
        max_length=50,
        description="The events `track()` sent for what the turn said: the text is never repeated here.",
    )
    handoff_id: IdStr | None = None
    ui: BlobKey | None = None


class TurnRead(Model):
    """A read the turn made from Niadra, by its version: the pack by ETag, a block by its version."""

    blob: BlobKey | None = Field(default=None, description="The content read, when the recording keeps it.")
    etag: Version | None = None
    receipt_id: IdStr | None = None
    surface: Literal[
        "pack", "state", "constraints", "coordination", "budget", "history", "agent_memory", "agent_state"
    ]
    version: Version | None = None


class TurnRecord(Model):
    """One turn, from its input (a message, an interface action, an event, a timer firing) to the last thing
    it emitted to the customer or to a document.
    """

    agent: TurnAgent
    blobs: dict[BlobKey, TurnBlob] = Field(default_factory=dict, max_length=1000)
    build: TurnBuild = Field(default_factory=TurnBuild)
    calls: list[TurnCall] = Field(default_factory=list, max_length=500)
    claims: list[TurnClaim] = Field(default_factory=list, max_length=500)
    completeness: Literal["complete", "partial", "incomplete", "unknown"] = "complete"
    content_mode: Literal["stored", "pointer", "hash_only"]
    conversation_id: IdStr | None = None
    coordination: list[TurnCoordination] = Field(default_factory=list, max_length=50)
    cost: TurnCost | None = None
    effects: list[TurnEffect] = Field(default_factory=list, max_length=50)
    ended_at: datetime | None = None
    fidelity: Literal["bronze", "silver", "gold"] = "gold"
    flags: list[
        Literal[
            "error",
            "guard_acted",
            "guard_budget_exceeded",
            "handoff",
            "assertion_failed",
            "synthetic",
            "incomplete",
            "negative_feedback",
            "truncated",
        ]
    ] = Field(default_factory=list, max_length=20)
    interactions: list[TurnInteraction] = Field(default_factory=list, max_length=200)
    kind: Literal["message", "action", "event", "timer"] = "message"
    latency_ms: Annotated[int, Field(ge=0)] | None = None
    output: TurnOutput = Field(default_factory=TurnOutput)
    reads: list[TurnRead] = Field(default_factory=list, max_length=20)
    spec: Literal["turn-record.v0"] = "turn-record.v0"
    started_at: datetime
    task_id: IdStr | None = None
    turn_id: TurnId


class ReplayCase(ResponseModel):
    """What the SDK's replay runner needs to run the turn again inside the customer's boundary: the frame,
    pointers and hashes, pins, the pack and view of the time, the masked history up to the turn and the
    suggested assertions. A pin that does not match stops the case with `pin_mismatch`.
    """

    assertions: list[dict[str, Any]] = Field(default_factory=list)
    case_id: IdStr
    expires_at: datetime = Field(description="After it, the case answers 410 `replay_expired`.")
    history: list[dict[str, Any]] = Field(default_factory=list)
    mode: Literal["hermetic_turn", "hermetic_conversation", "era_memory"]
    record: TurnRecord


class ReplayCaseRequest(Model):
    mode: Literal["hermetic_turn", "hermetic_conversation", "era_memory"] = "hermetic_turn"
    turn_id: TurnId


class Scenario(ResponseModel):
    assertions: list[dict[str, Any]]
    created_at: datetime
    name: str
    origin: Literal["manual", "report"]
    scenario_id: IdStr
    status: Literal["active", "retired"]
    turn_ids: list[TurnId]
    version: int


class ScenarioCreate(Model):
    assertions: list[dict[str, Any]] = Field(default_factory=list, max_length=50)
    name: ShortStr
    turn_ids: list[TurnId] = Field(min_length=1, max_length=50)


class ScenarioFromReport(Model):
    """A bug report becomes a scenario: its turns are promoted and assertions suggested by rule."""

    conversation_id: IdStr | None = None
    description: Annotated[str, StringConstraints(max_length=2000)] | None = None
    turn_ids: list[TurnId] = Field(default_factory=list, max_length=50)


class ScenarioPage(ResponseModel):
    items: list[Scenario]
    next_cursor: str | None = None


class ScenarioRun(ResponseModel):
    run_id: IdStr
    status: Literal["pending", "done"]
    summary: dict[str, Any] = Field(default_factory=dict)
    verdict: Literal["pass", "regression", "flaky", "infrastructure_error"] | None = None


class ScenarioRunCreate(Model):
    """The customer's CI reports N executions of the scenarios; the statistics stay with Niadra."""

    build: TurnBuild
    results: list[dict[str, Any]] = Field(min_length=1, max_length=5000)
    scenario_ids: list[IdStr] = Field(min_length=1, max_length=200)


class ScenarioUpdate(Model):
    assertions: Annotated[list[dict[str, Any]], Field(max_length=50)] | None = None
    name: ShortStr | None = None
    status: Literal["active", "retired"] | None = None


class TurnSearchRequest(Model):
    """A search over the kept tier. The conversation id travels in the body, never in the URL."""

    agent: ShortStr | None = None
    conversation_id: IdStr | None = None
    cursor: Annotated[str, StringConstraints(max_length=200)] | None = None
    flags: list[
        Literal[
            "error",
            "guard_acted",
            "guard_budget_exceeded",
            "handoff",
            "assertion_failed",
            "synthetic",
            "incomplete",
            "negative_feedback",
            "truncated",
        ]
    ] = Field(default_factory=list, max_length=20)
    limit: int = Field(default=50, ge=1, le=200)
    since: datetime | None = None
    until: datetime | None = None


class TurnSummary(ResponseModel):
    agent: ShortStr
    completeness: Literal["complete", "partial", "incomplete", "unknown"]
    fidelity: Literal["bronze", "silver", "gold"]
    flags: list[
        Literal[
            "error",
            "guard_acted",
            "guard_budget_exceeded",
            "handoff",
            "assertion_failed",
            "synthetic",
            "incomplete",
            "negative_feedback",
            "truncated",
        ]
    ] = Field(default_factory=list)
    kind: Literal["message", "action", "event", "timer"]
    replayable: bool
    started_at: datetime
    tier: Literal["short", "kept"]
    turn_id: TurnId


class TurnSearchResponse(ResponseModel):
    items: list[TurnSummary]
    next_cursor: str | None = None


class TurnView(ResponseModel):
    """A recorded turn as the viewer shows it. In `pointer` and `hash_only` modes, blobs have no content."""

    kept_until: datetime | None = None
    record: TurnRecord
    replayable: bool = Field(description="Every pin the recording requires is there.")
    tier: Literal["short", "kept"]


class TurnsRequest(Model):
    turns: list[TurnRecord] = Field(min_length=1, max_length=50)


class TurnsResponse(ResponseModel):
    """200 when every turn was taken, 207 with one error per rejected turn (by index)."""

    accepted: int
    duplicates: int = Field(description="Turns already recorded: the same turn sent twice is one.")
    errors: list[ItemError] = Field(default_factory=list)
